// Code generated by "enumer -type=SearchTargetType -json -transform=snake -trimprefix=Target"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SearchTargetTypeName = "usergrouppagepost"

var _SearchTargetTypeIndex = [...]uint8{0, 4, 9, 13, 17}

const _SearchTargetTypeLowerName = "usergrouppagepost"

func (i SearchTargetType) String() string {
	if i < 0 || i >= SearchTargetType(len(_SearchTargetTypeIndex)-1) {
		return fmt.Sprintf("SearchTargetType(%d)", i)
	}
	return _SearchTargetTypeName[_SearchTargetTypeIndex[i]:_SearchTargetTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SearchTargetTypeNoOp() {
	var x [1]struct{}
	_ = x[TargetUser-(0)]
	_ = x[TargetGroup-(1)]
	_ = x[TargetPage-(2)]
	_ = x[TargetPost-(3)]
}

var _SearchTargetTypeValues = []SearchTargetType{TargetUser, TargetGroup, TargetPage, TargetPost}

var _SearchTargetTypeNameToValueMap = map[string]SearchTargetType{
	_SearchTargetTypeName[0:4]:        TargetUser,
	_SearchTargetTypeLowerName[0:4]:   TargetUser,
	_SearchTargetTypeName[4:9]:        TargetGroup,
	_SearchTargetTypeLowerName[4:9]:   TargetGroup,
	_SearchTargetTypeName[9:13]:       TargetPage,
	_SearchTargetTypeLowerName[9:13]:  TargetPage,
	_SearchTargetTypeName[13:17]:      TargetPost,
	_SearchTargetTypeLowerName[13:17]: TargetPost,
}

var _SearchTargetTypeNames = []string{
	_SearchTargetTypeName[0:4],
	_SearchTargetTypeName[4:9],
	_SearchTargetTypeName[9:13],
	_SearchTargetTypeName[13:17],
}

// SearchTargetTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SearchTargetTypeString(s string) (SearchTargetType, error) {
	if val, ok := _SearchTargetTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SearchTargetTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SearchTargetType values", s)
}

// SearchTargetTypeValues returns all values of the enum
func SearchTargetTypeValues() []SearchTargetType {
	return _SearchTargetTypeValues
}

// SearchTargetTypeStrings returns a slice of all String values of the enum
func SearchTargetTypeStrings() []string {
	strs := make([]string, len(_SearchTargetTypeNames))
	copy(strs, _SearchTargetTypeNames)
	return strs
}

// IsASearchTargetType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SearchTargetType) IsASearchTargetType() bool {
	for _, v := range _SearchTargetTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SearchTargetType
func (i SearchTargetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SearchTargetType
func (i *SearchTargetType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SearchTargetType should be a string, got %s", data)
	}

	var err error
	*i, err = SearchTargetTypeString(s)
	return err
}
