version: "3.8"

name: "BE-modular-golang"
services:
  postgres_db_BE-modular-golang:
   image: postgres:15
   restart: unless-stopped
   container_name: postgres_db_BE-modular-golang
   environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: be_modular_golang
   ports:
    - "5432:5432"
   volumes:
    - pgdata_BE-modular-golang:/var/lib/postgresql/data
    - ./init/initpostgres.sql:/docker-entrypoint-initdb.d/init-db.sql # Thêm dòng này
   networks:
    - be_modular_golang_network
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin_BE-modular-golang:
   image: dpage/pgadmin4 
   container_name : pgadmin_BE-modular-golang
   restart: unless-stopped
   environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
   ports:
   - "5050:80"
   networks:
   - be_modular_golang_network
   depends_on:
     - postgres_db_BE-modular-golang
  redis_BE-modular-golang:
    image: redis:7.2-bookworm
    container_name: redis_BE-modular-golang
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - be_modular_golang_network
    volumes:
      - redisdata_BE-modular-golang:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  redis-commander_BE-modular-golang:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander_BE-modular-golang
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis_BE-modular-golang:6379
    ports:
      - "8081:8081"
    networks:
      - be_modular_golang_network
    depends_on:
      - redis_BE-modular-golang 

  mongodb_BE-modular-golang:
    image: mongo:6.0
    container_name: mongodb_BE-modular-golang
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      - be_modular_golang_network
    volumes:
      - mongo_data_BE-modular-golang:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "admin", "-u", "admin", "-p", "123", "--eval", "quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  mongo-express_BE-modular-golang:
    image: mongo-express:1.0.2
    container_name: mongo-express_BE-modular-golang
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
      - ME_CONFIG_MONGODB_SERVER=mongodb_BE-modular-golang
      - ME_CONFIG_BASICAUTH_USERNAME=developer
      - ME_CONFIG_BASICAUTH_PASSWORD=devpassword
    ports:
      - "8082:8081"
    networks:
      - be_modular_golang_network
    depends_on:
      - mongodb_BE-modular-golang

  mongo-setup_BE-modular-golang:
    image: mongo:6.0
    container_name: mongo_setup_BE-modular-golang
    networks:
      - be_modular_golang_network
    depends_on:
     - mongodb_BE-modular-golang
      
    # Script: Kết nối vào Mongo, auth bằng admin/123, và khởi tạo Replica Set
    command: >
      bash -c "echo 'Starting Replica Set Init...' && 
      sleep 5 && 
      mongosh --host mongodb_BE-modular-golang --port 27017 -u admin -p 123 --authenticationDatabase admin --eval 'try { rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongodb_BE-modular-golang:27017\"}]}) } catch (e) { print(e) }' && 
      echo 'Replica Set Initialized'"
  Elasticsearch_BE-modular-golang:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch_BE-modular-golang
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 120
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata_BE-modular-golang:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - be_modular_golang_network
  kibana_BE-modular-golang:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana_BE-modular-golang
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://Elasticsearch_BE-modular-golang:9200
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "5601:5601"
    networks:
      - be_modular_golang_network
    depends_on:
      - Elasticsearch_BE-modular-golang
  neo4j_BE-modular-golang:
     image: neo4j:5.11
     container_name: neo4j_BE-modular-golang
     restart: unless-stopped
     environment:
      - NEO4J_AUTH=neo4j/123456789
     volumes:
        - neo4jlogs_BE-modular-golang:/logs
        - neo4jcofig_BE-modular-golang:/config
        - neo4jdata_BE-modular-golang:/data
        - neo4jplugins_BE-modular-golang:/plugins
     ports:
      - "7474:7474"
      - "7687:7687"
     networks:
      - be_modular_golang_network
     healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u $${NEO4J_AUTH%%/*} -p $${NEO4J_AUTH##*/} 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Give Neo4j time to initialize before the first check
  seaweedfs-master_BE-modular-golang:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-master_BE-modular-golang
    restart: unless-stopped
    ports:
      - "9333:9333" # Master HTTP port
      - "19333:19333" # Master gRPC port
    command: ["master", "-ip=seaweedfs-master_BE-modular-golang"]
    volumes:
      - seaweedfs-master-data_BE-modular-golang:/data
    networks:
      - be_modular_golang_network
    healthcheck:
     test: ["CMD", "wget","--spider", "-q", "http://localhost:9333/"]
     interval: 10s
     timeout: 5s
     retries: 3
     start_period: 10s


  seaweedfs-volume_BE-modular-golang:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-volume_BE-modular-golang
    restart: unless-stopped
    ports:
      - "8083:8080" # Volume HTTP port
      - "18080:18080" # Volume gRPC port
    command: ["volume", "-mserver=seaweedfs-master_BE-modular-golang:9333", "-dir=/data", "-ip=seaweedfs-volume_BE-modular-golang"]
    volumes:
      - seaweedfs-volume-data_BE-modular-golang:/data
    networks:
      - be_modular_golang_network
    depends_on:
      - seaweedfs-master_BE-modular-golang
    healthcheck:
      test: ["CMD", "wget","--spider", "-q", "http://localhost:8083/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  seaweedfs-filer_BE-modular-golang:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-filer_BE-modular-golang
    restart: unless-stopped
    ports:
      - "8888:8888" # Filer HTTP port
      - "18888:18888" # Filer gRPC port
    command: ["filer", "-master=seaweedfs-master_BE-modular-golang:9333", "-ip=seaweedfs-filer_BE-modular-golang"]
    volumes:
      - seaweedfs-filer-data_BE-modular-golang:/data
    networks:
      - be_modular_golang_network
    depends_on:
      - seaweedfs-master_BE-modular-golang
      - seaweedfs-volume_BE-modular-golang
    healthcheck:
      test: ["CMD", "wget","--spider", "-q", "http://localhost:8888/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  seaweedfs-s3_BE-modular-golang:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-s3_BE-modular-golang
    restart: unless-stopped
    ports:
      - "8333:8333" # S3 API port
    command: ["s3", "-filer=seaweedfs-filer_BE-modular-golang:8888", "-ip=seaweedfs-s3_BE-modular-golang"]
    networks:
      - be_modular_golang_network
    depends_on:
      - seaweedfs-filer_BE-modular-golang
    healthcheck:
      test: ["CMD", "wget","--spider", "-q", "http://localhost:8333/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  Cassandra_BE-modular-golang:
    image: cassandra:4.1.3
    container_name: my-cassandra-db_cassandra-data_BE-modular-golang
    restart: unless-stopped
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data_BE-modular-golang:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      - be_modular_golang_network
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
  cassandra-init:
    image: cassandra:4.1.3
    container_name: cassandra_init_job
    restart: always
    depends_on:
      - Cassandra_BE-modular-golang
    volumes:
      - ./init/initCassandra.cql:/init.cql # Mount file script vào trong container
    networks:
      - be_modular_golang_network
    # Lệnh thực thi: Dùng cqlsh kết nối vào host 'cassandra' và chạy file init.cql
    command: /bin/bash -c "echo 'Starting init script...' && cqlsh Cassandra_BE-modular-golang -f /init.cql && echo 'Init completed!'"

  keycloak_BE-modular-golang:
    image: quay.io/keycloak/keycloak:22.0.1
   
    container_name: keycloak_BE-modular-golang
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres_db_BE-modular-golang:5432/keycloak
      - KC_DB_USERNAME=user     # Dùng user của service postgres ở trên
      - KC_DB_PASSWORD=123      # Dùng pass của service postgres ở trên
      - KC_HOSTNAME=localhost   # Quan trọng để redirect SSO chạy đúng trên local
    ports:
      - "8085:8080"
    command: start-dev
    depends_on:
      - postgres_db_BE-modular-golang
    networks:
      - be_modular_golang_network
    healthcheck: # Quan trọng: Để Terraform biết khi nào Keycloak sẵn sàng
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080; echo -e 'GET /health/ready HTTP/1.1\r\nHost: health\r\nConnection: close\r\n\r\n' >&3; cat <&3 | grep -q '200 OK'"]
      interval: 10s
      timeout: 5s
      retries: 15
  terraform-init:
    image: hashicorp/terraform:light
    container_name: terraform_init_job
    working_dir: /app
    volumes:
      - ./deployments/init:/app # Mount thư mục chứa file .tf vào
    # Lệnh này sẽ: Init -> Chờ Keycloak khỏe -> Apply config
    entrypoint: ["sh", "-c", "terraform init && echo 'Waiting for Keycloak...' && while ! nc -z keycloak_BE-modular-golang 8080; do sleep 2; done && sleep 10 && terraform apply -auto-approve"]
    depends_on:
      keycloak_BE-modular-golang:
        condition: service_healthy # Chỉ chạy khi Keycloak đã Healthcheck OK
    networks:
      - be_modular_golang_network  
networks:
  be_modular_golang_network:
    driver: bridge

volumes:
  pgdata_BE-modular-golang:
  redisdata_BE-modular-golang:
  mongo_data_BE-modular-golang:
  esdata_BE-modular-golang:
  neo4jlogs_BE-modular-golang:
  neo4jcofig_BE-modular-golang:
  neo4jdata_BE-modular-golang:
  neo4jplugins_BE-modular-golang:
  seaweedfs-master-data_BE-modular-golang:
  seaweedfs-volume-data_BE-modular-golang:
  seaweedfs-filer-data_BE-modular-golang:
  cassandra-data_BE-modular-golang:
  