// Code generated by "enumer -type=MediaType -json -transform=snake -trimprefix=MediaType"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MediaTypeName = "imagevideogif"

var _MediaTypeIndex = [...]uint8{0, 5, 10, 13}

const _MediaTypeLowerName = "imagevideogif"

func (i MediaType) String() string {
	if i < 0 || i >= MediaType(len(_MediaTypeIndex)-1) {
		return fmt.Sprintf("MediaType(%d)", i)
	}
	return _MediaTypeName[_MediaTypeIndex[i]:_MediaTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MediaTypeNoOp() {
	var x [1]struct{}
	_ = x[MediaTypeImage-(0)]
	_ = x[MediaTypeVideo-(1)]
	_ = x[MediaTypeGif-(2)]
}

var _MediaTypeValues = []MediaType{MediaTypeImage, MediaTypeVideo, MediaTypeGif}

var _MediaTypeNameToValueMap = map[string]MediaType{
	_MediaTypeName[0:5]:        MediaTypeImage,
	_MediaTypeLowerName[0:5]:   MediaTypeImage,
	_MediaTypeName[5:10]:       MediaTypeVideo,
	_MediaTypeLowerName[5:10]:  MediaTypeVideo,
	_MediaTypeName[10:13]:      MediaTypeGif,
	_MediaTypeLowerName[10:13]: MediaTypeGif,
}

var _MediaTypeNames = []string{
	_MediaTypeName[0:5],
	_MediaTypeName[5:10],
	_MediaTypeName[10:13],
}

// MediaTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MediaTypeString(s string) (MediaType, error) {
	if val, ok := _MediaTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MediaTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MediaType values", s)
}

// MediaTypeValues returns all values of the enum
func MediaTypeValues() []MediaType {
	return _MediaTypeValues
}

// MediaTypeStrings returns a slice of all String values of the enum
func MediaTypeStrings() []string {
	strs := make([]string, len(_MediaTypeNames))
	copy(strs, _MediaTypeNames)
	return strs
}

// IsAMediaType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MediaType) IsAMediaType() bool {
	for _, v := range _MediaTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MediaType
func (i MediaType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MediaType
func (i *MediaType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MediaType should be a string, got %s", data)
	}

	var err error
	*i, err = MediaTypeString(s)
	return err
}
