// Code generated by "enumer -type=PrivacyScope -json -transform=snake -trimprefix=Scope"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PrivacyScopeName = "publicfriendsonly_mecustom"

var _PrivacyScopeIndex = [...]uint8{0, 6, 13, 20, 26}

const _PrivacyScopeLowerName = "publicfriendsonly_mecustom"

func (i PrivacyScope) String() string {
	if i < 0 || i >= PrivacyScope(len(_PrivacyScopeIndex)-1) {
		return fmt.Sprintf("PrivacyScope(%d)", i)
	}
	return _PrivacyScopeName[_PrivacyScopeIndex[i]:_PrivacyScopeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PrivacyScopeNoOp() {
	var x [1]struct{}
	_ = x[ScopePublic-(0)]
	_ = x[ScopeFriends-(1)]
	_ = x[ScopeOnlyMe-(2)]
	_ = x[ScopeCustom-(3)]
}

var _PrivacyScopeValues = []PrivacyScope{ScopePublic, ScopeFriends, ScopeOnlyMe, ScopeCustom}

var _PrivacyScopeNameToValueMap = map[string]PrivacyScope{
	_PrivacyScopeName[0:6]:        ScopePublic,
	_PrivacyScopeLowerName[0:6]:   ScopePublic,
	_PrivacyScopeName[6:13]:       ScopeFriends,
	_PrivacyScopeLowerName[6:13]:  ScopeFriends,
	_PrivacyScopeName[13:20]:      ScopeOnlyMe,
	_PrivacyScopeLowerName[13:20]: ScopeOnlyMe,
	_PrivacyScopeName[20:26]:      ScopeCustom,
	_PrivacyScopeLowerName[20:26]: ScopeCustom,
}

var _PrivacyScopeNames = []string{
	_PrivacyScopeName[0:6],
	_PrivacyScopeName[6:13],
	_PrivacyScopeName[13:20],
	_PrivacyScopeName[20:26],
}

// PrivacyScopeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PrivacyScopeString(s string) (PrivacyScope, error) {
	if val, ok := _PrivacyScopeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PrivacyScopeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PrivacyScope values", s)
}

// PrivacyScopeValues returns all values of the enum
func PrivacyScopeValues() []PrivacyScope {
	return _PrivacyScopeValues
}

// PrivacyScopeStrings returns a slice of all String values of the enum
func PrivacyScopeStrings() []string {
	strs := make([]string, len(_PrivacyScopeNames))
	copy(strs, _PrivacyScopeNames)
	return strs
}

// IsAPrivacyScope returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PrivacyScope) IsAPrivacyScope() bool {
	for _, v := range _PrivacyScopeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PrivacyScope
func (i PrivacyScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PrivacyScope
func (i *PrivacyScope) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PrivacyScope should be a string, got %s", data)
	}

	var err error
	*i, err = PrivacyScopeString(s)
	return err
}
