// Code generated by "enumer -type=PublisherRole -json -transform=snake -trimprefix=Role"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PublisherRoleName = "admineditormoderatorbot"

var _PublisherRoleIndex = [...]uint8{0, 5, 11, 20, 23}

const _PublisherRoleLowerName = "admineditormoderatorbot"

func (i PublisherRole) String() string {
	if i < 0 || i >= PublisherRole(len(_PublisherRoleIndex)-1) {
		return fmt.Sprintf("PublisherRole(%d)", i)
	}
	return _PublisherRoleName[_PublisherRoleIndex[i]:_PublisherRoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PublisherRoleNoOp() {
	var x [1]struct{}
	_ = x[RoleAdmin-(0)]
	_ = x[RoleEditor-(1)]
	_ = x[RoleModerator-(2)]
	_ = x[RoleBot-(3)]
}

var _PublisherRoleValues = []PublisherRole{RoleAdmin, RoleEditor, RoleModerator, RoleBot}

var _PublisherRoleNameToValueMap = map[string]PublisherRole{
	_PublisherRoleName[0:5]:        RoleAdmin,
	_PublisherRoleLowerName[0:5]:   RoleAdmin,
	_PublisherRoleName[5:11]:       RoleEditor,
	_PublisherRoleLowerName[5:11]:  RoleEditor,
	_PublisherRoleName[11:20]:      RoleModerator,
	_PublisherRoleLowerName[11:20]: RoleModerator,
	_PublisherRoleName[20:23]:      RoleBot,
	_PublisherRoleLowerName[20:23]: RoleBot,
}

var _PublisherRoleNames = []string{
	_PublisherRoleName[0:5],
	_PublisherRoleName[5:11],
	_PublisherRoleName[11:20],
	_PublisherRoleName[20:23],
}

// PublisherRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PublisherRoleString(s string) (PublisherRole, error) {
	if val, ok := _PublisherRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PublisherRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PublisherRole values", s)
}

// PublisherRoleValues returns all values of the enum
func PublisherRoleValues() []PublisherRole {
	return _PublisherRoleValues
}

// PublisherRoleStrings returns a slice of all String values of the enum
func PublisherRoleStrings() []string {
	strs := make([]string, len(_PublisherRoleNames))
	copy(strs, _PublisherRoleNames)
	return strs
}

// IsAPublisherRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PublisherRole) IsAPublisherRole() bool {
	for _, v := range _PublisherRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PublisherRole
func (i PublisherRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PublisherRole
func (i *PublisherRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PublisherRole should be a string, got %s", data)
	}

	var err error
	*i, err = PublisherRoleString(s)
	return err
}
