// Code generated by "enumer -type=TargetCollection -json -transform=snake -trimprefix=Collection"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TargetCollectionName = "postscomments"

var _TargetCollectionIndex = [...]uint8{0, 5, 13}

const _TargetCollectionLowerName = "postscomments"

func (i TargetCollection) String() string {
	if i < 0 || i >= TargetCollection(len(_TargetCollectionIndex)-1) {
		return fmt.Sprintf("TargetCollection(%d)", i)
	}
	return _TargetCollectionName[_TargetCollectionIndex[i]:_TargetCollectionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TargetCollectionNoOp() {
	var x [1]struct{}
	_ = x[CollectionPosts-(0)]
	_ = x[CollectionComments-(1)]
}

var _TargetCollectionValues = []TargetCollection{CollectionPosts, CollectionComments}

var _TargetCollectionNameToValueMap = map[string]TargetCollection{
	_TargetCollectionName[0:5]:       CollectionPosts,
	_TargetCollectionLowerName[0:5]:  CollectionPosts,
	_TargetCollectionName[5:13]:      CollectionComments,
	_TargetCollectionLowerName[5:13]: CollectionComments,
}

var _TargetCollectionNames = []string{
	_TargetCollectionName[0:5],
	_TargetCollectionName[5:13],
}

// TargetCollectionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TargetCollectionString(s string) (TargetCollection, error) {
	if val, ok := _TargetCollectionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TargetCollectionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TargetCollection values", s)
}

// TargetCollectionValues returns all values of the enum
func TargetCollectionValues() []TargetCollection {
	return _TargetCollectionValues
}

// TargetCollectionStrings returns a slice of all String values of the enum
func TargetCollectionStrings() []string {
	strs := make([]string, len(_TargetCollectionNames))
	copy(strs, _TargetCollectionNames)
	return strs
}

// IsATargetCollection returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TargetCollection) IsATargetCollection() bool {
	for _, v := range _TargetCollectionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TargetCollection
func (i TargetCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TargetCollection
func (i *TargetCollection) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TargetCollection should be a string, got %s", data)
	}

	var err error
	*i, err = TargetCollectionString(s)
	return err
}
