// Code generated by "enumer -type=FontSize -json -transform=snake -trimprefix=Font"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _FontSizeName = "mediumlarge"

var _FontSizeIndex = [...]uint8{0, 6, 11}

const _FontSizeLowerName = "mediumlarge"

func (i FontSize) String() string {
	if i < 0 || i >= FontSize(len(_FontSizeIndex)-1) {
		return fmt.Sprintf("FontSize(%d)", i)
	}
	return _FontSizeName[_FontSizeIndex[i]:_FontSizeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FontSizeNoOp() {
	var x [1]struct{}
	_ = x[FontMedium-(0)]
	_ = x[FontLarge-(1)]
}

var _FontSizeValues = []FontSize{FontMedium, FontLarge}

var _FontSizeNameToValueMap = map[string]FontSize{
	_FontSizeName[0:6]:       FontMedium,
	_FontSizeLowerName[0:6]:  FontMedium,
	_FontSizeName[6:11]:      FontLarge,
	_FontSizeLowerName[6:11]: FontLarge,
}

var _FontSizeNames = []string{
	_FontSizeName[0:6],
	_FontSizeName[6:11],
}

// FontSizeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FontSizeString(s string) (FontSize, error) {
	if val, ok := _FontSizeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FontSizeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FontSize values", s)
}

// FontSizeValues returns all values of the enum
func FontSizeValues() []FontSize {
	return _FontSizeValues
}

// FontSizeStrings returns a slice of all String values of the enum
func FontSizeStrings() []string {
	strs := make([]string, len(_FontSizeNames))
	copy(strs, _FontSizeNames)
	return strs
}

// IsAFontSize returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FontSize) IsAFontSize() bool {
	for _, v := range _FontSizeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FontSize
func (i FontSize) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FontSize
func (i *FontSize) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FontSize should be a string, got %s", data)
	}

	var err error
	*i, err = FontSizeString(s)
	return err
}
