// Code generated by "enumer -type=LangCode -json -transform=snake -trimprefix=Lang"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _LangCodeName = "vienjp"

var _LangCodeIndex = [...]uint8{0, 2, 4, 6}

const _LangCodeLowerName = "vienjp"

func (i LangCode) String() string {
	if i < 0 || i >= LangCode(len(_LangCodeIndex)-1) {
		return fmt.Sprintf("LangCode(%d)", i)
	}
	return _LangCodeName[_LangCodeIndex[i]:_LangCodeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LangCodeNoOp() {
	var x [1]struct{}
	_ = x[LangVi-(0)]
	_ = x[LangEn-(1)]
	_ = x[LangJp-(2)]
}

var _LangCodeValues = []LangCode{LangVi, LangEn, LangJp}

var _LangCodeNameToValueMap = map[string]LangCode{
	_LangCodeName[0:2]:      LangVi,
	_LangCodeLowerName[0:2]: LangVi,
	_LangCodeName[2:4]:      LangEn,
	_LangCodeLowerName[2:4]: LangEn,
	_LangCodeName[4:6]:      LangJp,
	_LangCodeLowerName[4:6]: LangJp,
}

var _LangCodeNames = []string{
	_LangCodeName[0:2],
	_LangCodeName[2:4],
	_LangCodeName[4:6],
}

// LangCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LangCodeString(s string) (LangCode, error) {
	if val, ok := _LangCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LangCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LangCode values", s)
}

// LangCodeValues returns all values of the enum
func LangCodeValues() []LangCode {
	return _LangCodeValues
}

// LangCodeStrings returns a slice of all String values of the enum
func LangCodeStrings() []string {
	strs := make([]string, len(_LangCodeNames))
	copy(strs, _LangCodeNames)
	return strs
}

// IsALangCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LangCode) IsALangCode() bool {
	for _, v := range _LangCodeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for LangCode
func (i LangCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for LangCode
func (i *LangCode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LangCode should be a string, got %s", data)
	}

	var err error
	*i, err = LangCodeString(s)
	return err
}
