// Code generated by "enumer -type=LoginType -json -sql -transform=snake -trimprefix=LoginType"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _LoginTypeName = "emailgooglefacebookapple"

var _LoginTypeIndex = [...]uint8{0, 5, 11, 19, 24}

const _LoginTypeLowerName = "emailgooglefacebookapple"

func (i LoginType) String() string {
	if i < 0 || i >= LoginType(len(_LoginTypeIndex)-1) {
		return fmt.Sprintf("LoginType(%d)", i)
	}
	return _LoginTypeName[_LoginTypeIndex[i]:_LoginTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LoginTypeNoOp() {
	var x [1]struct{}
	_ = x[LoginTypeEmail-(0)]
	_ = x[LoginTypeGoogle-(1)]
	_ = x[LoginTypeFacebook-(2)]
	_ = x[LoginTypeApple-(3)]
}

var _LoginTypeValues = []LoginType{LoginTypeEmail, LoginTypeGoogle, LoginTypeFacebook, LoginTypeApple}

var _LoginTypeNameToValueMap = map[string]LoginType{
	_LoginTypeName[0:5]:        LoginTypeEmail,
	_LoginTypeLowerName[0:5]:   LoginTypeEmail,
	_LoginTypeName[5:11]:       LoginTypeGoogle,
	_LoginTypeLowerName[5:11]:  LoginTypeGoogle,
	_LoginTypeName[11:19]:      LoginTypeFacebook,
	_LoginTypeLowerName[11:19]: LoginTypeFacebook,
	_LoginTypeName[19:24]:      LoginTypeApple,
	_LoginTypeLowerName[19:24]: LoginTypeApple,
}

var _LoginTypeNames = []string{
	_LoginTypeName[0:5],
	_LoginTypeName[5:11],
	_LoginTypeName[11:19],
	_LoginTypeName[19:24],
}

// LoginTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LoginTypeString(s string) (LoginType, error) {
	if val, ok := _LoginTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LoginTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LoginType values", s)
}

// LoginTypeValues returns all values of the enum
func LoginTypeValues() []LoginType {
	return _LoginTypeValues
}

// LoginTypeStrings returns a slice of all String values of the enum
func LoginTypeStrings() []string {
	strs := make([]string, len(_LoginTypeNames))
	copy(strs, _LoginTypeNames)
	return strs
}

// IsALoginType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LoginType) IsALoginType() bool {
	for _, v := range _LoginTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for LoginType
func (i LoginType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for LoginType
func (i *LoginType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LoginType should be a string, got %s", data)
	}

	var err error
	*i, err = LoginTypeString(s)
	return err
}

func (i LoginType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *LoginType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of LoginType: %[1]T(%[1]v)", value)
	}

	val, err := LoginTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
