// Code generated by "enumer -type=PrivacyLevel -json -transform=snake -trimprefix=Privacy"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PrivacyLevelName = "publicfriendsclose_friendsonly_mefriends_of_friendseveryone"

var _PrivacyLevelIndex = [...]uint8{0, 6, 13, 26, 33, 51, 59}

const _PrivacyLevelLowerName = "publicfriendsclose_friendsonly_mefriends_of_friendseveryone"

func (i PrivacyLevel) String() string {
	if i < 0 || i >= PrivacyLevel(len(_PrivacyLevelIndex)-1) {
		return fmt.Sprintf("PrivacyLevel(%d)", i)
	}
	return _PrivacyLevelName[_PrivacyLevelIndex[i]:_PrivacyLevelIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PrivacyLevelNoOp() {
	var x [1]struct{}
	_ = x[PrivacyPublic-(0)]
	_ = x[PrivacyFriends-(1)]
	_ = x[PrivacyCloseFriends-(2)]
	_ = x[PrivacyOnlyMe-(3)]
	_ = x[PrivacyFriendsOfFriends-(4)]
	_ = x[PrivacyEveryone-(5)]
}

var _PrivacyLevelValues = []PrivacyLevel{PrivacyPublic, PrivacyFriends, PrivacyCloseFriends, PrivacyOnlyMe, PrivacyFriendsOfFriends, PrivacyEveryone}

var _PrivacyLevelNameToValueMap = map[string]PrivacyLevel{
	_PrivacyLevelName[0:6]:        PrivacyPublic,
	_PrivacyLevelLowerName[0:6]:   PrivacyPublic,
	_PrivacyLevelName[6:13]:       PrivacyFriends,
	_PrivacyLevelLowerName[6:13]:  PrivacyFriends,
	_PrivacyLevelName[13:26]:      PrivacyCloseFriends,
	_PrivacyLevelLowerName[13:26]: PrivacyCloseFriends,
	_PrivacyLevelName[26:33]:      PrivacyOnlyMe,
	_PrivacyLevelLowerName[26:33]: PrivacyOnlyMe,
	_PrivacyLevelName[33:51]:      PrivacyFriendsOfFriends,
	_PrivacyLevelLowerName[33:51]: PrivacyFriendsOfFriends,
	_PrivacyLevelName[51:59]:      PrivacyEveryone,
	_PrivacyLevelLowerName[51:59]: PrivacyEveryone,
}

var _PrivacyLevelNames = []string{
	_PrivacyLevelName[0:6],
	_PrivacyLevelName[6:13],
	_PrivacyLevelName[13:26],
	_PrivacyLevelName[26:33],
	_PrivacyLevelName[33:51],
	_PrivacyLevelName[51:59],
}

// PrivacyLevelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PrivacyLevelString(s string) (PrivacyLevel, error) {
	if val, ok := _PrivacyLevelNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PrivacyLevelNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PrivacyLevel values", s)
}

// PrivacyLevelValues returns all values of the enum
func PrivacyLevelValues() []PrivacyLevel {
	return _PrivacyLevelValues
}

// PrivacyLevelStrings returns a slice of all String values of the enum
func PrivacyLevelStrings() []string {
	strs := make([]string, len(_PrivacyLevelNames))
	copy(strs, _PrivacyLevelNames)
	return strs
}

// IsAPrivacyLevel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PrivacyLevel) IsAPrivacyLevel() bool {
	for _, v := range _PrivacyLevelValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PrivacyLevel
func (i PrivacyLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PrivacyLevel
func (i *PrivacyLevel) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PrivacyLevel should be a string, got %s", data)
	}

	var err error
	*i, err = PrivacyLevelString(s)
	return err
}
