// Code generated by "enumer -type=ThemeMode -json -transform=snake -trimprefix=Theme"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ThemeModeName = "systemlightdarkhigh_contrast"

var _ThemeModeIndex = [...]uint8{0, 6, 11, 15, 28}

const _ThemeModeLowerName = "systemlightdarkhigh_contrast"

func (i ThemeMode) String() string {
	if i < 0 || i >= ThemeMode(len(_ThemeModeIndex)-1) {
		return fmt.Sprintf("ThemeMode(%d)", i)
	}
	return _ThemeModeName[_ThemeModeIndex[i]:_ThemeModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ThemeModeNoOp() {
	var x [1]struct{}
	_ = x[ThemeSystem-(0)]
	_ = x[ThemeLight-(1)]
	_ = x[ThemeDark-(2)]
	_ = x[ThemeHighContrast-(3)]
}

var _ThemeModeValues = []ThemeMode{ThemeSystem, ThemeLight, ThemeDark, ThemeHighContrast}

var _ThemeModeNameToValueMap = map[string]ThemeMode{
	_ThemeModeName[0:6]:        ThemeSystem,
	_ThemeModeLowerName[0:6]:   ThemeSystem,
	_ThemeModeName[6:11]:       ThemeLight,
	_ThemeModeLowerName[6:11]:  ThemeLight,
	_ThemeModeName[11:15]:      ThemeDark,
	_ThemeModeLowerName[11:15]: ThemeDark,
	_ThemeModeName[15:28]:      ThemeHighContrast,
	_ThemeModeLowerName[15:28]: ThemeHighContrast,
}

var _ThemeModeNames = []string{
	_ThemeModeName[0:6],
	_ThemeModeName[6:11],
	_ThemeModeName[11:15],
	_ThemeModeName[15:28],
}

// ThemeModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ThemeModeString(s string) (ThemeMode, error) {
	if val, ok := _ThemeModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ThemeModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ThemeMode values", s)
}

// ThemeModeValues returns all values of the enum
func ThemeModeValues() []ThemeMode {
	return _ThemeModeValues
}

// ThemeModeStrings returns a slice of all String values of the enum
func ThemeModeStrings() []string {
	strs := make([]string, len(_ThemeModeNames))
	copy(strs, _ThemeModeNames)
	return strs
}

// IsAThemeMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ThemeMode) IsAThemeMode() bool {
	for _, v := range _ThemeModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ThemeMode
func (i ThemeMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ThemeMode
func (i *ThemeMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ThemeMode should be a string, got %s", data)
	}

	var err error
	*i, err = ThemeModeString(s)
	return err
}
