// Code generated by "enumer -type=Timezone -json -trimprefix=Timezone"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TimezoneName = "HCMNYLDN"

var _TimezoneIndex = [...]uint8{0, 3, 5, 8}

const _TimezoneLowerName = "hcmnyldn"

func (i Timezone) String() string {
	if i < 0 || i >= Timezone(len(_TimezoneIndex)-1) {
		return fmt.Sprintf("Timezone(%d)", i)
	}
	return _TimezoneName[_TimezoneIndex[i]:_TimezoneIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TimezoneNoOp() {
	var x [1]struct{}
	_ = x[TimezoneHCM-(0)]
	_ = x[TimezoneNY-(1)]
	_ = x[TimezoneLDN-(2)]
}

var _TimezoneValues = []Timezone{TimezoneHCM, TimezoneNY, TimezoneLDN}

var _TimezoneNameToValueMap = map[string]Timezone{
	_TimezoneName[0:3]:      TimezoneHCM,
	_TimezoneLowerName[0:3]: TimezoneHCM,
	_TimezoneName[3:5]:      TimezoneNY,
	_TimezoneLowerName[3:5]: TimezoneNY,
	_TimezoneName[5:8]:      TimezoneLDN,
	_TimezoneLowerName[5:8]: TimezoneLDN,
}

var _TimezoneNames = []string{
	_TimezoneName[0:3],
	_TimezoneName[3:5],
	_TimezoneName[5:8],
}

// TimezoneString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TimezoneString(s string) (Timezone, error) {
	if val, ok := _TimezoneNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TimezoneNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Timezone values", s)
}

// TimezoneValues returns all values of the enum
func TimezoneValues() []Timezone {
	return _TimezoneValues
}

// TimezoneStrings returns a slice of all String values of the enum
func TimezoneStrings() []string {
	strs := make([]string, len(_TimezoneNames))
	copy(strs, _TimezoneNames)
	return strs
}

// IsATimezone returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Timezone) IsATimezone() bool {
	for _, v := range _TimezoneValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Timezone
func (i Timezone) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Timezone
func (i *Timezone) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Timezone should be a string, got %s", data)
	}

	var err error
	*i, err = TimezoneString(s)
	return err
}
