// Code generated by "enumer -type=EmailFrequency -json -transform=snake -trimprefix=EmailFreq"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _EmailFrequencyName = "instantdailyweeklynever"

var _EmailFrequencyIndex = [...]uint8{0, 7, 12, 18, 23}

const _EmailFrequencyLowerName = "instantdailyweeklynever"

func (i EmailFrequency) String() string {
	if i < 0 || i >= EmailFrequency(len(_EmailFrequencyIndex)-1) {
		return fmt.Sprintf("EmailFrequency(%d)", i)
	}
	return _EmailFrequencyName[_EmailFrequencyIndex[i]:_EmailFrequencyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EmailFrequencyNoOp() {
	var x [1]struct{}
	_ = x[EmailFreqInstant-(0)]
	_ = x[EmailFreqDaily-(1)]
	_ = x[EmailFreqWeekly-(2)]
	_ = x[EmailFreqNever-(3)]
}

var _EmailFrequencyValues = []EmailFrequency{EmailFreqInstant, EmailFreqDaily, EmailFreqWeekly, EmailFreqNever}

var _EmailFrequencyNameToValueMap = map[string]EmailFrequency{
	_EmailFrequencyName[0:7]:        EmailFreqInstant,
	_EmailFrequencyLowerName[0:7]:   EmailFreqInstant,
	_EmailFrequencyName[7:12]:       EmailFreqDaily,
	_EmailFrequencyLowerName[7:12]:  EmailFreqDaily,
	_EmailFrequencyName[12:18]:      EmailFreqWeekly,
	_EmailFrequencyLowerName[12:18]: EmailFreqWeekly,
	_EmailFrequencyName[18:23]:      EmailFreqNever,
	_EmailFrequencyLowerName[18:23]: EmailFreqNever,
}

var _EmailFrequencyNames = []string{
	_EmailFrequencyName[0:7],
	_EmailFrequencyName[7:12],
	_EmailFrequencyName[12:18],
	_EmailFrequencyName[18:23],
}

// EmailFrequencyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EmailFrequencyString(s string) (EmailFrequency, error) {
	if val, ok := _EmailFrequencyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EmailFrequencyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EmailFrequency values", s)
}

// EmailFrequencyValues returns all values of the enum
func EmailFrequencyValues() []EmailFrequency {
	return _EmailFrequencyValues
}

// EmailFrequencyStrings returns a slice of all String values of the enum
func EmailFrequencyStrings() []string {
	strs := make([]string, len(_EmailFrequencyNames))
	copy(strs, _EmailFrequencyNames)
	return strs
}

// IsAEmailFrequency returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EmailFrequency) IsAEmailFrequency() bool {
	for _, v := range _EmailFrequencyValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EmailFrequency
func (i EmailFrequency) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EmailFrequency
func (i *EmailFrequency) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EmailFrequency should be a string, got %s", data)
	}

	var err error
	*i, err = EmailFrequencyString(s)
	return err
}
