// Code generated by "enumer -type=NotificationType -json -transform=snake -trimprefix=Notif"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _NotificationTypeName = "post_likecomment_replyfriend_requestfriend_acceptgroup_invitesystem_alertmention"

var _NotificationTypeIndex = [...]uint8{0, 9, 22, 36, 49, 61, 73, 80}

const _NotificationTypeLowerName = "post_likecomment_replyfriend_requestfriend_acceptgroup_invitesystem_alertmention"

func (i NotificationType) String() string {
	if i < 0 || i >= NotificationType(len(_NotificationTypeIndex)-1) {
		return fmt.Sprintf("NotificationType(%d)", i)
	}
	return _NotificationTypeName[_NotificationTypeIndex[i]:_NotificationTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _NotificationTypeNoOp() {
	var x [1]struct{}
	_ = x[NotifPostLike-(0)]
	_ = x[NotifCommentReply-(1)]
	_ = x[NotifFriendRequest-(2)]
	_ = x[NotifFriendAccept-(3)]
	_ = x[NotifGroupInvite-(4)]
	_ = x[NotifSystemAlert-(5)]
	_ = x[NotifMention-(6)]
}

var _NotificationTypeValues = []NotificationType{NotifPostLike, NotifCommentReply, NotifFriendRequest, NotifFriendAccept, NotifGroupInvite, NotifSystemAlert, NotifMention}

var _NotificationTypeNameToValueMap = map[string]NotificationType{
	_NotificationTypeName[0:9]:        NotifPostLike,
	_NotificationTypeLowerName[0:9]:   NotifPostLike,
	_NotificationTypeName[9:22]:       NotifCommentReply,
	_NotificationTypeLowerName[9:22]:  NotifCommentReply,
	_NotificationTypeName[22:36]:      NotifFriendRequest,
	_NotificationTypeLowerName[22:36]: NotifFriendRequest,
	_NotificationTypeName[36:49]:      NotifFriendAccept,
	_NotificationTypeLowerName[36:49]: NotifFriendAccept,
	_NotificationTypeName[49:61]:      NotifGroupInvite,
	_NotificationTypeLowerName[49:61]: NotifGroupInvite,
	_NotificationTypeName[61:73]:      NotifSystemAlert,
	_NotificationTypeLowerName[61:73]: NotifSystemAlert,
	_NotificationTypeName[73:80]:      NotifMention,
	_NotificationTypeLowerName[73:80]: NotifMention,
}

var _NotificationTypeNames = []string{
	_NotificationTypeName[0:9],
	_NotificationTypeName[9:22],
	_NotificationTypeName[22:36],
	_NotificationTypeName[36:49],
	_NotificationTypeName[49:61],
	_NotificationTypeName[61:73],
	_NotificationTypeName[73:80],
}

// NotificationTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func NotificationTypeString(s string) (NotificationType, error) {
	if val, ok := _NotificationTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _NotificationTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to NotificationType values", s)
}

// NotificationTypeValues returns all values of the enum
func NotificationTypeValues() []NotificationType {
	return _NotificationTypeValues
}

// NotificationTypeStrings returns a slice of all String values of the enum
func NotificationTypeStrings() []string {
	strs := make([]string, len(_NotificationTypeNames))
	copy(strs, _NotificationTypeNames)
	return strs
}

// IsANotificationType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i NotificationType) IsANotificationType() bool {
	for _, v := range _NotificationTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for NotificationType
func (i NotificationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for NotificationType
func (i *NotificationType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("NotificationType should be a string, got %s", data)
	}

	var err error
	*i, err = NotificationTypeString(s)
	return err
}
