// Code generated by "enumer -type=AlbumType -json -transform=snake -trimprefix=AlbumType"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AlbumTypeName = "normalprofilecovermobiletrash"

var _AlbumTypeIndex = [...]uint8{0, 6, 13, 18, 24, 29}

const _AlbumTypeLowerName = "normalprofilecovermobiletrash"

func (i AlbumType) String() string {
	if i < 0 || i >= AlbumType(len(_AlbumTypeIndex)-1) {
		return fmt.Sprintf("AlbumType(%d)", i)
	}
	return _AlbumTypeName[_AlbumTypeIndex[i]:_AlbumTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AlbumTypeNoOp() {
	var x [1]struct{}
	_ = x[AlbumTypeNormal-(0)]
	_ = x[AlbumTypeProfile-(1)]
	_ = x[AlbumTypeCover-(2)]
	_ = x[AlbumTypeMobile-(3)]
	_ = x[AlbumTypeTrash-(4)]
}

var _AlbumTypeValues = []AlbumType{AlbumTypeNormal, AlbumTypeProfile, AlbumTypeCover, AlbumTypeMobile, AlbumTypeTrash}

var _AlbumTypeNameToValueMap = map[string]AlbumType{
	_AlbumTypeName[0:6]:        AlbumTypeNormal,
	_AlbumTypeLowerName[0:6]:   AlbumTypeNormal,
	_AlbumTypeName[6:13]:       AlbumTypeProfile,
	_AlbumTypeLowerName[6:13]:  AlbumTypeProfile,
	_AlbumTypeName[13:18]:      AlbumTypeCover,
	_AlbumTypeLowerName[13:18]: AlbumTypeCover,
	_AlbumTypeName[18:24]:      AlbumTypeMobile,
	_AlbumTypeLowerName[18:24]: AlbumTypeMobile,
	_AlbumTypeName[24:29]:      AlbumTypeTrash,
	_AlbumTypeLowerName[24:29]: AlbumTypeTrash,
}

var _AlbumTypeNames = []string{
	_AlbumTypeName[0:6],
	_AlbumTypeName[6:13],
	_AlbumTypeName[13:18],
	_AlbumTypeName[18:24],
	_AlbumTypeName[24:29],
}

// AlbumTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AlbumTypeString(s string) (AlbumType, error) {
	if val, ok := _AlbumTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AlbumTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AlbumType values", s)
}

// AlbumTypeValues returns all values of the enum
func AlbumTypeValues() []AlbumType {
	return _AlbumTypeValues
}

// AlbumTypeStrings returns a slice of all String values of the enum
func AlbumTypeStrings() []string {
	strs := make([]string, len(_AlbumTypeNames))
	copy(strs, _AlbumTypeNames)
	return strs
}

// IsAAlbumType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AlbumType) IsAAlbumType() bool {
	for _, v := range _AlbumTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AlbumType
func (i AlbumType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AlbumType
func (i *AlbumType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AlbumType should be a string, got %s", data)
	}

	var err error
	*i, err = AlbumTypeString(s)
	return err
}
