// Code generated by "enumer -type=AssetType -json -transform=snake -trimprefix=Asset"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AssetTypeName = "imagevideogifsticker"

var _AssetTypeIndex = [...]uint8{0, 5, 10, 13, 20}

const _AssetTypeLowerName = "imagevideogifsticker"

func (i AssetType) String() string {
	if i < 0 || i >= AssetType(len(_AssetTypeIndex)-1) {
		return fmt.Sprintf("AssetType(%d)", i)
	}
	return _AssetTypeName[_AssetTypeIndex[i]:_AssetTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AssetTypeNoOp() {
	var x [1]struct{}
	_ = x[AssetImage-(0)]
	_ = x[AssetVideo-(1)]
	_ = x[AssetGif-(2)]
	_ = x[AssetSticker-(3)]
}

var _AssetTypeValues = []AssetType{AssetImage, AssetVideo, AssetGif, AssetSticker}

var _AssetTypeNameToValueMap = map[string]AssetType{
	_AssetTypeName[0:5]:        AssetImage,
	_AssetTypeLowerName[0:5]:   AssetImage,
	_AssetTypeName[5:10]:       AssetVideo,
	_AssetTypeLowerName[5:10]:  AssetVideo,
	_AssetTypeName[10:13]:      AssetGif,
	_AssetTypeLowerName[10:13]: AssetGif,
	_AssetTypeName[13:20]:      AssetSticker,
	_AssetTypeLowerName[13:20]: AssetSticker,
}

var _AssetTypeNames = []string{
	_AssetTypeName[0:5],
	_AssetTypeName[5:10],
	_AssetTypeName[10:13],
	_AssetTypeName[13:20],
}

// AssetTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AssetTypeString(s string) (AssetType, error) {
	if val, ok := _AssetTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AssetTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AssetType values", s)
}

// AssetTypeValues returns all values of the enum
func AssetTypeValues() []AssetType {
	return _AssetTypeValues
}

// AssetTypeStrings returns a slice of all String values of the enum
func AssetTypeStrings() []string {
	strs := make([]string, len(_AssetTypeNames))
	copy(strs, _AssetTypeNames)
	return strs
}

// IsAAssetType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AssetType) IsAAssetType() bool {
	for _, v := range _AssetTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AssetType
func (i AssetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AssetType
func (i *AssetType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AssetType should be a string, got %s", data)
	}

	var err error
	*i, err = AssetTypeString(s)
	return err
}
