// Code generated by "enumer -type=LiveStatus -json -transform=snake -trimprefix=LiveStatus"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _LiveStatusName = "pendingstreamingendedbanned"

var _LiveStatusIndex = [...]uint8{0, 7, 16, 21, 27}

const _LiveStatusLowerName = "pendingstreamingendedbanned"

func (i LiveStatus) String() string {
	if i < 0 || i >= LiveStatus(len(_LiveStatusIndex)-1) {
		return fmt.Sprintf("LiveStatus(%d)", i)
	}
	return _LiveStatusName[_LiveStatusIndex[i]:_LiveStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LiveStatusNoOp() {
	var x [1]struct{}
	_ = x[LiveStatusPending-(0)]
	_ = x[LiveStatusStreaming-(1)]
	_ = x[LiveStatusEnded-(2)]
	_ = x[LiveStatusBanned-(3)]
}

var _LiveStatusValues = []LiveStatus{LiveStatusPending, LiveStatusStreaming, LiveStatusEnded, LiveStatusBanned}

var _LiveStatusNameToValueMap = map[string]LiveStatus{
	_LiveStatusName[0:7]:        LiveStatusPending,
	_LiveStatusLowerName[0:7]:   LiveStatusPending,
	_LiveStatusName[7:16]:       LiveStatusStreaming,
	_LiveStatusLowerName[7:16]:  LiveStatusStreaming,
	_LiveStatusName[16:21]:      LiveStatusEnded,
	_LiveStatusLowerName[16:21]: LiveStatusEnded,
	_LiveStatusName[21:27]:      LiveStatusBanned,
	_LiveStatusLowerName[21:27]: LiveStatusBanned,
}

var _LiveStatusNames = []string{
	_LiveStatusName[0:7],
	_LiveStatusName[7:16],
	_LiveStatusName[16:21],
	_LiveStatusName[21:27],
}

// LiveStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LiveStatusString(s string) (LiveStatus, error) {
	if val, ok := _LiveStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LiveStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LiveStatus values", s)
}

// LiveStatusValues returns all values of the enum
func LiveStatusValues() []LiveStatus {
	return _LiveStatusValues
}

// LiveStatusStrings returns a slice of all String values of the enum
func LiveStatusStrings() []string {
	strs := make([]string, len(_LiveStatusNames))
	copy(strs, _LiveStatusNames)
	return strs
}

// IsALiveStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LiveStatus) IsALiveStatus() bool {
	for _, v := range _LiveStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for LiveStatus
func (i LiveStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for LiveStatus
func (i *LiveStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LiveStatus should be a string, got %s", data)
	}

	var err error
	*i, err = LiveStatusString(s)
	return err
}
