// Code generated by "enumer -type=MusicGenre -json -transform=snake -trimprefix=Genre"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MusicGenreName = "poprockhip_hoprnbedmballadcountryjazzindiek_popv_popsoundtrack"

var _MusicGenreIndex = [...]uint8{0, 3, 7, 14, 17, 20, 26, 33, 37, 42, 47, 52, 62}

const _MusicGenreLowerName = "poprockhip_hoprnbedmballadcountryjazzindiek_popv_popsoundtrack"

func (i MusicGenre) String() string {
	if i < 0 || i >= MusicGenre(len(_MusicGenreIndex)-1) {
		return fmt.Sprintf("MusicGenre(%d)", i)
	}
	return _MusicGenreName[_MusicGenreIndex[i]:_MusicGenreIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MusicGenreNoOp() {
	var x [1]struct{}
	_ = x[GenrePop-(0)]
	_ = x[GenreRock-(1)]
	_ = x[GenreHipHop-(2)]
	_ = x[GenreRNB-(3)]
	_ = x[GenreEDM-(4)]
	_ = x[GenreBallad-(5)]
	_ = x[GenreCountry-(6)]
	_ = x[GenreJazz-(7)]
	_ = x[GenreIndie-(8)]
	_ = x[GenreKPop-(9)]
	_ = x[GenreVPop-(10)]
	_ = x[GenreSoundtrack-(11)]
}

var _MusicGenreValues = []MusicGenre{GenrePop, GenreRock, GenreHipHop, GenreRNB, GenreEDM, GenreBallad, GenreCountry, GenreJazz, GenreIndie, GenreKPop, GenreVPop, GenreSoundtrack}

var _MusicGenreNameToValueMap = map[string]MusicGenre{
	_MusicGenreName[0:3]:        GenrePop,
	_MusicGenreLowerName[0:3]:   GenrePop,
	_MusicGenreName[3:7]:        GenreRock,
	_MusicGenreLowerName[3:7]:   GenreRock,
	_MusicGenreName[7:14]:       GenreHipHop,
	_MusicGenreLowerName[7:14]:  GenreHipHop,
	_MusicGenreName[14:17]:      GenreRNB,
	_MusicGenreLowerName[14:17]: GenreRNB,
	_MusicGenreName[17:20]:      GenreEDM,
	_MusicGenreLowerName[17:20]: GenreEDM,
	_MusicGenreName[20:26]:      GenreBallad,
	_MusicGenreLowerName[20:26]: GenreBallad,
	_MusicGenreName[26:33]:      GenreCountry,
	_MusicGenreLowerName[26:33]: GenreCountry,
	_MusicGenreName[33:37]:      GenreJazz,
	_MusicGenreLowerName[33:37]: GenreJazz,
	_MusicGenreName[37:42]:      GenreIndie,
	_MusicGenreLowerName[37:42]: GenreIndie,
	_MusicGenreName[42:47]:      GenreKPop,
	_MusicGenreLowerName[42:47]: GenreKPop,
	_MusicGenreName[47:52]:      GenreVPop,
	_MusicGenreLowerName[47:52]: GenreVPop,
	_MusicGenreName[52:62]:      GenreSoundtrack,
	_MusicGenreLowerName[52:62]: GenreSoundtrack,
}

var _MusicGenreNames = []string{
	_MusicGenreName[0:3],
	_MusicGenreName[3:7],
	_MusicGenreName[7:14],
	_MusicGenreName[14:17],
	_MusicGenreName[17:20],
	_MusicGenreName[20:26],
	_MusicGenreName[26:33],
	_MusicGenreName[33:37],
	_MusicGenreName[37:42],
	_MusicGenreName[42:47],
	_MusicGenreName[47:52],
	_MusicGenreName[52:62],
}

// MusicGenreString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MusicGenreString(s string) (MusicGenre, error) {
	if val, ok := _MusicGenreNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MusicGenreNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MusicGenre values", s)
}

// MusicGenreValues returns all values of the enum
func MusicGenreValues() []MusicGenre {
	return _MusicGenreValues
}

// MusicGenreStrings returns a slice of all String values of the enum
func MusicGenreStrings() []string {
	strs := make([]string, len(_MusicGenreNames))
	copy(strs, _MusicGenreNames)
	return strs
}

// IsAMusicGenre returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MusicGenre) IsAMusicGenre() bool {
	for _, v := range _MusicGenreValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MusicGenre
func (i MusicGenre) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MusicGenre
func (i *MusicGenre) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MusicGenre should be a string, got %s", data)
	}

	var err error
	*i, err = MusicGenreString(s)
	return err
}
