// Code generated by "enumer -type=OverlayType -json -transform=snake -trimprefix=Overlay"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _OverlayTypeName = "textmusicmentionlocationpollquestion"

var _OverlayTypeIndex = [...]uint8{0, 4, 9, 16, 24, 28, 36}

const _OverlayTypeLowerName = "textmusicmentionlocationpollquestion"

func (i OverlayType) String() string {
	if i < 0 || i >= OverlayType(len(_OverlayTypeIndex)-1) {
		return fmt.Sprintf("OverlayType(%d)", i)
	}
	return _OverlayTypeName[_OverlayTypeIndex[i]:_OverlayTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OverlayTypeNoOp() {
	var x [1]struct{}
	_ = x[OverlayText-(0)]
	_ = x[OverlayMusic-(1)]
	_ = x[OverlayMention-(2)]
	_ = x[OverlayLocation-(3)]
	_ = x[OverlayPoll-(4)]
	_ = x[OverlayQuestion-(5)]
}

var _OverlayTypeValues = []OverlayType{OverlayText, OverlayMusic, OverlayMention, OverlayLocation, OverlayPoll, OverlayQuestion}

var _OverlayTypeNameToValueMap = map[string]OverlayType{
	_OverlayTypeName[0:4]:        OverlayText,
	_OverlayTypeLowerName[0:4]:   OverlayText,
	_OverlayTypeName[4:9]:        OverlayMusic,
	_OverlayTypeLowerName[4:9]:   OverlayMusic,
	_OverlayTypeName[9:16]:       OverlayMention,
	_OverlayTypeLowerName[9:16]:  OverlayMention,
	_OverlayTypeName[16:24]:      OverlayLocation,
	_OverlayTypeLowerName[16:24]: OverlayLocation,
	_OverlayTypeName[24:28]:      OverlayPoll,
	_OverlayTypeLowerName[24:28]: OverlayPoll,
	_OverlayTypeName[28:36]:      OverlayQuestion,
	_OverlayTypeLowerName[28:36]: OverlayQuestion,
}

var _OverlayTypeNames = []string{
	_OverlayTypeName[0:4],
	_OverlayTypeName[4:9],
	_OverlayTypeName[9:16],
	_OverlayTypeName[16:24],
	_OverlayTypeName[24:28],
	_OverlayTypeName[28:36],
}

// OverlayTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OverlayTypeString(s string) (OverlayType, error) {
	if val, ok := _OverlayTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OverlayTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OverlayType values", s)
}

// OverlayTypeValues returns all values of the enum
func OverlayTypeValues() []OverlayType {
	return _OverlayTypeValues
}

// OverlayTypeStrings returns a slice of all String values of the enum
func OverlayTypeStrings() []string {
	strs := make([]string, len(_OverlayTypeNames))
	copy(strs, _OverlayTypeNames)
	return strs
}

// IsAOverlayType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OverlayType) IsAOverlayType() bool {
	for _, v := range _OverlayTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for OverlayType
func (i OverlayType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for OverlayType
func (i *OverlayType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("OverlayType should be a string, got %s", data)
	}

	var err error
	*i, err = OverlayTypeString(s)
	return err
}
