// Code generated by "enumer -type=ProcessingStatus -json -transform=snake -trimprefix=Processing"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ProcessingStatusName = "pendingprocessingactivefailed"

var _ProcessingStatusIndex = [...]uint8{0, 7, 17, 23, 29}

const _ProcessingStatusLowerName = "pendingprocessingactivefailed"

func (i ProcessingStatus) String() string {
	if i < 0 || i >= ProcessingStatus(len(_ProcessingStatusIndex)-1) {
		return fmt.Sprintf("ProcessingStatus(%d)", i)
	}
	return _ProcessingStatusName[_ProcessingStatusIndex[i]:_ProcessingStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProcessingStatusNoOp() {
	var x [1]struct{}
	_ = x[ProcessingPending-(0)]
	_ = x[ProcessingProcessing-(1)]
	_ = x[ProcessingActive-(2)]
	_ = x[ProcessingFailed-(3)]
}

var _ProcessingStatusValues = []ProcessingStatus{ProcessingPending, ProcessingProcessing, ProcessingActive, ProcessingFailed}

var _ProcessingStatusNameToValueMap = map[string]ProcessingStatus{
	_ProcessingStatusName[0:7]:        ProcessingPending,
	_ProcessingStatusLowerName[0:7]:   ProcessingPending,
	_ProcessingStatusName[7:17]:       ProcessingProcessing,
	_ProcessingStatusLowerName[7:17]:  ProcessingProcessing,
	_ProcessingStatusName[17:23]:      ProcessingActive,
	_ProcessingStatusLowerName[17:23]: ProcessingActive,
	_ProcessingStatusName[23:29]:      ProcessingFailed,
	_ProcessingStatusLowerName[23:29]: ProcessingFailed,
}

var _ProcessingStatusNames = []string{
	_ProcessingStatusName[0:7],
	_ProcessingStatusName[7:17],
	_ProcessingStatusName[17:23],
	_ProcessingStatusName[23:29],
}

// ProcessingStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProcessingStatusString(s string) (ProcessingStatus, error) {
	if val, ok := _ProcessingStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProcessingStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ProcessingStatus values", s)
}

// ProcessingStatusValues returns all values of the enum
func ProcessingStatusValues() []ProcessingStatus {
	return _ProcessingStatusValues
}

// ProcessingStatusStrings returns a slice of all String values of the enum
func ProcessingStatusStrings() []string {
	strs := make([]string, len(_ProcessingStatusNames))
	copy(strs, _ProcessingStatusNames)
	return strs
}

// IsAProcessingStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProcessingStatus) IsAProcessingStatus() bool {
	for _, v := range _ProcessingStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ProcessingStatus
func (i ProcessingStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ProcessingStatus
func (i *ProcessingStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ProcessingStatus should be a string, got %s", data)
	}

	var err error
	*i, err = ProcessingStatusString(s)
	return err
}
