// Code generated by "enumer -type=ReelPrivacy -json -transform=snake -trimprefix=Privacy"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ReelPrivacyName = "publicfriendsonly_me"

var _ReelPrivacyIndex = [...]uint8{0, 6, 13, 20}

const _ReelPrivacyLowerName = "publicfriendsonly_me"

func (i ReelPrivacy) String() string {
	if i < 0 || i >= ReelPrivacy(len(_ReelPrivacyIndex)-1) {
		return fmt.Sprintf("ReelPrivacy(%d)", i)
	}
	return _ReelPrivacyName[_ReelPrivacyIndex[i]:_ReelPrivacyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ReelPrivacyNoOp() {
	var x [1]struct{}
	_ = x[PrivacyPublic-(0)]
	_ = x[PrivacyFriends-(1)]
	_ = x[PrivacyOnlyMe-(2)]
}

var _ReelPrivacyValues = []ReelPrivacy{PrivacyPublic, PrivacyFriends, PrivacyOnlyMe}

var _ReelPrivacyNameToValueMap = map[string]ReelPrivacy{
	_ReelPrivacyName[0:6]:        PrivacyPublic,
	_ReelPrivacyLowerName[0:6]:   PrivacyPublic,
	_ReelPrivacyName[6:13]:       PrivacyFriends,
	_ReelPrivacyLowerName[6:13]:  PrivacyFriends,
	_ReelPrivacyName[13:20]:      PrivacyOnlyMe,
	_ReelPrivacyLowerName[13:20]: PrivacyOnlyMe,
}

var _ReelPrivacyNames = []string{
	_ReelPrivacyName[0:6],
	_ReelPrivacyName[6:13],
	_ReelPrivacyName[13:20],
}

// ReelPrivacyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ReelPrivacyString(s string) (ReelPrivacy, error) {
	if val, ok := _ReelPrivacyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ReelPrivacyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ReelPrivacy values", s)
}

// ReelPrivacyValues returns all values of the enum
func ReelPrivacyValues() []ReelPrivacy {
	return _ReelPrivacyValues
}

// ReelPrivacyStrings returns a slice of all String values of the enum
func ReelPrivacyStrings() []string {
	strs := make([]string, len(_ReelPrivacyNames))
	copy(strs, _ReelPrivacyNames)
	return strs
}

// IsAReelPrivacy returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ReelPrivacy) IsAReelPrivacy() bool {
	for _, v := range _ReelPrivacyValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ReelPrivacy
func (i ReelPrivacy) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ReelPrivacy
func (i *ReelPrivacy) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ReelPrivacy should be a string, got %s", data)
	}

	var err error
	*i, err = ReelPrivacyString(s)
	return err
}
