// Code generated by "enumer -type=RemixType -json -transform=snake -trimprefix=Remix"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _RemixTypeName = "duetremix"

var _RemixTypeIndex = [...]uint8{0, 4, 9}

const _RemixTypeLowerName = "duetremix"

func (i RemixType) String() string {
	if i < 0 || i >= RemixType(len(_RemixTypeIndex)-1) {
		return fmt.Sprintf("RemixType(%d)", i)
	}
	return _RemixTypeName[_RemixTypeIndex[i]:_RemixTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RemixTypeNoOp() {
	var x [1]struct{}
	_ = x[RemixDuet-(0)]
	_ = x[RemixRemix-(1)]
}

var _RemixTypeValues = []RemixType{RemixDuet, RemixRemix}

var _RemixTypeNameToValueMap = map[string]RemixType{
	_RemixTypeName[0:4]:      RemixDuet,
	_RemixTypeLowerName[0:4]: RemixDuet,
	_RemixTypeName[4:9]:      RemixRemix,
	_RemixTypeLowerName[4:9]: RemixRemix,
}

var _RemixTypeNames = []string{
	_RemixTypeName[0:4],
	_RemixTypeName[4:9],
}

// RemixTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RemixTypeString(s string) (RemixType, error) {
	if val, ok := _RemixTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RemixTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RemixType values", s)
}

// RemixTypeValues returns all values of the enum
func RemixTypeValues() []RemixType {
	return _RemixTypeValues
}

// RemixTypeStrings returns a slice of all String values of the enum
func RemixTypeStrings() []string {
	strs := make([]string, len(_RemixTypeNames))
	copy(strs, _RemixTypeNames)
	return strs
}

// IsARemixType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RemixType) IsARemixType() bool {
	for _, v := range _RemixTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for RemixType
func (i RemixType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for RemixType
func (i *RemixType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("RemixType should be a string, got %s", data)
	}

	var err error
	*i, err = RemixTypeString(s)
	return err
}
