// Code generated by "enumer -type=StoryPrivacyType -json -transform=snake -trimprefix=StoryPrivacy"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _StoryPrivacyTypeName = "publicfriendsclose_friendscustom"

var _StoryPrivacyTypeIndex = [...]uint8{0, 6, 13, 26, 32}

const _StoryPrivacyTypeLowerName = "publicfriendsclose_friendscustom"

func (i StoryPrivacyType) String() string {
	if i < 0 || i >= StoryPrivacyType(len(_StoryPrivacyTypeIndex)-1) {
		return fmt.Sprintf("StoryPrivacyType(%d)", i)
	}
	return _StoryPrivacyTypeName[_StoryPrivacyTypeIndex[i]:_StoryPrivacyTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StoryPrivacyTypeNoOp() {
	var x [1]struct{}
	_ = x[StoryPrivacyPublic-(0)]
	_ = x[StoryPrivacyFriends-(1)]
	_ = x[StoryPrivacyCloseFriends-(2)]
	_ = x[StoryPrivacyCustom-(3)]
}

var _StoryPrivacyTypeValues = []StoryPrivacyType{StoryPrivacyPublic, StoryPrivacyFriends, StoryPrivacyCloseFriends, StoryPrivacyCustom}

var _StoryPrivacyTypeNameToValueMap = map[string]StoryPrivacyType{
	_StoryPrivacyTypeName[0:6]:        StoryPrivacyPublic,
	_StoryPrivacyTypeLowerName[0:6]:   StoryPrivacyPublic,
	_StoryPrivacyTypeName[6:13]:       StoryPrivacyFriends,
	_StoryPrivacyTypeLowerName[6:13]:  StoryPrivacyFriends,
	_StoryPrivacyTypeName[13:26]:      StoryPrivacyCloseFriends,
	_StoryPrivacyTypeLowerName[13:26]: StoryPrivacyCloseFriends,
	_StoryPrivacyTypeName[26:32]:      StoryPrivacyCustom,
	_StoryPrivacyTypeLowerName[26:32]: StoryPrivacyCustom,
}

var _StoryPrivacyTypeNames = []string{
	_StoryPrivacyTypeName[0:6],
	_StoryPrivacyTypeName[6:13],
	_StoryPrivacyTypeName[13:26],
	_StoryPrivacyTypeName[26:32],
}

// StoryPrivacyTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StoryPrivacyTypeString(s string) (StoryPrivacyType, error) {
	if val, ok := _StoryPrivacyTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StoryPrivacyTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to StoryPrivacyType values", s)
}

// StoryPrivacyTypeValues returns all values of the enum
func StoryPrivacyTypeValues() []StoryPrivacyType {
	return _StoryPrivacyTypeValues
}

// StoryPrivacyTypeStrings returns a slice of all String values of the enum
func StoryPrivacyTypeStrings() []string {
	strs := make([]string, len(_StoryPrivacyTypeNames))
	copy(strs, _StoryPrivacyTypeNames)
	return strs
}

// IsAStoryPrivacyType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i StoryPrivacyType) IsAStoryPrivacyType() bool {
	for _, v := range _StoryPrivacyTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for StoryPrivacyType
func (i StoryPrivacyType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for StoryPrivacyType
func (i *StoryPrivacyType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("StoryPrivacyType should be a string, got %s", data)
	}

	var err error
	*i, err = StoryPrivacyTypeString(s)
	return err
}
