// Code generated by "enumer -type=StoryMediaType -json -transform=snake -trimprefix=StoryMedia"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _StoryMediaTypeName = "imagevideo"

var _StoryMediaTypeIndex = [...]uint8{0, 5, 10}

const _StoryMediaTypeLowerName = "imagevideo"

func (i StoryMediaType) String() string {
	if i < 0 || i >= StoryMediaType(len(_StoryMediaTypeIndex)-1) {
		return fmt.Sprintf("StoryMediaType(%d)", i)
	}
	return _StoryMediaTypeName[_StoryMediaTypeIndex[i]:_StoryMediaTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StoryMediaTypeNoOp() {
	var x [1]struct{}
	_ = x[StoryMediaImage-(0)]
	_ = x[StoryMediaVideo-(1)]
}

var _StoryMediaTypeValues = []StoryMediaType{StoryMediaImage, StoryMediaVideo}

var _StoryMediaTypeNameToValueMap = map[string]StoryMediaType{
	_StoryMediaTypeName[0:5]:       StoryMediaImage,
	_StoryMediaTypeLowerName[0:5]:  StoryMediaImage,
	_StoryMediaTypeName[5:10]:      StoryMediaVideo,
	_StoryMediaTypeLowerName[5:10]: StoryMediaVideo,
}

var _StoryMediaTypeNames = []string{
	_StoryMediaTypeName[0:5],
	_StoryMediaTypeName[5:10],
}

// StoryMediaTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StoryMediaTypeString(s string) (StoryMediaType, error) {
	if val, ok := _StoryMediaTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StoryMediaTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to StoryMediaType values", s)
}

// StoryMediaTypeValues returns all values of the enum
func StoryMediaTypeValues() []StoryMediaType {
	return _StoryMediaTypeValues
}

// StoryMediaTypeStrings returns a slice of all String values of the enum
func StoryMediaTypeStrings() []string {
	strs := make([]string, len(_StoryMediaTypeNames))
	copy(strs, _StoryMediaTypeNames)
	return strs
}

// IsAStoryMediaType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i StoryMediaType) IsAStoryMediaType() bool {
	for _, v := range _StoryMediaTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for StoryMediaType
func (i StoryMediaType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for StoryMediaType
func (i *StoryMediaType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("StoryMediaType should be a string, got %s", data)
	}

	var err error
	*i, err = StoryMediaTypeString(s)
	return err
}
