// Code generated by "enumer -type=StoryInteractionType -json -transform=snake -trimprefix=Interaction"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _StoryInteractionTypeName = "viewreactionpoll_vote"

var _StoryInteractionTypeIndex = [...]uint8{0, 4, 12, 21}

const _StoryInteractionTypeLowerName = "viewreactionpoll_vote"

func (i StoryInteractionType) String() string {
	if i < 0 || i >= StoryInteractionType(len(_StoryInteractionTypeIndex)-1) {
		return fmt.Sprintf("StoryInteractionType(%d)", i)
	}
	return _StoryInteractionTypeName[_StoryInteractionTypeIndex[i]:_StoryInteractionTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StoryInteractionTypeNoOp() {
	var x [1]struct{}
	_ = x[InteractionView-(0)]
	_ = x[InteractionReaction-(1)]
	_ = x[InteractionPollVote-(2)]
}

var _StoryInteractionTypeValues = []StoryInteractionType{InteractionView, InteractionReaction, InteractionPollVote}

var _StoryInteractionTypeNameToValueMap = map[string]StoryInteractionType{
	_StoryInteractionTypeName[0:4]:        InteractionView,
	_StoryInteractionTypeLowerName[0:4]:   InteractionView,
	_StoryInteractionTypeName[4:12]:       InteractionReaction,
	_StoryInteractionTypeLowerName[4:12]:  InteractionReaction,
	_StoryInteractionTypeName[12:21]:      InteractionPollVote,
	_StoryInteractionTypeLowerName[12:21]: InteractionPollVote,
}

var _StoryInteractionTypeNames = []string{
	_StoryInteractionTypeName[0:4],
	_StoryInteractionTypeName[4:12],
	_StoryInteractionTypeName[12:21],
}

// StoryInteractionTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StoryInteractionTypeString(s string) (StoryInteractionType, error) {
	if val, ok := _StoryInteractionTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StoryInteractionTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to StoryInteractionType values", s)
}

// StoryInteractionTypeValues returns all values of the enum
func StoryInteractionTypeValues() []StoryInteractionType {
	return _StoryInteractionTypeValues
}

// StoryInteractionTypeStrings returns a slice of all String values of the enum
func StoryInteractionTypeStrings() []string {
	strs := make([]string, len(_StoryInteractionTypeNames))
	copy(strs, _StoryInteractionTypeNames)
	return strs
}

// IsAStoryInteractionType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i StoryInteractionType) IsAStoryInteractionType() bool {
	for _, v := range _StoryInteractionTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for StoryInteractionType
func (i StoryInteractionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for StoryInteractionType
func (i *StoryInteractionType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("StoryInteractionType should be a string, got %s", data)
	}

	var err error
	*i, err = StoryInteractionTypeString(s)
	return err
}
