// Code generated by "enumer -type=TagStatus -json -transform=snake -trimprefix=TagStatus"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TagStatusName = "pendingapproved"

var _TagStatusIndex = [...]uint8{0, 7, 15}

const _TagStatusLowerName = "pendingapproved"

func (i TagStatus) String() string {
	if i < 0 || i >= TagStatus(len(_TagStatusIndex)-1) {
		return fmt.Sprintf("TagStatus(%d)", i)
	}
	return _TagStatusName[_TagStatusIndex[i]:_TagStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TagStatusNoOp() {
	var x [1]struct{}
	_ = x[TagStatusPending-(0)]
	_ = x[TagStatusApproved-(1)]
}

var _TagStatusValues = []TagStatus{TagStatusPending, TagStatusApproved}

var _TagStatusNameToValueMap = map[string]TagStatus{
	_TagStatusName[0:7]:       TagStatusPending,
	_TagStatusLowerName[0:7]:  TagStatusPending,
	_TagStatusName[7:15]:      TagStatusApproved,
	_TagStatusLowerName[7:15]: TagStatusApproved,
}

var _TagStatusNames = []string{
	_TagStatusName[0:7],
	_TagStatusName[7:15],
}

// TagStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TagStatusString(s string) (TagStatus, error) {
	if val, ok := _TagStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TagStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TagStatus values", s)
}

// TagStatusValues returns all values of the enum
func TagStatusValues() []TagStatus {
	return _TagStatusValues
}

// TagStatusStrings returns a slice of all String values of the enum
func TagStatusStrings() []string {
	strs := make([]string, len(_TagStatusNames))
	copy(strs, _TagStatusNames)
	return strs
}

// IsATagStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TagStatus) IsATagStatus() bool {
	for _, v := range _TagStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TagStatus
func (i TagStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TagStatus
func (i *TagStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TagStatus should be a string, got %s", data)
	}

	var err error
	*i, err = TagStatusString(s)
	return err
}
