// Code generated by "enumer -type=UserBadge -json -transform=snake -trimprefix=Badge"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _UserBadgeName = "moderatortop_fangifterverifiedstaff"

var _UserBadgeIndex = [...]uint8{0, 9, 16, 22, 30, 35}

const _UserBadgeLowerName = "moderatortop_fangifterverifiedstaff"

func (i UserBadge) String() string {
	if i < 0 || i >= UserBadge(len(_UserBadgeIndex)-1) {
		return fmt.Sprintf("UserBadge(%d)", i)
	}
	return _UserBadgeName[_UserBadgeIndex[i]:_UserBadgeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _UserBadgeNoOp() {
	var x [1]struct{}
	_ = x[BadgeModerator-(0)]
	_ = x[BadgeTopFan-(1)]
	_ = x[BadgeGifter-(2)]
	_ = x[BadgeVerified-(3)]
	_ = x[BadgeStaff-(4)]
}

var _UserBadgeValues = []UserBadge{BadgeModerator, BadgeTopFan, BadgeGifter, BadgeVerified, BadgeStaff}

var _UserBadgeNameToValueMap = map[string]UserBadge{
	_UserBadgeName[0:9]:        BadgeModerator,
	_UserBadgeLowerName[0:9]:   BadgeModerator,
	_UserBadgeName[9:16]:       BadgeTopFan,
	_UserBadgeLowerName[9:16]:  BadgeTopFan,
	_UserBadgeName[16:22]:      BadgeGifter,
	_UserBadgeLowerName[16:22]: BadgeGifter,
	_UserBadgeName[22:30]:      BadgeVerified,
	_UserBadgeLowerName[22:30]: BadgeVerified,
	_UserBadgeName[30:35]:      BadgeStaff,
	_UserBadgeLowerName[30:35]: BadgeStaff,
}

var _UserBadgeNames = []string{
	_UserBadgeName[0:9],
	_UserBadgeName[9:16],
	_UserBadgeName[16:22],
	_UserBadgeName[22:30],
	_UserBadgeName[30:35],
}

// UserBadgeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func UserBadgeString(s string) (UserBadge, error) {
	if val, ok := _UserBadgeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _UserBadgeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to UserBadge values", s)
}

// UserBadgeValues returns all values of the enum
func UserBadgeValues() []UserBadge {
	return _UserBadgeValues
}

// UserBadgeStrings returns a slice of all String values of the enum
func UserBadgeStrings() []string {
	strs := make([]string, len(_UserBadgeNames))
	copy(strs, _UserBadgeNames)
	return strs
}

// IsAUserBadge returns "true" if the value is listed in the enum definition. "false" otherwise
func (i UserBadge) IsAUserBadge() bool {
	for _, v := range _UserBadgeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for UserBadge
func (i UserBadge) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for UserBadge
func (i *UserBadge) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("UserBadge should be a string, got %s", data)
	}

	var err error
	*i, err = UserBadgeString(s)
	return err
}
