syntax = "proto3";
package api.proto.v1;
option go_package = "github.com/quang/social-network/pkg/pb/v1;pb";

service CommunityService {
 rpc GetRoleUserInGroup (GetRoleUserInGroupRequest) returns (GetRoleUserInGroupResponse);
 rpc GetGroupInfo (GetGroupInfoRequest) returns (GetGroupInfoResponse);
}
message GetRoleUserInGroupRequest {
 string group_id = 1;
 string user_id = 2;
}
message GetRoleUserInGroupResponse {
  string role = 1;
}
message GetGroupInfoRequest {
 string group_id = 1;
}
message GetGroupInfoResponse {
 string group_id = 1;
 string protected = 2;
}