syntax = "proto3";

package api.proto.v1;

option go_package = "github.com/quang/social-network/pkg/pb/v1;pb";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
service IdentityService {
  rpc GetUserOTP (google.protobuf.Empty) returns (UserIDResponse);
  rpc GetUserSettingByID (UserSettingIDRequest) returns (UserSettingResponse);
  rpc CheckUSERIDExistence (UserIDRequest) returns (UserIDExistenceResponse);
}
message UserIDRequest {
  string user_id = 1;
}
message UserIDExistenceResponse {
  bool exists = 1;
}
message UserIDResponse {
  string user_id = 1;
}
message UserSettingIDRequest {
  string user_id = 1;
}
// --- Response & Models ---

message NotificationSettings {
  string email_frequency = 1;
  bool push_interactions = 2;
  bool push_friends = 3;
  bool push_groups = 4;
  bool push_events = 5;
  bool push_birthdays = 6;
}

message UserSettingResponse {
  string id = 1; // Map từ primitive.ObjectID
  string user_id = 2;
  // 2. PRIVACY DEFAULTS
  string default_post_audience = 9;  // Map từ sharedEnums.PrivacyScope
  string default_story_audience = 10; // Map từ sharedEnums.PrivacyScope
  // 3. ACCESS CONTROL
  string allow_friend_request_from = 11;
  string allow_friend_list_view_from = 12;
  bool allow_search_engine_indexing = 15;
  bool Allow_Profile_View_From = 13;
  // 4. TIMELINE & TAGGING
  string allow_timeline_posting_from = 16;
  bool review_tags_enabled = 17;
  bool review_timeline_posts_enabled = 18;
  // 5. NOTIFICATIONS
  NotificationSettings notifications = 19;
  google.protobuf.Timestamp updated_at = 20;
}