// Code generated by "enumer -type=AdStatus -json -transform=snake -trimprefix=AdStatus"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AdStatusName = "reviewingactiverejectedpaused"

var _AdStatusIndex = [...]uint8{0, 9, 15, 23, 29}

const _AdStatusLowerName = "reviewingactiverejectedpaused"

func (i AdStatus) String() string {
	if i < 0 || i >= AdStatus(len(_AdStatusIndex)-1) {
		return fmt.Sprintf("AdStatus(%d)", i)
	}
	return _AdStatusName[_AdStatusIndex[i]:_AdStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AdStatusNoOp() {
	var x [1]struct{}
	_ = x[AdStatusReviewing-(0)]
	_ = x[AdStatusActive-(1)]
	_ = x[AdStatusRejected-(2)]
	_ = x[AdStatusPaused-(3)]
}

var _AdStatusValues = []AdStatus{AdStatusReviewing, AdStatusActive, AdStatusRejected, AdStatusPaused}

var _AdStatusNameToValueMap = map[string]AdStatus{
	_AdStatusName[0:9]:        AdStatusReviewing,
	_AdStatusLowerName[0:9]:   AdStatusReviewing,
	_AdStatusName[9:15]:       AdStatusActive,
	_AdStatusLowerName[9:15]:  AdStatusActive,
	_AdStatusName[15:23]:      AdStatusRejected,
	_AdStatusLowerName[15:23]: AdStatusRejected,
	_AdStatusName[23:29]:      AdStatusPaused,
	_AdStatusLowerName[23:29]: AdStatusPaused,
}

var _AdStatusNames = []string{
	_AdStatusName[0:9],
	_AdStatusName[9:15],
	_AdStatusName[15:23],
	_AdStatusName[23:29],
}

// AdStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AdStatusString(s string) (AdStatus, error) {
	if val, ok := _AdStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AdStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AdStatus values", s)
}

// AdStatusValues returns all values of the enum
func AdStatusValues() []AdStatus {
	return _AdStatusValues
}

// AdStatusStrings returns a slice of all String values of the enum
func AdStatusStrings() []string {
	strs := make([]string, len(_AdStatusNames))
	copy(strs, _AdStatusNames)
	return strs
}

// IsAAdStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AdStatus) IsAAdStatus() bool {
	for _, v := range _AdStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AdStatus
func (i AdStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AdStatus
func (i *AdStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AdStatus should be a string, got %s", data)
	}

	var err error
	*i, err = AdStatusString(s)
	return err
}
