// Code generated by "enumer -type=BuyingType -json -transform=snake -trimprefix=Buying"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _BuyingTypeName = "auctionfixed_price"

var _BuyingTypeIndex = [...]uint8{0, 7, 18}

const _BuyingTypeLowerName = "auctionfixed_price"

func (i BuyingType) String() string {
	if i < 0 || i >= BuyingType(len(_BuyingTypeIndex)-1) {
		return fmt.Sprintf("BuyingType(%d)", i)
	}
	return _BuyingTypeName[_BuyingTypeIndex[i]:_BuyingTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BuyingTypeNoOp() {
	var x [1]struct{}
	_ = x[BuyingAuction-(0)]
	_ = x[BuyingFixedPrice-(1)]
}

var _BuyingTypeValues = []BuyingType{BuyingAuction, BuyingFixedPrice}

var _BuyingTypeNameToValueMap = map[string]BuyingType{
	_BuyingTypeName[0:7]:       BuyingAuction,
	_BuyingTypeLowerName[0:7]:  BuyingAuction,
	_BuyingTypeName[7:18]:      BuyingFixedPrice,
	_BuyingTypeLowerName[7:18]: BuyingFixedPrice,
}

var _BuyingTypeNames = []string{
	_BuyingTypeName[0:7],
	_BuyingTypeName[7:18],
}

// BuyingTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BuyingTypeString(s string) (BuyingType, error) {
	if val, ok := _BuyingTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BuyingTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BuyingType values", s)
}

// BuyingTypeValues returns all values of the enum
func BuyingTypeValues() []BuyingType {
	return _BuyingTypeValues
}

// BuyingTypeStrings returns a slice of all String values of the enum
func BuyingTypeStrings() []string {
	strs := make([]string, len(_BuyingTypeNames))
	copy(strs, _BuyingTypeNames)
	return strs
}

// IsABuyingType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BuyingType) IsABuyingType() bool {
	for _, v := range _BuyingTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for BuyingType
func (i BuyingType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for BuyingType
func (i *BuyingType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BuyingType should be a string, got %s", data)
	}

	var err error
	*i, err = BuyingTypeString(s)
	return err
}
