// Code generated by "enumer -type=CampaignStatus -json -transform=snake -trimprefix=CampaignStatus"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _CampaignStatusName = "activepausedcompletedarchived"

var _CampaignStatusIndex = [...]uint8{0, 6, 12, 21, 29}

const _CampaignStatusLowerName = "activepausedcompletedarchived"

func (i CampaignStatus) String() string {
	if i < 0 || i >= CampaignStatus(len(_CampaignStatusIndex)-1) {
		return fmt.Sprintf("CampaignStatus(%d)", i)
	}
	return _CampaignStatusName[_CampaignStatusIndex[i]:_CampaignStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CampaignStatusNoOp() {
	var x [1]struct{}
	_ = x[CampaignStatusActive-(0)]
	_ = x[CampaignStatusPaused-(1)]
	_ = x[CampaignStatusCompleted-(2)]
	_ = x[CampaignStatusArchived-(3)]
}

var _CampaignStatusValues = []CampaignStatus{CampaignStatusActive, CampaignStatusPaused, CampaignStatusCompleted, CampaignStatusArchived}

var _CampaignStatusNameToValueMap = map[string]CampaignStatus{
	_CampaignStatusName[0:6]:        CampaignStatusActive,
	_CampaignStatusLowerName[0:6]:   CampaignStatusActive,
	_CampaignStatusName[6:12]:       CampaignStatusPaused,
	_CampaignStatusLowerName[6:12]:  CampaignStatusPaused,
	_CampaignStatusName[12:21]:      CampaignStatusCompleted,
	_CampaignStatusLowerName[12:21]: CampaignStatusCompleted,
	_CampaignStatusName[21:29]:      CampaignStatusArchived,
	_CampaignStatusLowerName[21:29]: CampaignStatusArchived,
}

var _CampaignStatusNames = []string{
	_CampaignStatusName[0:6],
	_CampaignStatusName[6:12],
	_CampaignStatusName[12:21],
	_CampaignStatusName[21:29],
}

// CampaignStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CampaignStatusString(s string) (CampaignStatus, error) {
	if val, ok := _CampaignStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CampaignStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CampaignStatus values", s)
}

// CampaignStatusValues returns all values of the enum
func CampaignStatusValues() []CampaignStatus {
	return _CampaignStatusValues
}

// CampaignStatusStrings returns a slice of all String values of the enum
func CampaignStatusStrings() []string {
	strs := make([]string, len(_CampaignStatusNames))
	copy(strs, _CampaignStatusNames)
	return strs
}

// IsACampaignStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CampaignStatus) IsACampaignStatus() bool {
	for _, v := range _CampaignStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CampaignStatus
func (i CampaignStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CampaignStatus
func (i *CampaignStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CampaignStatus should be a string, got %s", data)
	}

	var err error
	*i, err = CampaignStatusString(s)
	return err
}
