// Code generated by "enumer -type=CampaignObjective -json -transform=snake -trimprefix=Objective"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _CampaignObjectiveName = "reachtrafficmessagesconversions"

var _CampaignObjectiveIndex = [...]uint8{0, 5, 12, 20, 31}

const _CampaignObjectiveLowerName = "reachtrafficmessagesconversions"

func (i CampaignObjective) String() string {
	if i < 0 || i >= CampaignObjective(len(_CampaignObjectiveIndex)-1) {
		return fmt.Sprintf("CampaignObjective(%d)", i)
	}
	return _CampaignObjectiveName[_CampaignObjectiveIndex[i]:_CampaignObjectiveIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CampaignObjectiveNoOp() {
	var x [1]struct{}
	_ = x[ObjectiveReach-(0)]
	_ = x[ObjectiveTraffic-(1)]
	_ = x[ObjectiveMessages-(2)]
	_ = x[ObjectiveConversions-(3)]
}

var _CampaignObjectiveValues = []CampaignObjective{ObjectiveReach, ObjectiveTraffic, ObjectiveMessages, ObjectiveConversions}

var _CampaignObjectiveNameToValueMap = map[string]CampaignObjective{
	_CampaignObjectiveName[0:5]:        ObjectiveReach,
	_CampaignObjectiveLowerName[0:5]:   ObjectiveReach,
	_CampaignObjectiveName[5:12]:       ObjectiveTraffic,
	_CampaignObjectiveLowerName[5:12]:  ObjectiveTraffic,
	_CampaignObjectiveName[12:20]:      ObjectiveMessages,
	_CampaignObjectiveLowerName[12:20]: ObjectiveMessages,
	_CampaignObjectiveName[20:31]:      ObjectiveConversions,
	_CampaignObjectiveLowerName[20:31]: ObjectiveConversions,
}

var _CampaignObjectiveNames = []string{
	_CampaignObjectiveName[0:5],
	_CampaignObjectiveName[5:12],
	_CampaignObjectiveName[12:20],
	_CampaignObjectiveName[20:31],
}

// CampaignObjectiveString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CampaignObjectiveString(s string) (CampaignObjective, error) {
	if val, ok := _CampaignObjectiveNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CampaignObjectiveNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CampaignObjective values", s)
}

// CampaignObjectiveValues returns all values of the enum
func CampaignObjectiveValues() []CampaignObjective {
	return _CampaignObjectiveValues
}

// CampaignObjectiveStrings returns a slice of all String values of the enum
func CampaignObjectiveStrings() []string {
	strs := make([]string, len(_CampaignObjectiveNames))
	copy(strs, _CampaignObjectiveNames)
	return strs
}

// IsACampaignObjective returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CampaignObjective) IsACampaignObjective() bool {
	for _, v := range _CampaignObjectiveValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CampaignObjective
func (i CampaignObjective) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CampaignObjective
func (i *CampaignObjective) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CampaignObjective should be a string, got %s", data)
	}

	var err error
	*i, err = CampaignObjectiveString(s)
	return err
}
