// Code generated by "enumer -type=CTAType -json -transform=snake -trimprefix=CTA"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _CTATypeName = "send_messagecall_nowvisit_websiteshop_nowfollow"

var _CTATypeIndex = [...]uint8{0, 12, 20, 33, 41, 47}

const _CTATypeLowerName = "send_messagecall_nowvisit_websiteshop_nowfollow"

func (i CTAType) String() string {
	if i < 0 || i >= CTAType(len(_CTATypeIndex)-1) {
		return fmt.Sprintf("CTAType(%d)", i)
	}
	return _CTATypeName[_CTATypeIndex[i]:_CTATypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CTATypeNoOp() {
	var x [1]struct{}
	_ = x[CTASendMessage-(0)]
	_ = x[CTACallNow-(1)]
	_ = x[CTAVisitWebsite-(2)]
	_ = x[CTAShopNow-(3)]
	_ = x[CTAFollow-(4)]
}

var _CTATypeValues = []CTAType{CTASendMessage, CTACallNow, CTAVisitWebsite, CTAShopNow, CTAFollow}

var _CTATypeNameToValueMap = map[string]CTAType{
	_CTATypeName[0:12]:       CTASendMessage,
	_CTATypeLowerName[0:12]:  CTASendMessage,
	_CTATypeName[12:20]:      CTACallNow,
	_CTATypeLowerName[12:20]: CTACallNow,
	_CTATypeName[20:33]:      CTAVisitWebsite,
	_CTATypeLowerName[20:33]: CTAVisitWebsite,
	_CTATypeName[33:41]:      CTAShopNow,
	_CTATypeLowerName[33:41]: CTAShopNow,
	_CTATypeName[41:47]:      CTAFollow,
	_CTATypeLowerName[41:47]: CTAFollow,
}

var _CTATypeNames = []string{
	_CTATypeName[0:12],
	_CTATypeName[12:20],
	_CTATypeName[20:33],
	_CTATypeName[33:41],
	_CTATypeName[41:47],
}

// CTATypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CTATypeString(s string) (CTAType, error) {
	if val, ok := _CTATypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CTATypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CTAType values", s)
}

// CTATypeValues returns all values of the enum
func CTATypeValues() []CTAType {
	return _CTATypeValues
}

// CTATypeStrings returns a slice of all String values of the enum
func CTATypeStrings() []string {
	strs := make([]string, len(_CTATypeNames))
	copy(strs, _CTATypeNames)
	return strs
}

// IsACTAType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CTAType) IsACTAType() bool {
	for _, v := range _CTATypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CTAType
func (i CTAType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CTAType
func (i *CTAType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CTAType should be a string, got %s", data)
	}

	var err error
	*i, err = CTATypeString(s)
	return err
}
