// Code generated by "enumer -type=DayOfWeek -json -transform=title -trimprefix=Day"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DayOfWeekName = "MondayTuesdayWednesdayThursdayFridaySaturdaySunday"

var _DayOfWeekIndex = [...]uint8{0, 6, 13, 22, 30, 36, 44, 50}

const _DayOfWeekLowerName = "mondaytuesdaywednesdaythursdayfridaysaturdaysunday"

func (i DayOfWeek) String() string {
	if i < 0 || i >= DayOfWeek(len(_DayOfWeekIndex)-1) {
		return fmt.Sprintf("DayOfWeek(%d)", i)
	}
	return _DayOfWeekName[_DayOfWeekIndex[i]:_DayOfWeekIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DayOfWeekNoOp() {
	var x [1]struct{}
	_ = x[DayMonday-(0)]
	_ = x[DayTuesday-(1)]
	_ = x[DayWednesday-(2)]
	_ = x[DayThursday-(3)]
	_ = x[DayFriday-(4)]
	_ = x[DaySaturday-(5)]
	_ = x[DaySunday-(6)]
}

var _DayOfWeekValues = []DayOfWeek{DayMonday, DayTuesday, DayWednesday, DayThursday, DayFriday, DaySaturday, DaySunday}

var _DayOfWeekNameToValueMap = map[string]DayOfWeek{
	_DayOfWeekName[0:6]:        DayMonday,
	_DayOfWeekLowerName[0:6]:   DayMonday,
	_DayOfWeekName[6:13]:       DayTuesday,
	_DayOfWeekLowerName[6:13]:  DayTuesday,
	_DayOfWeekName[13:22]:      DayWednesday,
	_DayOfWeekLowerName[13:22]: DayWednesday,
	_DayOfWeekName[22:30]:      DayThursday,
	_DayOfWeekLowerName[22:30]: DayThursday,
	_DayOfWeekName[30:36]:      DayFriday,
	_DayOfWeekLowerName[30:36]: DayFriday,
	_DayOfWeekName[36:44]:      DaySaturday,
	_DayOfWeekLowerName[36:44]: DaySaturday,
	_DayOfWeekName[44:50]:      DaySunday,
	_DayOfWeekLowerName[44:50]: DaySunday,
}

var _DayOfWeekNames = []string{
	_DayOfWeekName[0:6],
	_DayOfWeekName[6:13],
	_DayOfWeekName[13:22],
	_DayOfWeekName[22:30],
	_DayOfWeekName[30:36],
	_DayOfWeekName[36:44],
	_DayOfWeekName[44:50],
}

// DayOfWeekString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DayOfWeekString(s string) (DayOfWeek, error) {
	if val, ok := _DayOfWeekNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DayOfWeekNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DayOfWeek values", s)
}

// DayOfWeekValues returns all values of the enum
func DayOfWeekValues() []DayOfWeek {
	return _DayOfWeekValues
}

// DayOfWeekStrings returns a slice of all String values of the enum
func DayOfWeekStrings() []string {
	strs := make([]string, len(_DayOfWeekNames))
	copy(strs, _DayOfWeekNames)
	return strs
}

// IsADayOfWeek returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DayOfWeek) IsADayOfWeek() bool {
	for _, v := range _DayOfWeekValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DayOfWeek
func (i DayOfWeek) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DayOfWeek
func (i *DayOfWeek) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DayOfWeek should be a string, got %s", data)
	}

	var err error
	*i, err = DayOfWeekString(s)
	return err
}
