// Code generated by "enumer -type=FollowType -json -transform=snake -trimprefix=FollowType"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _FollowTypeName = "followlike"

var _FollowTypeIndex = [...]uint8{0, 6, 10}

const _FollowTypeLowerName = "followlike"

func (i FollowType) String() string {
	if i < 0 || i >= FollowType(len(_FollowTypeIndex)-1) {
		return fmt.Sprintf("FollowType(%d)", i)
	}
	return _FollowTypeName[_FollowTypeIndex[i]:_FollowTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FollowTypeNoOp() {
	var x [1]struct{}
	_ = x[FollowTypeFollow-(0)]
	_ = x[FollowTypeLike-(1)]
}

var _FollowTypeValues = []FollowType{FollowTypeFollow, FollowTypeLike}

var _FollowTypeNameToValueMap = map[string]FollowType{
	_FollowTypeName[0:6]:       FollowTypeFollow,
	_FollowTypeLowerName[0:6]:  FollowTypeFollow,
	_FollowTypeName[6:10]:      FollowTypeLike,
	_FollowTypeLowerName[6:10]: FollowTypeLike,
}

var _FollowTypeNames = []string{
	_FollowTypeName[0:6],
	_FollowTypeName[6:10],
}

// FollowTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FollowTypeString(s string) (FollowType, error) {
	if val, ok := _FollowTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FollowTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FollowType values", s)
}

// FollowTypeValues returns all values of the enum
func FollowTypeValues() []FollowType {
	return _FollowTypeValues
}

// FollowTypeStrings returns a slice of all String values of the enum
func FollowTypeStrings() []string {
	strs := make([]string, len(_FollowTypeNames))
	copy(strs, _FollowTypeNames)
	return strs
}

// IsAFollowType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FollowType) IsAFollowType() bool {
	for _, v := range _FollowTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FollowType
func (i FollowType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FollowType
func (i *FollowType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FollowType should be a string, got %s", data)
	}

	var err error
	*i, err = FollowTypeString(s)
	return err
}
