// Code generated by "enumer -type=MessagingStatus -json -transform=snake -trimprefix=MsgStatus"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MessagingStatusName = "onlineaway"

var _MessagingStatusIndex = [...]uint8{0, 6, 10}

const _MessagingStatusLowerName = "onlineaway"

func (i MessagingStatus) String() string {
	if i < 0 || i >= MessagingStatus(len(_MessagingStatusIndex)-1) {
		return fmt.Sprintf("MessagingStatus(%d)", i)
	}
	return _MessagingStatusName[_MessagingStatusIndex[i]:_MessagingStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MessagingStatusNoOp() {
	var x [1]struct{}
	_ = x[MsgStatusOnline-(0)]
	_ = x[MsgStatusAway-(1)]
}

var _MessagingStatusValues = []MessagingStatus{MsgStatusOnline, MsgStatusAway}

var _MessagingStatusNameToValueMap = map[string]MessagingStatus{
	_MessagingStatusName[0:6]:       MsgStatusOnline,
	_MessagingStatusLowerName[0:6]:  MsgStatusOnline,
	_MessagingStatusName[6:10]:      MsgStatusAway,
	_MessagingStatusLowerName[6:10]: MsgStatusAway,
}

var _MessagingStatusNames = []string{
	_MessagingStatusName[0:6],
	_MessagingStatusName[6:10],
}

// MessagingStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MessagingStatusString(s string) (MessagingStatus, error) {
	if val, ok := _MessagingStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MessagingStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MessagingStatus values", s)
}

// MessagingStatusValues returns all values of the enum
func MessagingStatusValues() []MessagingStatus {
	return _MessagingStatusValues
}

// MessagingStatusStrings returns a slice of all String values of the enum
func MessagingStatusStrings() []string {
	strs := make([]string, len(_MessagingStatusNames))
	copy(strs, _MessagingStatusNames)
	return strs
}

// IsAMessagingStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MessagingStatus) IsAMessagingStatus() bool {
	for _, v := range _MessagingStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MessagingStatus
func (i MessagingStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MessagingStatus
func (i *MessagingStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MessagingStatus should be a string, got %s", data)
	}

	var err error
	*i, err = MessagingStatusString(s)
	return err
}
