// Code generated by "enumer -type=PageStatus -json -transform=snake -trimprefix=PageStatus"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PageStatusName = "publishedunpublishedbanned"

var _PageStatusIndex = [...]uint8{0, 9, 20, 26}

const _PageStatusLowerName = "publishedunpublishedbanned"

func (i PageStatus) String() string {
	if i < 0 || i >= PageStatus(len(_PageStatusIndex)-1) {
		return fmt.Sprintf("PageStatus(%d)", i)
	}
	return _PageStatusName[_PageStatusIndex[i]:_PageStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PageStatusNoOp() {
	var x [1]struct{}
	_ = x[PageStatusPublished-(0)]
	_ = x[PageStatusUnpublished-(1)]
	_ = x[PageStatusBanned-(2)]
}

var _PageStatusValues = []PageStatus{PageStatusPublished, PageStatusUnpublished, PageStatusBanned}

var _PageStatusNameToValueMap = map[string]PageStatus{
	_PageStatusName[0:9]:        PageStatusPublished,
	_PageStatusLowerName[0:9]:   PageStatusPublished,
	_PageStatusName[9:20]:       PageStatusUnpublished,
	_PageStatusLowerName[9:20]:  PageStatusUnpublished,
	_PageStatusName[20:26]:      PageStatusBanned,
	_PageStatusLowerName[20:26]: PageStatusBanned,
}

var _PageStatusNames = []string{
	_PageStatusName[0:9],
	_PageStatusName[9:20],
	_PageStatusName[20:26],
}

// PageStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PageStatusString(s string) (PageStatus, error) {
	if val, ok := _PageStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PageStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PageStatus values", s)
}

// PageStatusValues returns all values of the enum
func PageStatusValues() []PageStatus {
	return _PageStatusValues
}

// PageStatusStrings returns a slice of all String values of the enum
func PageStatusStrings() []string {
	strs := make([]string, len(_PageStatusNames))
	copy(strs, _PageStatusNames)
	return strs
}

// IsAPageStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PageStatus) IsAPageStatus() bool {
	for _, v := range _PageStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PageStatus
func (i PageStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PageStatus
func (i *PageStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PageStatus should be a string, got %s", data)
	}

	var err error
	*i, err = PageStatusString(s)
	return err
}
