// Code generated by "enumer -type=PageRole -json -transform=snake -trimprefix=Role"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PageRoleName = "admineditormoderatoradvertiseranalyst"

var _PageRoleIndex = [...]uint8{0, 5, 11, 20, 30, 37}

const _PageRoleLowerName = "admineditormoderatoradvertiseranalyst"

func (i PageRole) String() string {
	if i < 0 || i >= PageRole(len(_PageRoleIndex)-1) {
		return fmt.Sprintf("PageRole(%d)", i)
	}
	return _PageRoleName[_PageRoleIndex[i]:_PageRoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PageRoleNoOp() {
	var x [1]struct{}
	_ = x[RoleAdmin-(0)]
	_ = x[RoleEditor-(1)]
	_ = x[RoleModerator-(2)]
	_ = x[RoleAdvertiser-(3)]
	_ = x[RoleAnalyst-(4)]
}

var _PageRoleValues = []PageRole{RoleAdmin, RoleEditor, RoleModerator, RoleAdvertiser, RoleAnalyst}

var _PageRoleNameToValueMap = map[string]PageRole{
	_PageRoleName[0:5]:        RoleAdmin,
	_PageRoleLowerName[0:5]:   RoleAdmin,
	_PageRoleName[5:11]:       RoleEditor,
	_PageRoleLowerName[5:11]:  RoleEditor,
	_PageRoleName[11:20]:      RoleModerator,
	_PageRoleLowerName[11:20]: RoleModerator,
	_PageRoleName[20:30]:      RoleAdvertiser,
	_PageRoleLowerName[20:30]: RoleAdvertiser,
	_PageRoleName[30:37]:      RoleAnalyst,
	_PageRoleLowerName[30:37]: RoleAnalyst,
}

var _PageRoleNames = []string{
	_PageRoleName[0:5],
	_PageRoleName[5:11],
	_PageRoleName[11:20],
	_PageRoleName[20:30],
	_PageRoleName[30:37],
}

// PageRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PageRoleString(s string) (PageRole, error) {
	if val, ok := _PageRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PageRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PageRole values", s)
}

// PageRoleValues returns all values of the enum
func PageRoleValues() []PageRole {
	return _PageRoleValues
}

// PageRoleStrings returns a slice of all String values of the enum
func PageRoleStrings() []string {
	strs := make([]string, len(_PageRoleNames))
	copy(strs, _PageRoleNames)
	return strs
}

// IsAPageRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PageRole) IsAPageRole() bool {
	for _, v := range _PageRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PageRole
func (i PageRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PageRole
func (i *PageRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PageRole should be a string, got %s", data)
	}

	var err error
	*i, err = PageRoleString(s)
	return err
}
