// Code generated by "enumer -type=ProfanityFilter -json -transform=snake -trimprefix=Profanity"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ProfanityFilterName = "offmediumstrong"

var _ProfanityFilterIndex = [...]uint8{0, 3, 9, 15}

const _ProfanityFilterLowerName = "offmediumstrong"

func (i ProfanityFilter) String() string {
	if i < 0 || i >= ProfanityFilter(len(_ProfanityFilterIndex)-1) {
		return fmt.Sprintf("ProfanityFilter(%d)", i)
	}
	return _ProfanityFilterName[_ProfanityFilterIndex[i]:_ProfanityFilterIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProfanityFilterNoOp() {
	var x [1]struct{}
	_ = x[ProfanityOff-(0)]
	_ = x[ProfanityMedium-(1)]
	_ = x[ProfanityStrong-(2)]
}

var _ProfanityFilterValues = []ProfanityFilter{ProfanityOff, ProfanityMedium, ProfanityStrong}

var _ProfanityFilterNameToValueMap = map[string]ProfanityFilter{
	_ProfanityFilterName[0:3]:       ProfanityOff,
	_ProfanityFilterLowerName[0:3]:  ProfanityOff,
	_ProfanityFilterName[3:9]:       ProfanityMedium,
	_ProfanityFilterLowerName[3:9]:  ProfanityMedium,
	_ProfanityFilterName[9:15]:      ProfanityStrong,
	_ProfanityFilterLowerName[9:15]: ProfanityStrong,
}

var _ProfanityFilterNames = []string{
	_ProfanityFilterName[0:3],
	_ProfanityFilterName[3:9],
	_ProfanityFilterName[9:15],
}

// ProfanityFilterString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProfanityFilterString(s string) (ProfanityFilter, error) {
	if val, ok := _ProfanityFilterNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProfanityFilterNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ProfanityFilter values", s)
}

// ProfanityFilterValues returns all values of the enum
func ProfanityFilterValues() []ProfanityFilter {
	return _ProfanityFilterValues
}

// ProfanityFilterStrings returns a slice of all String values of the enum
func ProfanityFilterStrings() []string {
	strs := make([]string, len(_ProfanityFilterNames))
	copy(strs, _ProfanityFilterNames)
	return strs
}

// IsAProfanityFilter returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProfanityFilter) IsAProfanityFilter() bool {
	for _, v := range _ProfanityFilterValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ProfanityFilter
func (i ProfanityFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ProfanityFilter
func (i *ProfanityFilter) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ProfanityFilter should be a string, got %s", data)
	}

	var err error
	*i, err = ProfanityFilterString(s)
	return err
}
