// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/common/configs"
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/common/database"
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/common/server/grpc"
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/common/shared/client"
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/modules/identity"
)

// Injectors from wire.go:

func InitializeApp(config *configs.Config) (*App, error) {
	engine := NewGinServer()
	mongodbConnection, err := database.NewMongodbConnection(config)
	if err != nil {
		return nil, err
	}
	redisConnection, err := database.NewRedisConnection(config)
	if err != nil {
		return nil, err
	}
	postgresConnection, err := database.NewPostgresConnection(config)
	if err != nil {
		return nil, err
	}
	elasticConnection, err := database.NewElasticConnection(config)
	if err != nil {
		return nil, err
	}
	cassandraConnection, err := database.NewCassandraConnection(config)
	if err != nil {
		return nil, err
	}
	neo4jConnection, err := database.NewNeo4jConnection(config)
	if err != nil {
		return nil, err
	}
	grpcServer := grpc.NewGRPCServer()
	mongoDatabase := client.ProvideMongoDatabase(mongodbConnection, config)
	db := client.ProvidePostgresGormDB(postgresConnection)
	moduleIdentity := identity.NewModuleIdentity(mongoDatabase, db)
	app := NewApp(engine, mongodbConnection, redisConnection, postgresConnection, elasticConnection, cassandraConnection, neo4jConnection, grpcServer, moduleIdentity)
	return app, nil
}
