// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/common/configs"
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/common/database"
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/common/server/grpc"
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/common/server/http"
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/modules/identity"
)

// Injectors from wire.go:

func InitializeApp(config *configs.Config) (*App, func(), error) {
	mongoDatabase, cleanup, err := database.NewMongoDatabase(config)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := database.NewPostgresDB(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	moduleIdentity := identity.NewModuleIdentity(mongoDatabase, db)
	engine := http.NewGinServer(moduleIdentity)
	grpcServer := grpc.NewGRPCServer()
	app := NewApp(engine, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
