// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/common/configs"
	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/common/database"
)

// Injectors from wire.go:

func InitializeApp(config *configs.Config) (*App, error) {
	engine := NewGinServer()
	db, err := database.ConnectPostgres(config)
	if err != nil {
		return nil, err
	}
	app := NewApp(engine, db)
	return app, nil
}
