// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID       string `json:"id"`
	Content  string `json:"content"`
	AuthorID string `json:"authorId"`
	Author   *User  `json:"author"`
}

type Query struct {
}

type User struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Avatar *string `json:"avatar,omitempty"`
}
