// Code generated by "enumer -type=ConversationStatus -json -transform=snake -trimprefix=Status"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ConversationStatusName = "activependingspamarchived"

var _ConversationStatusIndex = [...]uint8{0, 6, 13, 17, 25}

const _ConversationStatusLowerName = "activependingspamarchived"

func (i ConversationStatus) String() string {
	if i < 0 || i >= ConversationStatus(len(_ConversationStatusIndex)-1) {
		return fmt.Sprintf("ConversationStatus(%d)", i)
	}
	return _ConversationStatusName[_ConversationStatusIndex[i]:_ConversationStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ConversationStatusNoOp() {
	var x [1]struct{}
	_ = x[StatusActive-(0)]
	_ = x[StatusPending-(1)]
	_ = x[StatusSpam-(2)]
	_ = x[StatusArchived-(3)]
}

var _ConversationStatusValues = []ConversationStatus{StatusActive, StatusPending, StatusSpam, StatusArchived}

var _ConversationStatusNameToValueMap = map[string]ConversationStatus{
	_ConversationStatusName[0:6]:        StatusActive,
	_ConversationStatusLowerName[0:6]:   StatusActive,
	_ConversationStatusName[6:13]:       StatusPending,
	_ConversationStatusLowerName[6:13]:  StatusPending,
	_ConversationStatusName[13:17]:      StatusSpam,
	_ConversationStatusLowerName[13:17]: StatusSpam,
	_ConversationStatusName[17:25]:      StatusArchived,
	_ConversationStatusLowerName[17:25]: StatusArchived,
}

var _ConversationStatusNames = []string{
	_ConversationStatusName[0:6],
	_ConversationStatusName[6:13],
	_ConversationStatusName[13:17],
	_ConversationStatusName[17:25],
}

// ConversationStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ConversationStatusString(s string) (ConversationStatus, error) {
	if val, ok := _ConversationStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ConversationStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ConversationStatus values", s)
}

// ConversationStatusValues returns all values of the enum
func ConversationStatusValues() []ConversationStatus {
	return _ConversationStatusValues
}

// ConversationStatusStrings returns a slice of all String values of the enum
func ConversationStatusStrings() []string {
	strs := make([]string, len(_ConversationStatusNames))
	copy(strs, _ConversationStatusNames)
	return strs
}

// IsAConversationStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ConversationStatus) IsAConversationStatus() bool {
	for _, v := range _ConversationStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ConversationStatus
func (i ConversationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ConversationStatus
func (i *ConversationStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ConversationStatus should be a string, got %s", data)
	}

	var err error
	*i, err = ConversationStatusString(s)
	return err
}
