// Code generated by "enumer -type=ConversationType -json -transform=snake -trimprefix=Type"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ConversationTypeName = "privategroup"

var _ConversationTypeIndex = [...]uint8{0, 7, 12}

const _ConversationTypeLowerName = "privategroup"

func (i ConversationType) String() string {
	if i < 0 || i >= ConversationType(len(_ConversationTypeIndex)-1) {
		return fmt.Sprintf("ConversationType(%d)", i)
	}
	return _ConversationTypeName[_ConversationTypeIndex[i]:_ConversationTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ConversationTypeNoOp() {
	var x [1]struct{}
	_ = x[TypePrivate-(0)]
	_ = x[TypeGroup-(1)]
}

var _ConversationTypeValues = []ConversationType{TypePrivate, TypeGroup}

var _ConversationTypeNameToValueMap = map[string]ConversationType{
	_ConversationTypeName[0:7]:       TypePrivate,
	_ConversationTypeLowerName[0:7]:  TypePrivate,
	_ConversationTypeName[7:12]:      TypeGroup,
	_ConversationTypeLowerName[7:12]: TypeGroup,
}

var _ConversationTypeNames = []string{
	_ConversationTypeName[0:7],
	_ConversationTypeName[7:12],
}

// ConversationTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ConversationTypeString(s string) (ConversationType, error) {
	if val, ok := _ConversationTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ConversationTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ConversationType values", s)
}

// ConversationTypeValues returns all values of the enum
func ConversationTypeValues() []ConversationType {
	return _ConversationTypeValues
}

// ConversationTypeStrings returns a slice of all String values of the enum
func ConversationTypeStrings() []string {
	strs := make([]string, len(_ConversationTypeNames))
	copy(strs, _ConversationTypeNames)
	return strs
}

// IsAConversationType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ConversationType) IsAConversationType() bool {
	for _, v := range _ConversationTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ConversationType
func (i ConversationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ConversationType
func (i *ConversationType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ConversationType should be a string, got %s", data)
	}

	var err error
	*i, err = ConversationTypeString(s)
	return err
}
