// Code generated by "enumer -type=MessageType -json -transform=snake -trimprefix=Msg"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MessageTypeName = "textimagevideoaudiofilelocationstory_replysticker"

var _MessageTypeIndex = [...]uint8{0, 4, 9, 14, 19, 23, 31, 42, 49}

const _MessageTypeLowerName = "textimagevideoaudiofilelocationstory_replysticker"

func (i MessageType) String() string {
	if i < 0 || i >= MessageType(len(_MessageTypeIndex)-1) {
		return fmt.Sprintf("MessageType(%d)", i)
	}
	return _MessageTypeName[_MessageTypeIndex[i]:_MessageTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MessageTypeNoOp() {
	var x [1]struct{}
	_ = x[MsgText-(0)]
	_ = x[MsgImage-(1)]
	_ = x[MsgVideo-(2)]
	_ = x[MsgAudio-(3)]
	_ = x[MsgFile-(4)]
	_ = x[MsgLocation-(5)]
	_ = x[MsgStoryReply-(6)]
	_ = x[MsgSticker-(7)]
}

var _MessageTypeValues = []MessageType{MsgText, MsgImage, MsgVideo, MsgAudio, MsgFile, MsgLocation, MsgStoryReply, MsgSticker}

var _MessageTypeNameToValueMap = map[string]MessageType{
	_MessageTypeName[0:4]:        MsgText,
	_MessageTypeLowerName[0:4]:   MsgText,
	_MessageTypeName[4:9]:        MsgImage,
	_MessageTypeLowerName[4:9]:   MsgImage,
	_MessageTypeName[9:14]:       MsgVideo,
	_MessageTypeLowerName[9:14]:  MsgVideo,
	_MessageTypeName[14:19]:      MsgAudio,
	_MessageTypeLowerName[14:19]: MsgAudio,
	_MessageTypeName[19:23]:      MsgFile,
	_MessageTypeLowerName[19:23]: MsgFile,
	_MessageTypeName[23:31]:      MsgLocation,
	_MessageTypeLowerName[23:31]: MsgLocation,
	_MessageTypeName[31:42]:      MsgStoryReply,
	_MessageTypeLowerName[31:42]: MsgStoryReply,
	_MessageTypeName[42:49]:      MsgSticker,
	_MessageTypeLowerName[42:49]: MsgSticker,
}

var _MessageTypeNames = []string{
	_MessageTypeName[0:4],
	_MessageTypeName[4:9],
	_MessageTypeName[9:14],
	_MessageTypeName[14:19],
	_MessageTypeName[19:23],
	_MessageTypeName[23:31],
	_MessageTypeName[31:42],
	_MessageTypeName[42:49],
}

// MessageTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MessageTypeString(s string) (MessageType, error) {
	if val, ok := _MessageTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MessageTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MessageType values", s)
}

// MessageTypeValues returns all values of the enum
func MessageTypeValues() []MessageType {
	return _MessageTypeValues
}

// MessageTypeStrings returns a slice of all String values of the enum
func MessageTypeStrings() []string {
	strs := make([]string, len(_MessageTypeNames))
	copy(strs, _MessageTypeNames)
	return strs
}

// IsAMessageType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MessageType) IsAMessageType() bool {
	for _, v := range _MessageTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MessageType
func (i MessageType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MessageType
func (i *MessageType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MessageType should be a string, got %s", data)
	}

	var err error
	*i, err = MessageTypeString(s)
	return err
}
