// Code generated by "enumer -type=MessageReactionCode -json -transform=snake -trimprefix=Reaction"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MessageReactionCodeName = "hearthahasadwowangrylikedislike"

var _MessageReactionCodeIndex = [...]uint8{0, 5, 9, 12, 15, 20, 24, 31}

const _MessageReactionCodeLowerName = "hearthahasadwowangrylikedislike"

func (i MessageReactionCode) String() string {
	if i < 0 || i >= MessageReactionCode(len(_MessageReactionCodeIndex)-1) {
		return fmt.Sprintf("MessageReactionCode(%d)", i)
	}
	return _MessageReactionCodeName[_MessageReactionCodeIndex[i]:_MessageReactionCodeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MessageReactionCodeNoOp() {
	var x [1]struct{}
	_ = x[ReactionHeart-(0)]
	_ = x[ReactionHaha-(1)]
	_ = x[ReactionSad-(2)]
	_ = x[ReactionWow-(3)]
	_ = x[ReactionAngry-(4)]
	_ = x[ReactionLike-(5)]
	_ = x[ReactionDislike-(6)]
}

var _MessageReactionCodeValues = []MessageReactionCode{ReactionHeart, ReactionHaha, ReactionSad, ReactionWow, ReactionAngry, ReactionLike, ReactionDislike}

var _MessageReactionCodeNameToValueMap = map[string]MessageReactionCode{
	_MessageReactionCodeName[0:5]:        ReactionHeart,
	_MessageReactionCodeLowerName[0:5]:   ReactionHeart,
	_MessageReactionCodeName[5:9]:        ReactionHaha,
	_MessageReactionCodeLowerName[5:9]:   ReactionHaha,
	_MessageReactionCodeName[9:12]:       ReactionSad,
	_MessageReactionCodeLowerName[9:12]:  ReactionSad,
	_MessageReactionCodeName[12:15]:      ReactionWow,
	_MessageReactionCodeLowerName[12:15]: ReactionWow,
	_MessageReactionCodeName[15:20]:      ReactionAngry,
	_MessageReactionCodeLowerName[15:20]: ReactionAngry,
	_MessageReactionCodeName[20:24]:      ReactionLike,
	_MessageReactionCodeLowerName[20:24]: ReactionLike,
	_MessageReactionCodeName[24:31]:      ReactionDislike,
	_MessageReactionCodeLowerName[24:31]: ReactionDislike,
}

var _MessageReactionCodeNames = []string{
	_MessageReactionCodeName[0:5],
	_MessageReactionCodeName[5:9],
	_MessageReactionCodeName[9:12],
	_MessageReactionCodeName[12:15],
	_MessageReactionCodeName[15:20],
	_MessageReactionCodeName[20:24],
	_MessageReactionCodeName[24:31],
}

// MessageReactionCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MessageReactionCodeString(s string) (MessageReactionCode, error) {
	if val, ok := _MessageReactionCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MessageReactionCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MessageReactionCode values", s)
}

// MessageReactionCodeValues returns all values of the enum
func MessageReactionCodeValues() []MessageReactionCode {
	return _MessageReactionCodeValues
}

// MessageReactionCodeStrings returns a slice of all String values of the enum
func MessageReactionCodeStrings() []string {
	strs := make([]string, len(_MessageReactionCodeNames))
	copy(strs, _MessageReactionCodeNames)
	return strs
}

// IsAMessageReactionCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MessageReactionCode) IsAMessageReactionCode() bool {
	for _, v := range _MessageReactionCodeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MessageReactionCode
func (i MessageReactionCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MessageReactionCode
func (i *MessageReactionCode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MessageReactionCode should be a string, got %s", data)
	}

	var err error
	*i, err = MessageReactionCodeString(s)
	return err
}
