// Code generated by "enumer -type=ParticipantRole -json -transform=snake -trimprefix=Role"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ParticipantRoleName = "memberadminmoderator"

var _ParticipantRoleIndex = [...]uint8{0, 6, 11, 20}

const _ParticipantRoleLowerName = "memberadminmoderator"

func (i ParticipantRole) String() string {
	if i < 0 || i >= ParticipantRole(len(_ParticipantRoleIndex)-1) {
		return fmt.Sprintf("ParticipantRole(%d)", i)
	}
	return _ParticipantRoleName[_ParticipantRoleIndex[i]:_ParticipantRoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ParticipantRoleNoOp() {
	var x [1]struct{}
	_ = x[RoleMember-(0)]
	_ = x[RoleAdmin-(1)]
	_ = x[RoleModerator-(2)]
}

var _ParticipantRoleValues = []ParticipantRole{RoleMember, RoleAdmin, RoleModerator}

var _ParticipantRoleNameToValueMap = map[string]ParticipantRole{
	_ParticipantRoleName[0:6]:        RoleMember,
	_ParticipantRoleLowerName[0:6]:   RoleMember,
	_ParticipantRoleName[6:11]:       RoleAdmin,
	_ParticipantRoleLowerName[6:11]:  RoleAdmin,
	_ParticipantRoleName[11:20]:      RoleModerator,
	_ParticipantRoleLowerName[11:20]: RoleModerator,
}

var _ParticipantRoleNames = []string{
	_ParticipantRoleName[0:6],
	_ParticipantRoleName[6:11],
	_ParticipantRoleName[11:20],
}

// ParticipantRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParticipantRoleString(s string) (ParticipantRole, error) {
	if val, ok := _ParticipantRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ParticipantRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ParticipantRole values", s)
}

// ParticipantRoleValues returns all values of the enum
func ParticipantRoleValues() []ParticipantRole {
	return _ParticipantRoleValues
}

// ParticipantRoleStrings returns a slice of all String values of the enum
func ParticipantRoleStrings() []string {
	strs := make([]string, len(_ParticipantRoleNames))
	copy(strs, _ParticipantRoleNames)
	return strs
}

// IsAParticipantRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ParticipantRole) IsAParticipantRole() bool {
	for _, v := range _ParticipantRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ParticipantRole
func (i ParticipantRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ParticipantRole
func (i *ParticipantRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ParticipantRole should be a string, got %s", data)
	}

	var err error
	*i, err = ParticipantRoleString(s)
	return err
}
