// Code generated by "enumer -type=PermissionLevel -json -transform=snake -trimprefix=Perm"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PermissionLevelName = "everyoneadmin_only"

var _PermissionLevelIndex = [...]uint8{0, 8, 18}

const _PermissionLevelLowerName = "everyoneadmin_only"

func (i PermissionLevel) String() string {
	if i < 0 || i >= PermissionLevel(len(_PermissionLevelIndex)-1) {
		return fmt.Sprintf("PermissionLevel(%d)", i)
	}
	return _PermissionLevelName[_PermissionLevelIndex[i]:_PermissionLevelIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PermissionLevelNoOp() {
	var x [1]struct{}
	_ = x[PermEveryone-(0)]
	_ = x[PermAdminOnly-(1)]
}

var _PermissionLevelValues = []PermissionLevel{PermEveryone, PermAdminOnly}

var _PermissionLevelNameToValueMap = map[string]PermissionLevel{
	_PermissionLevelName[0:8]:       PermEveryone,
	_PermissionLevelLowerName[0:8]:  PermEveryone,
	_PermissionLevelName[8:18]:      PermAdminOnly,
	_PermissionLevelLowerName[8:18]: PermAdminOnly,
}

var _PermissionLevelNames = []string{
	_PermissionLevelName[0:8],
	_PermissionLevelName[8:18],
}

// PermissionLevelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PermissionLevelString(s string) (PermissionLevel, error) {
	if val, ok := _PermissionLevelNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PermissionLevelNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PermissionLevel values", s)
}

// PermissionLevelValues returns all values of the enum
func PermissionLevelValues() []PermissionLevel {
	return _PermissionLevelValues
}

// PermissionLevelStrings returns a slice of all String values of the enum
func PermissionLevelStrings() []string {
	strs := make([]string, len(_PermissionLevelNames))
	copy(strs, _PermissionLevelNames)
	return strs
}

// IsAPermissionLevel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PermissionLevel) IsAPermissionLevel() bool {
	for _, v := range _PermissionLevelValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PermissionLevel
func (i PermissionLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PermissionLevel
func (i *PermissionLevel) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PermissionLevel should be a string, got %s", data)
	}

	var err error
	*i, err = PermissionLevelString(s)
	return err
}
