// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/business.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoleUserInPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleUserInPageRequest) Reset() {
	*x = GetRoleUserInPageRequest{}
	mi := &file_v1_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleUserInPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleUserInPageRequest) ProtoMessage() {}

func (x *GetRoleUserInPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleUserInPageRequest.ProtoReflect.Descriptor instead.
func (*GetRoleUserInPageRequest) Descriptor() ([]byte, []int) {
	return file_v1_business_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoleUserInPageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *GetRoleUserInPageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRoleUserInPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          []string               `protobuf:"bytes,1,rep,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleUserInPageResponse) Reset() {
	*x = GetRoleUserInPageResponse{}
	mi := &file_v1_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleUserInPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleUserInPageResponse) ProtoMessage() {}

func (x *GetRoleUserInPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleUserInPageResponse.ProtoReflect.Descriptor instead.
func (*GetRoleUserInPageResponse) Descriptor() ([]byte, []int) {
	return file_v1_business_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoleUserInPageResponse) GetRole() []string {
	if x != nil {
		return x.Role
	}
	return nil
}

var File_v1_business_proto protoreflect.FileDescriptor

const file_v1_business_proto_rawDesc = "" +
	"\n" +
	"\x11v1/business.proto\x12\fapi.proto.v1\"L\n" +
	"\x18GetRoleUserInPageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x19GetRoleUserInPageResponse\x12\x12\n" +
	"\x04role\x18\x01 \x03(\tR\x04role2w\n" +
	"\x0fBusinessService\x12d\n" +
	"\x11GetRoleUserInPage\x12&.api.proto.v1.GetRoleUserInPageRequest\x1a'.api.proto.v1.GetRoleUserInPageResponseB.Z,github.com/quang/social-network/pkg/pb/v1;pbb\x06proto3"

var (
	file_v1_business_proto_rawDescOnce sync.Once
	file_v1_business_proto_rawDescData []byte
)

func file_v1_business_proto_rawDescGZIP() []byte {
	file_v1_business_proto_rawDescOnce.Do(func() {
		file_v1_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_business_proto_rawDesc), len(file_v1_business_proto_rawDesc)))
	})
	return file_v1_business_proto_rawDescData
}

var file_v1_business_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_business_proto_goTypes = []any{
	(*GetRoleUserInPageRequest)(nil),  // 0: api.proto.v1.GetRoleUserInPageRequest
	(*GetRoleUserInPageResponse)(nil), // 1: api.proto.v1.GetRoleUserInPageResponse
}
var file_v1_business_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.BusinessService.GetRoleUserInPage:input_type -> api.proto.v1.GetRoleUserInPageRequest
	1, // 1: api.proto.v1.BusinessService.GetRoleUserInPage:output_type -> api.proto.v1.GetRoleUserInPageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_business_proto_init() }
func file_v1_business_proto_init() {
	if File_v1_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_business_proto_rawDesc), len(file_v1_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_business_proto_goTypes,
		DependencyIndexes: file_v1_business_proto_depIdxs,
		MessageInfos:      file_v1_business_proto_msgTypes,
	}.Build()
	File_v1_business_proto = out.File
	file_v1_business_proto_goTypes = nil
	file_v1_business_proto_depIdxs = nil
}
