// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/community.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoleUserInGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleUserInGroupRequest) Reset() {
	*x = GetRoleUserInGroupRequest{}
	mi := &file_v1_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleUserInGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleUserInGroupRequest) ProtoMessage() {}

func (x *GetRoleUserInGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleUserInGroupRequest.ProtoReflect.Descriptor instead.
func (*GetRoleUserInGroupRequest) Descriptor() ([]byte, []int) {
	return file_v1_community_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoleUserInGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetRoleUserInGroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRoleUserInGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          []string               `protobuf:"bytes,1,rep,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleUserInGroupResponse) Reset() {
	*x = GetRoleUserInGroupResponse{}
	mi := &file_v1_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleUserInGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleUserInGroupResponse) ProtoMessage() {}

func (x *GetRoleUserInGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleUserInGroupResponse.ProtoReflect.Descriptor instead.
func (*GetRoleUserInGroupResponse) Descriptor() ([]byte, []int) {
	return file_v1_community_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoleUserInGroupResponse) GetRole() []string {
	if x != nil {
		return x.Role
	}
	return nil
}

var File_v1_community_proto protoreflect.FileDescriptor

const file_v1_community_proto_rawDesc = "" +
	"\n" +
	"\x12v1/community.proto\x12\fapi.proto.v1\"O\n" +
	"\x19GetRoleUserInGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"0\n" +
	"\x1aGetRoleUserInGroupResponse\x12\x12\n" +
	"\x04role\x18\x01 \x03(\tR\x04role2{\n" +
	"\x10CommunityService\x12g\n" +
	"\x12GetRoleUserInGroup\x12'.api.proto.v1.GetRoleUserInGroupRequest\x1a(.api.proto.v1.GetRoleUserInGroupResponseB.Z,github.com/quang/social-network/pkg/pb/v1;pbb\x06proto3"

var (
	file_v1_community_proto_rawDescOnce sync.Once
	file_v1_community_proto_rawDescData []byte
)

func file_v1_community_proto_rawDescGZIP() []byte {
	file_v1_community_proto_rawDescOnce.Do(func() {
		file_v1_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_community_proto_rawDesc), len(file_v1_community_proto_rawDesc)))
	})
	return file_v1_community_proto_rawDescData
}

var file_v1_community_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_community_proto_goTypes = []any{
	(*GetRoleUserInGroupRequest)(nil),  // 0: api.proto.v1.GetRoleUserInGroupRequest
	(*GetRoleUserInGroupResponse)(nil), // 1: api.proto.v1.GetRoleUserInGroupResponse
}
var file_v1_community_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.CommunityService.GetRoleUserInGroup:input_type -> api.proto.v1.GetRoleUserInGroupRequest
	1, // 1: api.proto.v1.CommunityService.GetRoleUserInGroup:output_type -> api.proto.v1.GetRoleUserInGroupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_community_proto_init() }
func file_v1_community_proto_init() {
	if File_v1_community_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_community_proto_rawDesc), len(file_v1_community_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_community_proto_goTypes,
		DependencyIndexes: file_v1_community_proto_depIdxs,
		MessageInfos:      file_v1_community_proto_msgTypes,
	}.Build()
	File_v1_community_proto = out.File
	file_v1_community_proto_goTypes = nil
	file_v1_community_proto_depIdxs = nil
}
