// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/content.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOwnerPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOwnerPostRequest) Reset() {
	*x = GetOwnerPostRequest{}
	mi := &file_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOwnerPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnerPostRequest) ProtoMessage() {}

func (x *GetOwnerPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnerPostRequest.ProtoReflect.Descriptor instead.
func (*GetOwnerPostRequest) Descriptor() ([]byte, []int) {
	return file_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *GetOwnerPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetOwnerPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOwnerPostResponse) Reset() {
	*x = GetOwnerPostResponse{}
	mi := &file_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOwnerPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnerPostResponse) ProtoMessage() {}

func (x *GetOwnerPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnerPostResponse.ProtoReflect.Descriptor instead.
func (*GetOwnerPostResponse) Descriptor() ([]byte, []int) {
	return file_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *GetOwnerPostResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

var File_v1_content_proto protoreflect.FileDescriptor

const file_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x10v1/content.proto\x12\fapi.proto.v1\".\n" +
	"\x13GetOwnerPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"1\n" +
	"\x14GetOwnerPostResponse\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId2g\n" +
	"\x0eContentService\x12U\n" +
	"\fGetOwnerPost\x12!.api.proto.v1.GetOwnerPostRequest\x1a\".api.proto.v1.GetOwnerPostResponseB.Z,github.com/quang/social-network/pkg/pb/v1;pbb\x06proto3"

var (
	file_v1_content_proto_rawDescOnce sync.Once
	file_v1_content_proto_rawDescData []byte
)

func file_v1_content_proto_rawDescGZIP() []byte {
	file_v1_content_proto_rawDescOnce.Do(func() {
		file_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_content_proto_rawDesc), len(file_v1_content_proto_rawDesc)))
	})
	return file_v1_content_proto_rawDescData
}

var file_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_content_proto_goTypes = []any{
	(*GetOwnerPostRequest)(nil),  // 0: api.proto.v1.GetOwnerPostRequest
	(*GetOwnerPostResponse)(nil), // 1: api.proto.v1.GetOwnerPostResponse
}
var file_v1_content_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.ContentService.GetOwnerPost:input_type -> api.proto.v1.GetOwnerPostRequest
	1, // 1: api.proto.v1.ContentService.GetOwnerPost:output_type -> api.proto.v1.GetOwnerPostResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_content_proto_init() }
func file_v1_content_proto_init() {
	if File_v1_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_content_proto_rawDesc), len(file_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_content_proto_goTypes,
		DependencyIndexes: file_v1_content_proto_depIdxs,
		MessageInfos:      file_v1_content_proto_msgTypes,
	}.Build()
	File_v1_content_proto = out.File
	file_v1_content_proto_goTypes = nil
	file_v1_content_proto_depIdxs = nil
}
