// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: v1/identity.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_GetUserOTP_FullMethodName           = "/api.proto.v1.IdentityService/GetUserOTP"
	IdentityService_GetUserSettingByID_FullMethodName   = "/api.proto.v1.IdentityService/GetUserSettingByID"
	IdentityService_CheckUSERIDExistence_FullMethodName = "/api.proto.v1.IdentityService/CheckUSERIDExistence"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityServiceClient interface {
	GetUserOTP(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserIDResponse, error)
	GetUserSettingByID(ctx context.Context, in *UserSettingIDRequest, opts ...grpc.CallOption) (*UserSettingResponse, error)
	CheckUSERIDExistence(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*UserIDExistenceResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) GetUserOTP(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserIDResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUserOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUserSettingByID(ctx context.Context, in *UserSettingIDRequest, opts ...grpc.CallOption) (*UserSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSettingResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUserSettingByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) CheckUSERIDExistence(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*UserIDExistenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserIDExistenceResponse)
	err := c.cc.Invoke(ctx, IdentityService_CheckUSERIDExistence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
type IdentityServiceServer interface {
	GetUserOTP(context.Context, *emptypb.Empty) (*UserIDResponse, error)
	GetUserSettingByID(context.Context, *UserSettingIDRequest) (*UserSettingResponse, error)
	CheckUSERIDExistence(context.Context, *UserIDRequest) (*UserIDExistenceResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) GetUserOTP(context.Context, *emptypb.Empty) (*UserIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserOTP not implemented")
}
func (UnimplementedIdentityServiceServer) GetUserSettingByID(context.Context, *UserSettingIDRequest) (*UserSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSettingByID not implemented")
}
func (UnimplementedIdentityServiceServer) CheckUSERIDExistence(context.Context, *UserIDRequest) (*UserIDExistenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUSERIDExistence not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_GetUserOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserOTP(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUserSettingByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSettingIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserSettingByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserSettingByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserSettingByID(ctx, req.(*UserSettingIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_CheckUSERIDExistence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).CheckUSERIDExistence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_CheckUSERIDExistence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).CheckUSERIDExistence(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserOTP",
			Handler:    _IdentityService_GetUserOTP_Handler,
		},
		{
			MethodName: "GetUserSettingByID",
			Handler:    _IdentityService_GetUserSettingByID_Handler,
		},
		{
			MethodName: "CheckUSERIDExistence",
			Handler:    _IdentityService_CheckUSERIDExistence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/identity.proto",
}
