// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/identity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDResponse) Reset() {
	*x = UserIDResponse{}
	mi := &file_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDResponse) ProtoMessage() {}

func (x *UserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDResponse.ProtoReflect.Descriptor instead.
func (*UserIDResponse) Descriptor() ([]byte, []int) {
	return file_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *UserIDResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_v1_identity_proto protoreflect.FileDescriptor

const file_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x11v1/identity.proto\x12\fapi.proto.v1\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\x0eUserIDResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2U\n" +
	"\x0fIdentityService\x12B\n" +
	"\n" +
	"GetUserOTP\x12\x16.google.protobuf.Empty\x1a\x1c.api.proto.v1.UserIDResponseB.Z,github.com/quang/social-network/pkg/pb/v1;pbb\x06proto3"

var (
	file_v1_identity_proto_rawDescOnce sync.Once
	file_v1_identity_proto_rawDescData []byte
)

func file_v1_identity_proto_rawDescGZIP() []byte {
	file_v1_identity_proto_rawDescOnce.Do(func() {
		file_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_identity_proto_rawDesc), len(file_v1_identity_proto_rawDesc)))
	})
	return file_v1_identity_proto_rawDescData
}

var file_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_identity_proto_goTypes = []any{
	(*UserIDResponse)(nil), // 0: api.proto.v1.UserIDResponse
	(*emptypb.Empty)(nil),  // 1: google.protobuf.Empty
}
var file_v1_identity_proto_depIdxs = []int32{
	1, // 0: api.proto.v1.IdentityService.GetUserOTP:input_type -> google.protobuf.Empty
	0, // 1: api.proto.v1.IdentityService.GetUserOTP:output_type -> api.proto.v1.UserIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_identity_proto_init() }
func file_v1_identity_proto_init() {
	if File_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_identity_proto_rawDesc), len(file_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_identity_proto_goTypes,
		DependencyIndexes: file_v1_identity_proto_depIdxs,
		MessageInfos:      file_v1_identity_proto_msgTypes,
	}.Build()
	File_v1_identity_proto = out.File
	file_v1_identity_proto_goTypes = nil
	file_v1_identity_proto_depIdxs = nil
}
