// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/media.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserIDbyStoryIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDbyStoryIDRequest) Reset() {
	*x = GetUserIDbyStoryIDRequest{}
	mi := &file_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDbyStoryIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDbyStoryIDRequest) ProtoMessage() {}

func (x *GetUserIDbyStoryIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDbyStoryIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserIDbyStoryIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserIDbyStoryIDRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

type GetUserIDbyStoryIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDbyStoryIDResponse) Reset() {
	*x = GetUserIDbyStoryIDResponse{}
	mi := &file_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDbyStoryIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDbyStoryIDResponse) ProtoMessage() {}

func (x *GetUserIDbyStoryIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDbyStoryIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserIDbyStoryIDResponse) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserIDbyStoryIDResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_v1_media_proto protoreflect.FileDescriptor

const file_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/media.proto\x12\fapi.proto.v1\"6\n" +
	"\x19GetUserIDbyStoryIDRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\"5\n" +
	"\x1aGetUserIDbyStoryIDResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2w\n" +
	"\fMediaService\x12g\n" +
	"\x12GetUserIDbyStoryID\x12'.api.proto.v1.GetUserIDbyStoryIDRequest\x1a(.api.proto.v1.GetUserIDbyStoryIDResponseB.Z,github.com/quang/social-network/pkg/pb/v1;pbb\x06proto3"

var (
	file_v1_media_proto_rawDescOnce sync.Once
	file_v1_media_proto_rawDescData []byte
)

func file_v1_media_proto_rawDescGZIP() []byte {
	file_v1_media_proto_rawDescOnce.Do(func() {
		file_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_media_proto_rawDesc), len(file_v1_media_proto_rawDesc)))
	})
	return file_v1_media_proto_rawDescData
}

var file_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_media_proto_goTypes = []any{
	(*GetUserIDbyStoryIDRequest)(nil),  // 0: api.proto.v1.GetUserIDbyStoryIDRequest
	(*GetUserIDbyStoryIDResponse)(nil), // 1: api.proto.v1.GetUserIDbyStoryIDResponse
}
var file_v1_media_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.MediaService.GetUserIDbyStoryID:input_type -> api.proto.v1.GetUserIDbyStoryIDRequest
	1, // 1: api.proto.v1.MediaService.GetUserIDbyStoryID:output_type -> api.proto.v1.GetUserIDbyStoryIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_media_proto_init() }
func file_v1_media_proto_init() {
	if File_v1_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_media_proto_rawDesc), len(file_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_media_proto_goTypes,
		DependencyIndexes: file_v1_media_proto_depIdxs,
		MessageInfos:      file_v1_media_proto_msgTypes,
	}.Build()
	File_v1_media_proto = out.File
	file_v1_media_proto_goTypes = nil
	file_v1_media_proto_depIdxs = nil
}
