// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/social.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserblockIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserId2       string                 `protobuf:"bytes,2,opt,name=user_id2,json=userId2,proto3" json:"user_id2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserblockIDRequest) Reset() {
	*x = UserblockIDRequest{}
	mi := &file_v1_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserblockIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserblockIDRequest) ProtoMessage() {}

func (x *UserblockIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserblockIDRequest.ProtoReflect.Descriptor instead.
func (*UserblockIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_social_proto_rawDescGZIP(), []int{0}
}

func (x *UserblockIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserblockIDRequest) GetUserId2() string {
	if x != nil {
		return x.UserId2
	}
	return ""
}

type UserblockIDRequestv2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserblockIDRequestv2) Reset() {
	*x = UserblockIDRequestv2{}
	mi := &file_v1_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserblockIDRequestv2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserblockIDRequestv2) ProtoMessage() {}

func (x *UserblockIDRequestv2) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserblockIDRequestv2.ProtoReflect.Descriptor instead.
func (*UserblockIDRequestv2) Descriptor() ([]byte, []int) {
	return file_v1_social_proto_rawDescGZIP(), []int{1}
}

func (x *UserblockIDRequestv2) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListBlockByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Typeblock     []string               `protobuf:"bytes,1,rep,name=typeblock,proto3" json:"typeblock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockByUserIDResponse) Reset() {
	*x = ListBlockByUserIDResponse{}
	mi := &file_v1_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockByUserIDResponse) ProtoMessage() {}

func (x *ListBlockByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockByUserIDResponse.ProtoReflect.Descriptor instead.
func (*ListBlockByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_v1_social_proto_rawDescGZIP(), []int{2}
}

func (x *ListBlockByUserIDResponse) GetTypeblock() []string {
	if x != nil {
		return x.Typeblock
	}
	return nil
}

type UserSocialIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSocialIDRequest) Reset() {
	*x = UserSocialIDRequest{}
	mi := &file_v1_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSocialIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSocialIDRequest) ProtoMessage() {}

func (x *UserSocialIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSocialIDRequest.ProtoReflect.Descriptor instead.
func (*UserSocialIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_social_proto_rawDescGZIP(), []int{3}
}

func (x *UserSocialIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type InfoUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthorName    string                 `protobuf:"bytes,2,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`
	AuthorAvatar  string                 `protobuf:"bytes,3,opt,name=AuthorAvatar,proto3" json:"AuthorAvatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoUserByIDResponse) Reset() {
	*x = InfoUserByIDResponse{}
	mi := &file_v1_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoUserByIDResponse) ProtoMessage() {}

func (x *InfoUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoUserByIDResponse.ProtoReflect.Descriptor instead.
func (*InfoUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_v1_social_proto_rawDescGZIP(), []int{4}
}

func (x *InfoUserByIDResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InfoUserByIDResponse) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *InfoUserByIDResponse) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

var File_v1_social_proto protoreflect.FileDescriptor

const file_v1_social_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/social.proto\x12\fapi.proto.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x12UserblockIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_id2\x18\x02 \x01(\tR\auserId2\"/\n" +
	"\x14UserblockIDRequestv2\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"9\n" +
	"\x19ListBlockByUserIDResponse\x12\x1c\n" +
	"\ttypeblock\x18\x01 \x03(\tR\ttypeblock\".\n" +
	"\x13UserSocialIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"s\n" +
	"\x14InfoUserByIDResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"AuthorName\x18\x02 \x01(\tR\n" +
	"AuthorName\x12\"\n" +
	"\fAuthorAvatar\x18\x03 \x01(\tR\fAuthorAvatar2\xb3\x02\n" +
	"\rSocialService\x12a\n" +
	"\x14GetListBlockByUserID\x12 .api.proto.v1.UserblockIDRequest\x1a'.api.proto.v1.ListBlockByUserIDResponse\x12e\n" +
	"\x16GetListBlockByUserIDV2\x12\".api.proto.v1.UserblockIDRequestv2\x1a'.api.proto.v1.ListBlockByUserIDResponse\x12X\n" +
	"\x0fGetInfoUserByID\x12!.api.proto.v1.UserSocialIDRequest\x1a\".api.proto.v1.InfoUserByIDResponseB.Z,github.com/quang/social-network/pkg/pb/v1;pbb\x06proto3"

var (
	file_v1_social_proto_rawDescOnce sync.Once
	file_v1_social_proto_rawDescData []byte
)

func file_v1_social_proto_rawDescGZIP() []byte {
	file_v1_social_proto_rawDescOnce.Do(func() {
		file_v1_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_social_proto_rawDesc), len(file_v1_social_proto_rawDesc)))
	})
	return file_v1_social_proto_rawDescData
}

var file_v1_social_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_social_proto_goTypes = []any{
	(*UserblockIDRequest)(nil),        // 0: api.proto.v1.UserblockIDRequest
	(*UserblockIDRequestv2)(nil),      // 1: api.proto.v1.UserblockIDRequestv2
	(*ListBlockByUserIDResponse)(nil), // 2: api.proto.v1.ListBlockByUserIDResponse
	(*UserSocialIDRequest)(nil),       // 3: api.proto.v1.UserSocialIDRequest
	(*InfoUserByIDResponse)(nil),      // 4: api.proto.v1.InfoUserByIDResponse
}
var file_v1_social_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.SocialService.GetListBlockByUserID:input_type -> api.proto.v1.UserblockIDRequest
	1, // 1: api.proto.v1.SocialService.GetListBlockByUserIDV2:input_type -> api.proto.v1.UserblockIDRequestv2
	3, // 2: api.proto.v1.SocialService.GetInfoUserByID:input_type -> api.proto.v1.UserSocialIDRequest
	2, // 3: api.proto.v1.SocialService.GetListBlockByUserID:output_type -> api.proto.v1.ListBlockByUserIDResponse
	2, // 4: api.proto.v1.SocialService.GetListBlockByUserIDV2:output_type -> api.proto.v1.ListBlockByUserIDResponse
	4, // 5: api.proto.v1.SocialService.GetInfoUserByID:output_type -> api.proto.v1.InfoUserByIDResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_social_proto_init() }
func file_v1_social_proto_init() {
	if File_v1_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_social_proto_rawDesc), len(file_v1_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_social_proto_goTypes,
		DependencyIndexes: file_v1_social_proto_depIdxs,
		MessageInfos:      file_v1_social_proto_msgTypes,
	}.Build()
	File_v1_social_proto = out.File
	file_v1_social_proto_goTypes = nil
	file_v1_social_proto_depIdxs = nil
}
