// Code generated by "enumer -type=Is_Muted -json -sql -transform=snake -trimprefix=Is_Muted"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _Is_MutedName = "noyes"

var _Is_MutedIndex = [...]uint8{0, 2, 5}

const _Is_MutedLowerName = "noyes"

func (i Is_Muted) String() string {
	if i < 0 || i >= Is_Muted(len(_Is_MutedIndex)-1) {
		return fmt.Sprintf("Is_Muted(%d)", i)
	}
	return _Is_MutedName[_Is_MutedIndex[i]:_Is_MutedIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _Is_MutedNoOp() {
	var x [1]struct{}
	_ = x[Is_Muted_No-(0)]
	_ = x[Is_Muted_Yes-(1)]
}

var _Is_MutedValues = []Is_Muted{Is_Muted_No, Is_Muted_Yes}

var _Is_MutedNameToValueMap = map[string]Is_Muted{
	_Is_MutedName[0:2]:      Is_Muted_No,
	_Is_MutedLowerName[0:2]: Is_Muted_No,
	_Is_MutedName[2:5]:      Is_Muted_Yes,
	_Is_MutedLowerName[2:5]: Is_Muted_Yes,
}

var _Is_MutedNames = []string{
	_Is_MutedName[0:2],
	_Is_MutedName[2:5],
}

// Is_MutedString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func Is_MutedString(s string) (Is_Muted, error) {
	if val, ok := _Is_MutedNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _Is_MutedNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Is_Muted values", s)
}

// Is_MutedValues returns all values of the enum
func Is_MutedValues() []Is_Muted {
	return _Is_MutedValues
}

// Is_MutedStrings returns a slice of all String values of the enum
func Is_MutedStrings() []string {
	strs := make([]string, len(_Is_MutedNames))
	copy(strs, _Is_MutedNames)
	return strs
}

// IsAIs_Muted returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Is_Muted) IsAIs_Muted() bool {
	for _, v := range _Is_MutedValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Is_Muted
func (i Is_Muted) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Is_Muted
func (i *Is_Muted) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Is_Muted should be a string, got %s", data)
	}

	var err error
	*i, err = Is_MutedString(s)
	return err
}

func (i Is_Muted) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Is_Muted) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Is_Muted: %[1]T(%[1]v)", value)
	}

	val, err := Is_MutedString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
