// Code generated by "enumer -type=StatusFriendship -json -sql -transform=snake -trimprefix=Type_Block"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _StatusFriendshipName = "status_friendship_pendingstatus_friendship_acceptedstatus_friendship_declinedstatus_friendship_blocked"

var _StatusFriendshipIndex = [...]uint8{0, 25, 51, 77, 102}

const _StatusFriendshipLowerName = "status_friendship_pendingstatus_friendship_acceptedstatus_friendship_declinedstatus_friendship_blocked"

func (i StatusFriendship) String() string {
	if i < 0 || i >= StatusFriendship(len(_StatusFriendshipIndex)-1) {
		return fmt.Sprintf("StatusFriendship(%d)", i)
	}
	return _StatusFriendshipName[_StatusFriendshipIndex[i]:_StatusFriendshipIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StatusFriendshipNoOp() {
	var x [1]struct{}
	_ = x[StatusFriendship_Pending-(0)]
	_ = x[StatusFriendship_Accepted-(1)]
	_ = x[StatusFriendship_Declined-(2)]
	_ = x[StatusFriendship_Blocked-(3)]
}

var _StatusFriendshipValues = []StatusFriendship{StatusFriendship_Pending, StatusFriendship_Accepted, StatusFriendship_Declined, StatusFriendship_Blocked}

var _StatusFriendshipNameToValueMap = map[string]StatusFriendship{
	_StatusFriendshipName[0:25]:        StatusFriendship_Pending,
	_StatusFriendshipLowerName[0:25]:   StatusFriendship_Pending,
	_StatusFriendshipName[25:51]:       StatusFriendship_Accepted,
	_StatusFriendshipLowerName[25:51]:  StatusFriendship_Accepted,
	_StatusFriendshipName[51:77]:       StatusFriendship_Declined,
	_StatusFriendshipLowerName[51:77]:  StatusFriendship_Declined,
	_StatusFriendshipName[77:102]:      StatusFriendship_Blocked,
	_StatusFriendshipLowerName[77:102]: StatusFriendship_Blocked,
}

var _StatusFriendshipNames = []string{
	_StatusFriendshipName[0:25],
	_StatusFriendshipName[25:51],
	_StatusFriendshipName[51:77],
	_StatusFriendshipName[77:102],
}

// StatusFriendshipString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusFriendshipString(s string) (StatusFriendship, error) {
	if val, ok := _StatusFriendshipNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StatusFriendshipNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to StatusFriendship values", s)
}

// StatusFriendshipValues returns all values of the enum
func StatusFriendshipValues() []StatusFriendship {
	return _StatusFriendshipValues
}

// StatusFriendshipStrings returns a slice of all String values of the enum
func StatusFriendshipStrings() []string {
	strs := make([]string, len(_StatusFriendshipNames))
	copy(strs, _StatusFriendshipNames)
	return strs
}

// IsAStatusFriendship returns "true" if the value is listed in the enum definition. "false" otherwise
func (i StatusFriendship) IsAStatusFriendship() bool {
	for _, v := range _StatusFriendshipValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for StatusFriendship
func (i StatusFriendship) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for StatusFriendship
func (i *StatusFriendship) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("StatusFriendship should be a string, got %s", data)
	}

	var err error
	*i, err = StatusFriendshipString(s)
	return err
}

func (i StatusFriendship) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *StatusFriendship) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of StatusFriendship: %[1]T(%[1]v)", value)
	}

	val, err := StatusFriendshipString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
