// Code generated by "enumer -type=Type_Block -json -sql -transform=snake -trimprefix=Type_Block"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _Type_BlockName = "fullpartialchatprofilenone"

var _Type_BlockIndex = [...]uint8{0, 4, 11, 15, 22, 26}

const _Type_BlockLowerName = "fullpartialchatprofilenone"

func (i Type_Block) String() string {
	if i < 0 || i >= Type_Block(len(_Type_BlockIndex)-1) {
		return fmt.Sprintf("Type_Block(%d)", i)
	}
	return _Type_BlockName[_Type_BlockIndex[i]:_Type_BlockIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _Type_BlockNoOp() {
	var x [1]struct{}
	_ = x[Type_Block_Full-(0)]
	_ = x[Type_Block_Partial-(1)]
	_ = x[Type_Block_Chat-(2)]
	_ = x[Type_Block_Profile-(3)]
	_ = x[Type_Block_None-(4)]
}

var _Type_BlockValues = []Type_Block{Type_Block_Full, Type_Block_Partial, Type_Block_Chat, Type_Block_Profile, Type_Block_None}

var _Type_BlockNameToValueMap = map[string]Type_Block{
	_Type_BlockName[0:4]:        Type_Block_Full,
	_Type_BlockLowerName[0:4]:   Type_Block_Full,
	_Type_BlockName[4:11]:       Type_Block_Partial,
	_Type_BlockLowerName[4:11]:  Type_Block_Partial,
	_Type_BlockName[11:15]:      Type_Block_Chat,
	_Type_BlockLowerName[11:15]: Type_Block_Chat,
	_Type_BlockName[15:22]:      Type_Block_Profile,
	_Type_BlockLowerName[15:22]: Type_Block_Profile,
	_Type_BlockName[22:26]:      Type_Block_None,
	_Type_BlockLowerName[22:26]: Type_Block_None,
}

var _Type_BlockNames = []string{
	_Type_BlockName[0:4],
	_Type_BlockName[4:11],
	_Type_BlockName[11:15],
	_Type_BlockName[15:22],
	_Type_BlockName[22:26],
}

// Type_BlockString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func Type_BlockString(s string) (Type_Block, error) {
	if val, ok := _Type_BlockNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _Type_BlockNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Type_Block values", s)
}

// Type_BlockValues returns all values of the enum
func Type_BlockValues() []Type_Block {
	return _Type_BlockValues
}

// Type_BlockStrings returns a slice of all String values of the enum
func Type_BlockStrings() []string {
	strs := make([]string, len(_Type_BlockNames))
	copy(strs, _Type_BlockNames)
	return strs
}

// IsAType_Block returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Type_Block) IsAType_Block() bool {
	for _, v := range _Type_BlockValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Type_Block
func (i Type_Block) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Type_Block
func (i *Type_Block) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Type_Block should be a string, got %s", data)
	}

	var err error
	*i, err = Type_BlockString(s)
	return err
}

func (i Type_Block) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Type_Block) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Type_Block: %[1]T(%[1]v)", value)
	}

	val, err := Type_BlockString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
