// Code generated by "enumer -type=CommentMediaType -json -transform=snake -trimprefix=CommentMedia"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _CommentMediaTypeName = "imagegifstickervideo"

var _CommentMediaTypeIndex = [...]uint8{0, 5, 8, 15, 20}

const _CommentMediaTypeLowerName = "imagegifstickervideo"

func (i CommentMediaType) String() string {
	if i < 0 || i >= CommentMediaType(len(_CommentMediaTypeIndex)-1) {
		return fmt.Sprintf("CommentMediaType(%d)", i)
	}
	return _CommentMediaTypeName[_CommentMediaTypeIndex[i]:_CommentMediaTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CommentMediaTypeNoOp() {
	var x [1]struct{}
	_ = x[CommentMediaImage-(0)]
	_ = x[CommentMediaGif-(1)]
	_ = x[CommentMediaSticker-(2)]
	_ = x[CommentMediaVideo-(3)]
}

var _CommentMediaTypeValues = []CommentMediaType{CommentMediaImage, CommentMediaGif, CommentMediaSticker, CommentMediaVideo}

var _CommentMediaTypeNameToValueMap = map[string]CommentMediaType{
	_CommentMediaTypeName[0:5]:        CommentMediaImage,
	_CommentMediaTypeLowerName[0:5]:   CommentMediaImage,
	_CommentMediaTypeName[5:8]:        CommentMediaGif,
	_CommentMediaTypeLowerName[5:8]:   CommentMediaGif,
	_CommentMediaTypeName[8:15]:       CommentMediaSticker,
	_CommentMediaTypeLowerName[8:15]:  CommentMediaSticker,
	_CommentMediaTypeName[15:20]:      CommentMediaVideo,
	_CommentMediaTypeLowerName[15:20]: CommentMediaVideo,
}

var _CommentMediaTypeNames = []string{
	_CommentMediaTypeName[0:5],
	_CommentMediaTypeName[5:8],
	_CommentMediaTypeName[8:15],
	_CommentMediaTypeName[15:20],
}

// CommentMediaTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CommentMediaTypeString(s string) (CommentMediaType, error) {
	if val, ok := _CommentMediaTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CommentMediaTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CommentMediaType values", s)
}

// CommentMediaTypeValues returns all values of the enum
func CommentMediaTypeValues() []CommentMediaType {
	return _CommentMediaTypeValues
}

// CommentMediaTypeStrings returns a slice of all String values of the enum
func CommentMediaTypeStrings() []string {
	strs := make([]string, len(_CommentMediaTypeNames))
	copy(strs, _CommentMediaTypeNames)
	return strs
}

// IsACommentMediaType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CommentMediaType) IsACommentMediaType() bool {
	for _, v := range _CommentMediaTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CommentMediaType
func (i CommentMediaType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CommentMediaType
func (i *CommentMediaType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CommentMediaType should be a string, got %s", data)
	}

	var err error
	*i, err = CommentMediaTypeString(s)
	return err
}
