// Code generated by "enumer -type=CommentStatus -json -transform=snake -trimprefix=CommentStatus"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _CommentStatusName = "activehiddendeletedpending"

var _CommentStatusIndex = [...]uint8{0, 6, 12, 19, 26}

const _CommentStatusLowerName = "activehiddendeletedpending"

func (i CommentStatus) String() string {
	if i < 0 || i >= CommentStatus(len(_CommentStatusIndex)-1) {
		return fmt.Sprintf("CommentStatus(%d)", i)
	}
	return _CommentStatusName[_CommentStatusIndex[i]:_CommentStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CommentStatusNoOp() {
	var x [1]struct{}
	_ = x[CommentStatusActive-(0)]
	_ = x[CommentStatusHidden-(1)]
	_ = x[CommentStatusDeleted-(2)]
	_ = x[CommentStatusPending-(3)]
}

var _CommentStatusValues = []CommentStatus{CommentStatusActive, CommentStatusHidden, CommentStatusDeleted, CommentStatusPending}

var _CommentStatusNameToValueMap = map[string]CommentStatus{
	_CommentStatusName[0:6]:        CommentStatusActive,
	_CommentStatusLowerName[0:6]:   CommentStatusActive,
	_CommentStatusName[6:12]:       CommentStatusHidden,
	_CommentStatusLowerName[6:12]:  CommentStatusHidden,
	_CommentStatusName[12:19]:      CommentStatusDeleted,
	_CommentStatusLowerName[12:19]: CommentStatusDeleted,
	_CommentStatusName[19:26]:      CommentStatusPending,
	_CommentStatusLowerName[19:26]: CommentStatusPending,
}

var _CommentStatusNames = []string{
	_CommentStatusName[0:6],
	_CommentStatusName[6:12],
	_CommentStatusName[12:19],
	_CommentStatusName[19:26],
}

// CommentStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CommentStatusString(s string) (CommentStatus, error) {
	if val, ok := _CommentStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CommentStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CommentStatus values", s)
}

// CommentStatusValues returns all values of the enum
func CommentStatusValues() []CommentStatus {
	return _CommentStatusValues
}

// CommentStatusStrings returns a slice of all String values of the enum
func CommentStatusStrings() []string {
	strs := make([]string, len(_CommentStatusNames))
	copy(strs, _CommentStatusNames)
	return strs
}

// IsACommentStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CommentStatus) IsACommentStatus() bool {
	for _, v := range _CommentStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CommentStatus
func (i CommentStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CommentStatus
func (i *CommentStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CommentStatus should be a string, got %s", data)
	}

	var err error
	*i, err = CommentStatusString(s)
	return err
}
