// Code generated by "enumer -type=ReactionCode -json -transform=snake -trimprefix=Reaction"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ReactionCodeName = "likelovehahasadangrywow"

var _ReactionCodeIndex = [...]uint8{0, 4, 8, 12, 15, 20, 23}

const _ReactionCodeLowerName = "likelovehahasadangrywow"

func (i ReactionCode) String() string {
	if i < 0 || i >= ReactionCode(len(_ReactionCodeIndex)-1) {
		return fmt.Sprintf("ReactionCode(%d)", i)
	}
	return _ReactionCodeName[_ReactionCodeIndex[i]:_ReactionCodeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ReactionCodeNoOp() {
	var x [1]struct{}
	_ = x[ReactionLike-(0)]
	_ = x[ReactionLove-(1)]
	_ = x[ReactionHaha-(2)]
	_ = x[ReactionSad-(3)]
	_ = x[ReactionAngry-(4)]
	_ = x[ReactionWow-(5)]
}

var _ReactionCodeValues = []ReactionCode{ReactionLike, ReactionLove, ReactionHaha, ReactionSad, ReactionAngry, ReactionWow}

var _ReactionCodeNameToValueMap = map[string]ReactionCode{
	_ReactionCodeName[0:4]:        ReactionLike,
	_ReactionCodeLowerName[0:4]:   ReactionLike,
	_ReactionCodeName[4:8]:        ReactionLove,
	_ReactionCodeLowerName[4:8]:   ReactionLove,
	_ReactionCodeName[8:12]:       ReactionHaha,
	_ReactionCodeLowerName[8:12]:  ReactionHaha,
	_ReactionCodeName[12:15]:      ReactionSad,
	_ReactionCodeLowerName[12:15]: ReactionSad,
	_ReactionCodeName[15:20]:      ReactionAngry,
	_ReactionCodeLowerName[15:20]: ReactionAngry,
	_ReactionCodeName[20:23]:      ReactionWow,
	_ReactionCodeLowerName[20:23]: ReactionWow,
}

var _ReactionCodeNames = []string{
	_ReactionCodeName[0:4],
	_ReactionCodeName[4:8],
	_ReactionCodeName[8:12],
	_ReactionCodeName[12:15],
	_ReactionCodeName[15:20],
	_ReactionCodeName[20:23],
}

// ReactionCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ReactionCodeString(s string) (ReactionCode, error) {
	if val, ok := _ReactionCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ReactionCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ReactionCode values", s)
}

// ReactionCodeValues returns all values of the enum
func ReactionCodeValues() []ReactionCode {
	return _ReactionCodeValues
}

// ReactionCodeStrings returns a slice of all String values of the enum
func ReactionCodeStrings() []string {
	strs := make([]string, len(_ReactionCodeNames))
	copy(strs, _ReactionCodeNames)
	return strs
}

// IsAReactionCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ReactionCode) IsAReactionCode() bool {
	for _, v := range _ReactionCodeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ReactionCode
func (i ReactionCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ReactionCode
func (i *ReactionCode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ReactionCode should be a string, got %s", data)
	}

	var err error
	*i, err = ReactionCodeString(s)
	return err
}
