package resolver

// // This file will be automatically regenerated based on the schema, any resolver
// // implementations
// // will be copied through when generating and any unknown code will be moved to the end.
// // Code generated by github.com/99designs/gqlgen version v0.17.86

// import (
// 	"context"
// 	"fmt"

// 	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/graphQL/generated"
// 	"github.com/NguyenNhatquang522004/BE-modular-golang/internal/graphQL/model"
// )

// // Posts is the resolver for the posts field.
// func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
// // Gọi UseCase của module Social
// 	posts, err := r.SocialPostUseCase.GetTimeline(ctx)
// 	if err != nil {
// 		return nil, err
// 	}
    
//     // Convert Domain Post -> GraphQL Model Post
// 	var result []*model.Post
// 	for _, p := range posts {
// 		result = append(result, &model.Post{
// 			ID:       p.ID,
// 			Content:  p.Content,
// 			AuthorID: p.AuthorID, 
//             // Lưu ý: Field 'Author' chưa có data ở đây, để rỗng hoặc nil
// 		})
// 	}
// 	return result, nil
// }
// func (r *postResolver) Author(ctx context.Context, obj *model.Post) (*model.User, error) {
//     // Dùng DataLoader đã inject trong middleware
//     // Nó sẽ gom userIDs của 10-20 bài post lại và gọi DB 1 lần
// 	userDomain, err := dataloader.GetUser(ctx, obj.AuthorID)
// 	if err != nil {
// 		return nil, err
// 	}

// 	return &model.User{
// 		ID:   userDomain.ID,
// 		Name: userDomain.Name,
// 	}, nil
// }
// // User is the resolver for the user field.
// func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
// 	panic(fmt.Errorf("not implemented: User - user"))
// }

// Query returns generated.QueryResolver implementation.
// func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// type queryResolver struct{ *Resolver }
