// Code generated by "enumer -type=ActivityType -json -transform=snake -trimprefix=Activity"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ActivityTypeName = "feelingwatchingreadinglisteningtravelingeatingcelebrating"

var _ActivityTypeIndex = [...]uint8{0, 7, 15, 22, 31, 40, 46, 57}

const _ActivityTypeLowerName = "feelingwatchingreadinglisteningtravelingeatingcelebrating"

func (i ActivityType) String() string {
	if i < 0 || i >= ActivityType(len(_ActivityTypeIndex)-1) {
		return fmt.Sprintf("ActivityType(%d)", i)
	}
	return _ActivityTypeName[_ActivityTypeIndex[i]:_ActivityTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ActivityTypeNoOp() {
	var x [1]struct{}
	_ = x[ActivityFeeling-(0)]
	_ = x[ActivityWatching-(1)]
	_ = x[ActivityReading-(2)]
	_ = x[ActivityListening-(3)]
	_ = x[ActivityTraveling-(4)]
	_ = x[ActivityEating-(5)]
	_ = x[ActivityCelebrating-(6)]
}

var _ActivityTypeValues = []ActivityType{ActivityFeeling, ActivityWatching, ActivityReading, ActivityListening, ActivityTraveling, ActivityEating, ActivityCelebrating}

var _ActivityTypeNameToValueMap = map[string]ActivityType{
	_ActivityTypeName[0:7]:        ActivityFeeling,
	_ActivityTypeLowerName[0:7]:   ActivityFeeling,
	_ActivityTypeName[7:15]:       ActivityWatching,
	_ActivityTypeLowerName[7:15]:  ActivityWatching,
	_ActivityTypeName[15:22]:      ActivityReading,
	_ActivityTypeLowerName[15:22]: ActivityReading,
	_ActivityTypeName[22:31]:      ActivityListening,
	_ActivityTypeLowerName[22:31]: ActivityListening,
	_ActivityTypeName[31:40]:      ActivityTraveling,
	_ActivityTypeLowerName[31:40]: ActivityTraveling,
	_ActivityTypeName[40:46]:      ActivityEating,
	_ActivityTypeLowerName[40:46]: ActivityEating,
	_ActivityTypeName[46:57]:      ActivityCelebrating,
	_ActivityTypeLowerName[46:57]: ActivityCelebrating,
}

var _ActivityTypeNames = []string{
	_ActivityTypeName[0:7],
	_ActivityTypeName[7:15],
	_ActivityTypeName[15:22],
	_ActivityTypeName[22:31],
	_ActivityTypeName[31:40],
	_ActivityTypeName[40:46],
	_ActivityTypeName[46:57],
}

// ActivityTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ActivityTypeString(s string) (ActivityType, error) {
	if val, ok := _ActivityTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ActivityTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ActivityType values", s)
}

// ActivityTypeValues returns all values of the enum
func ActivityTypeValues() []ActivityType {
	return _ActivityTypeValues
}

// ActivityTypeStrings returns a slice of all String values of the enum
func ActivityTypeStrings() []string {
	strs := make([]string, len(_ActivityTypeNames))
	copy(strs, _ActivityTypeNames)
	return strs
}

// IsAActivityType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ActivityType) IsAActivityType() bool {
	for _, v := range _ActivityTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ActivityType
func (i ActivityType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ActivityType
func (i *ActivityType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ActivityType should be a string, got %s", data)
	}

	var err error
	*i, err = ActivityTypeString(s)
	return err
}
