// Code generated by "enumer -type=CallType -json -transform=snake -trimprefix=CallType"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _CallTypeName = "voicevideo"

var _CallTypeIndex = [...]uint8{0, 5, 10}

const _CallTypeLowerName = "voicevideo"

func (i CallType) String() string {
	if i < 0 || i >= CallType(len(_CallTypeIndex)-1) {
		return fmt.Sprintf("CallType(%d)", i)
	}
	return _CallTypeName[_CallTypeIndex[i]:_CallTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CallTypeNoOp() {
	var x [1]struct{}
	_ = x[CallTypeVoice-(0)]
	_ = x[CallTypeVideo-(1)]
}

var _CallTypeValues = []CallType{CallTypeVoice, CallTypeVideo}

var _CallTypeNameToValueMap = map[string]CallType{
	_CallTypeName[0:5]:       CallTypeVoice,
	_CallTypeLowerName[0:5]:  CallTypeVoice,
	_CallTypeName[5:10]:      CallTypeVideo,
	_CallTypeLowerName[5:10]: CallTypeVideo,
}

var _CallTypeNames = []string{
	_CallTypeName[0:5],
	_CallTypeName[5:10],
}

// CallTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CallTypeString(s string) (CallType, error) {
	if val, ok := _CallTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CallTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CallType values", s)
}

// CallTypeValues returns all values of the enum
func CallTypeValues() []CallType {
	return _CallTypeValues
}

// CallTypeStrings returns a slice of all String values of the enum
func CallTypeStrings() []string {
	strs := make([]string, len(_CallTypeNames))
	copy(strs, _CallTypeNames)
	return strs
}

// IsACallType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CallType) IsACallType() bool {
	for _, v := range _CallTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CallType
func (i CallType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CallType
func (i *CallType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CallType should be a string, got %s", data)
	}

	var err error
	*i, err = CallTypeString(s)
	return err
}
