// Code generated by "enumer -type=CallStatus -json -transform=snake -trimprefix=CallStatus"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _CallStatusName = "missedendedrejectedbusy"

var _CallStatusIndex = [...]uint8{0, 6, 11, 19, 23}

const _CallStatusLowerName = "missedendedrejectedbusy"

func (i CallStatus) String() string {
	if i < 0 || i >= CallStatus(len(_CallStatusIndex)-1) {
		return fmt.Sprintf("CallStatus(%d)", i)
	}
	return _CallStatusName[_CallStatusIndex[i]:_CallStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CallStatusNoOp() {
	var x [1]struct{}
	_ = x[CallStatusMissed-(0)]
	_ = x[CallStatusEnded-(1)]
	_ = x[CallStatusRejected-(2)]
	_ = x[CallStatusBusy-(3)]
}

var _CallStatusValues = []CallStatus{CallStatusMissed, CallStatusEnded, CallStatusRejected, CallStatusBusy}

var _CallStatusNameToValueMap = map[string]CallStatus{
	_CallStatusName[0:6]:        CallStatusMissed,
	_CallStatusLowerName[0:6]:   CallStatusMissed,
	_CallStatusName[6:11]:       CallStatusEnded,
	_CallStatusLowerName[6:11]:  CallStatusEnded,
	_CallStatusName[11:19]:      CallStatusRejected,
	_CallStatusLowerName[11:19]: CallStatusRejected,
	_CallStatusName[19:23]:      CallStatusBusy,
	_CallStatusLowerName[19:23]: CallStatusBusy,
}

var _CallStatusNames = []string{
	_CallStatusName[0:6],
	_CallStatusName[6:11],
	_CallStatusName[11:19],
	_CallStatusName[19:23],
}

// CallStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CallStatusString(s string) (CallStatus, error) {
	if val, ok := _CallStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CallStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CallStatus values", s)
}

// CallStatusValues returns all values of the enum
func CallStatusValues() []CallStatus {
	return _CallStatusValues
}

// CallStatusStrings returns a slice of all String values of the enum
func CallStatusStrings() []string {
	strs := make([]string, len(_CallStatusNames))
	copy(strs, _CallStatusNames)
	return strs
}

// IsACallStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CallStatus) IsACallStatus() bool {
	for _, v := range _CallStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CallStatus
func (i CallStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CallStatus
func (i *CallStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CallStatus should be a string, got %s", data)
	}

	var err error
	*i, err = CallStatusString(s)
	return err
}
