// Code generated by "enumer -type=ContextType -json -transform=snake -trimprefix=ContextType"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ContextTypeName = "user_wallgrouppage"

var _ContextTypeIndex = [...]uint8{0, 9, 14, 18}

const _ContextTypeLowerName = "user_wallgrouppage"

func (i ContextType) String() string {
	if i < 0 || i >= ContextType(len(_ContextTypeIndex)-1) {
		return fmt.Sprintf("ContextType(%d)", i)
	}
	return _ContextTypeName[_ContextTypeIndex[i]:_ContextTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ContextTypeNoOp() {
	var x [1]struct{}
	_ = x[ContextTypeUserWall-(0)]
	_ = x[ContextTypeGroup-(1)]
	_ = x[ContextTypePage-(2)]
}

var _ContextTypeValues = []ContextType{ContextTypeUserWall, ContextTypeGroup, ContextTypePage}

var _ContextTypeNameToValueMap = map[string]ContextType{
	_ContextTypeName[0:9]:        ContextTypeUserWall,
	_ContextTypeLowerName[0:9]:   ContextTypeUserWall,
	_ContextTypeName[9:14]:       ContextTypeGroup,
	_ContextTypeLowerName[9:14]:  ContextTypeGroup,
	_ContextTypeName[14:18]:      ContextTypePage,
	_ContextTypeLowerName[14:18]: ContextTypePage,
}

var _ContextTypeNames = []string{
	_ContextTypeName[0:9],
	_ContextTypeName[9:14],
	_ContextTypeName[14:18],
}

// ContextTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ContextTypeString(s string) (ContextType, error) {
	if val, ok := _ContextTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ContextTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ContextType values", s)
}

// ContextTypeValues returns all values of the enum
func ContextTypeValues() []ContextType {
	return _ContextTypeValues
}

// ContextTypeStrings returns a slice of all String values of the enum
func ContextTypeStrings() []string {
	strs := make([]string, len(_ContextTypeNames))
	copy(strs, _ContextTypeNames)
	return strs
}

// IsAContextType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ContextType) IsAContextType() bool {
	for _, v := range _ContextTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ContextType
func (i ContextType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ContextType
func (i *ContextType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ContextType should be a string, got %s", data)
	}

	var err error
	*i, err = ContextTypeString(s)
	return err
}
