// Code generated by "enumer -type=ConversationScope -json -transform=snake -trimprefix=Scope"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ConversationScopeName = "messengercommunity_channel"

var _ConversationScopeIndex = [...]uint8{0, 9, 26}

const _ConversationScopeLowerName = "messengercommunity_channel"

func (i ConversationScope) String() string {
	if i < 0 || i >= ConversationScope(len(_ConversationScopeIndex)-1) {
		return fmt.Sprintf("ConversationScope(%d)", i)
	}
	return _ConversationScopeName[_ConversationScopeIndex[i]:_ConversationScopeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ConversationScopeNoOp() {
	var x [1]struct{}
	_ = x[ScopeMessenger-(0)]
	_ = x[ScopeCommunityChannel-(1)]
}

var _ConversationScopeValues = []ConversationScope{ScopeMessenger, ScopeCommunityChannel}

var _ConversationScopeNameToValueMap = map[string]ConversationScope{
	_ConversationScopeName[0:9]:       ScopeMessenger,
	_ConversationScopeLowerName[0:9]:  ScopeMessenger,
	_ConversationScopeName[9:26]:      ScopeCommunityChannel,
	_ConversationScopeLowerName[9:26]: ScopeCommunityChannel,
}

var _ConversationScopeNames = []string{
	_ConversationScopeName[0:9],
	_ConversationScopeName[9:26],
}

// ConversationScopeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ConversationScopeString(s string) (ConversationScope, error) {
	if val, ok := _ConversationScopeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ConversationScopeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ConversationScope values", s)
}

// ConversationScopeValues returns all values of the enum
func ConversationScopeValues() []ConversationScope {
	return _ConversationScopeValues
}

// ConversationScopeStrings returns a slice of all String values of the enum
func ConversationScopeStrings() []string {
	strs := make([]string, len(_ConversationScopeNames))
	copy(strs, _ConversationScopeNames)
	return strs
}

// IsAConversationScope returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ConversationScope) IsAConversationScope() bool {
	for _, v := range _ConversationScopeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ConversationScope
func (i ConversationScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ConversationScope
func (i *ConversationScope) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ConversationScope should be a string, got %s", data)
	}

	var err error
	*i, err = ConversationScopeString(s)
	return err
}
