// Code generated by "enumer -type=EmailFrequency -json -transform=snake -trimprefix=Email"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _EmailFrequencyName = "dailyweeklynever"

var _EmailFrequencyIndex = [...]uint8{0, 5, 11, 16}

const _EmailFrequencyLowerName = "dailyweeklynever"

func (i EmailFrequency) String() string {
	if i < 0 || i >= EmailFrequency(len(_EmailFrequencyIndex)-1) {
		return fmt.Sprintf("EmailFrequency(%d)", i)
	}
	return _EmailFrequencyName[_EmailFrequencyIndex[i]:_EmailFrequencyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EmailFrequencyNoOp() {
	var x [1]struct{}
	_ = x[EmailDaily-(0)]
	_ = x[EmailWeekly-(1)]
	_ = x[EmailNever-(2)]
}

var _EmailFrequencyValues = []EmailFrequency{EmailDaily, EmailWeekly, EmailNever}

var _EmailFrequencyNameToValueMap = map[string]EmailFrequency{
	_EmailFrequencyName[0:5]:        EmailDaily,
	_EmailFrequencyLowerName[0:5]:   EmailDaily,
	_EmailFrequencyName[5:11]:       EmailWeekly,
	_EmailFrequencyLowerName[5:11]:  EmailWeekly,
	_EmailFrequencyName[11:16]:      EmailNever,
	_EmailFrequencyLowerName[11:16]: EmailNever,
}

var _EmailFrequencyNames = []string{
	_EmailFrequencyName[0:5],
	_EmailFrequencyName[5:11],
	_EmailFrequencyName[11:16],
}

// EmailFrequencyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EmailFrequencyString(s string) (EmailFrequency, error) {
	if val, ok := _EmailFrequencyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EmailFrequencyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EmailFrequency values", s)
}

// EmailFrequencyValues returns all values of the enum
func EmailFrequencyValues() []EmailFrequency {
	return _EmailFrequencyValues
}

// EmailFrequencyStrings returns a slice of all String values of the enum
func EmailFrequencyStrings() []string {
	strs := make([]string, len(_EmailFrequencyNames))
	copy(strs, _EmailFrequencyNames)
	return strs
}

// IsAEmailFrequency returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EmailFrequency) IsAEmailFrequency() bool {
	for _, v := range _EmailFrequencyValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EmailFrequency
func (i EmailFrequency) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EmailFrequency
func (i *EmailFrequency) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EmailFrequency should be a string, got %s", data)
	}

	var err error
	*i, err = EmailFrequencyString(s)
	return err
}
