// Code generated by "enumer -type=NotificationLevel -json -transform=snake -trimprefix=Notif"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _NotificationLevelName = "allhighlightoff"

var _NotificationLevelIndex = [...]uint8{0, 3, 12, 15}

const _NotificationLevelLowerName = "allhighlightoff"

func (i NotificationLevel) String() string {
	if i < 0 || i >= NotificationLevel(len(_NotificationLevelIndex)-1) {
		return fmt.Sprintf("NotificationLevel(%d)", i)
	}
	return _NotificationLevelName[_NotificationLevelIndex[i]:_NotificationLevelIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _NotificationLevelNoOp() {
	var x [1]struct{}
	_ = x[NotifAll-(0)]
	_ = x[NotifHighlight-(1)]
	_ = x[NotifOff-(2)]
}

var _NotificationLevelValues = []NotificationLevel{NotifAll, NotifHighlight, NotifOff}

var _NotificationLevelNameToValueMap = map[string]NotificationLevel{
	_NotificationLevelName[0:3]:        NotifAll,
	_NotificationLevelLowerName[0:3]:   NotifAll,
	_NotificationLevelName[3:12]:       NotifHighlight,
	_NotificationLevelLowerName[3:12]:  NotifHighlight,
	_NotificationLevelName[12:15]:      NotifOff,
	_NotificationLevelLowerName[12:15]: NotifOff,
}

var _NotificationLevelNames = []string{
	_NotificationLevelName[0:3],
	_NotificationLevelName[3:12],
	_NotificationLevelName[12:15],
}

// NotificationLevelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func NotificationLevelString(s string) (NotificationLevel, error) {
	if val, ok := _NotificationLevelNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _NotificationLevelNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to NotificationLevel values", s)
}

// NotificationLevelValues returns all values of the enum
func NotificationLevelValues() []NotificationLevel {
	return _NotificationLevelValues
}

// NotificationLevelStrings returns a slice of all String values of the enum
func NotificationLevelStrings() []string {
	strs := make([]string, len(_NotificationLevelNames))
	copy(strs, _NotificationLevelNames)
	return strs
}

// IsANotificationLevel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i NotificationLevel) IsANotificationLevel() bool {
	for _, v := range _NotificationLevelValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for NotificationLevel
func (i NotificationLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for NotificationLevel
func (i *NotificationLevel) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("NotificationLevel should be a string, got %s", data)
	}

	var err error
	*i, err = NotificationLevelString(s)
	return err
}
