// Code generated by "enumer -type=PostType -json -transform=snake -trimprefix=PostType"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PostTypeName = "textmediasharebackgroundqn_alive"

var _PostTypeIndex = [...]uint8{0, 4, 9, 14, 24, 28, 32}

const _PostTypeLowerName = "textmediasharebackgroundqn_alive"

func (i PostType) String() string {
	if i < 0 || i >= PostType(len(_PostTypeIndex)-1) {
		return fmt.Sprintf("PostType(%d)", i)
	}
	return _PostTypeName[_PostTypeIndex[i]:_PostTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PostTypeNoOp() {
	var x [1]struct{}
	_ = x[PostTypeText-(0)]
	_ = x[PostTypeMedia-(1)]
	_ = x[PostTypeShare-(2)]
	_ = x[PostTypeBackground-(3)]
	_ = x[PostTypeQnA-(4)]
	_ = x[PostTypeLive-(5)]
}

var _PostTypeValues = []PostType{PostTypeText, PostTypeMedia, PostTypeShare, PostTypeBackground, PostTypeQnA, PostTypeLive}

var _PostTypeNameToValueMap = map[string]PostType{
	_PostTypeName[0:4]:        PostTypeText,
	_PostTypeLowerName[0:4]:   PostTypeText,
	_PostTypeName[4:9]:        PostTypeMedia,
	_PostTypeLowerName[4:9]:   PostTypeMedia,
	_PostTypeName[9:14]:       PostTypeShare,
	_PostTypeLowerName[9:14]:  PostTypeShare,
	_PostTypeName[14:24]:      PostTypeBackground,
	_PostTypeLowerName[14:24]: PostTypeBackground,
	_PostTypeName[24:28]:      PostTypeQnA,
	_PostTypeLowerName[24:28]: PostTypeQnA,
	_PostTypeName[28:32]:      PostTypeLive,
	_PostTypeLowerName[28:32]: PostTypeLive,
}

var _PostTypeNames = []string{
	_PostTypeName[0:4],
	_PostTypeName[4:9],
	_PostTypeName[9:14],
	_PostTypeName[14:24],
	_PostTypeName[24:28],
	_PostTypeName[28:32],
}

// PostTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PostTypeString(s string) (PostType, error) {
	if val, ok := _PostTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PostTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PostType values", s)
}

// PostTypeValues returns all values of the enum
func PostTypeValues() []PostType {
	return _PostTypeValues
}

// PostTypeStrings returns a slice of all String values of the enum
func PostTypeStrings() []string {
	strs := make([]string, len(_PostTypeNames))
	copy(strs, _PostTypeNames)
	return strs
}

// IsAPostType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PostType) IsAPostType() bool {
	for _, v := range _PostTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PostType
func (i PostType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PostType
func (i *PostType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PostType should be a string, got %s", data)
	}

	var err error
	*i, err = PostTypeString(s)
	return err
}
