// Code generated by "enumer -type=PostStatus -json -transform=snake -trimprefix=Status"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PostStatusName = "publisheddraftarchivedhidden"

var _PostStatusIndex = [...]uint8{0, 9, 14, 22, 28}

const _PostStatusLowerName = "publisheddraftarchivedhidden"

func (i PostStatus) String() string {
	if i < 0 || i >= PostStatus(len(_PostStatusIndex)-1) {
		return fmt.Sprintf("PostStatus(%d)", i)
	}
	return _PostStatusName[_PostStatusIndex[i]:_PostStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PostStatusNoOp() {
	var x [1]struct{}
	_ = x[StatusPublished-(0)]
	_ = x[StatusDraft-(1)]
	_ = x[StatusArchived-(2)]
	_ = x[StatusHidden-(3)]
}

var _PostStatusValues = []PostStatus{StatusPublished, StatusDraft, StatusArchived, StatusHidden}

var _PostStatusNameToValueMap = map[string]PostStatus{
	_PostStatusName[0:9]:        StatusPublished,
	_PostStatusLowerName[0:9]:   StatusPublished,
	_PostStatusName[9:14]:       StatusDraft,
	_PostStatusLowerName[9:14]:  StatusDraft,
	_PostStatusName[14:22]:      StatusArchived,
	_PostStatusLowerName[14:22]: StatusArchived,
	_PostStatusName[22:28]:      StatusHidden,
	_PostStatusLowerName[22:28]: StatusHidden,
}

var _PostStatusNames = []string{
	_PostStatusName[0:9],
	_PostStatusName[9:14],
	_PostStatusName[14:22],
	_PostStatusName[22:28],
}

// PostStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PostStatusString(s string) (PostStatus, error) {
	if val, ok := _PostStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PostStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PostStatus values", s)
}

// PostStatusValues returns all values of the enum
func PostStatusValues() []PostStatus {
	return _PostStatusValues
}

// PostStatusStrings returns a slice of all String values of the enum
func PostStatusStrings() []string {
	strs := make([]string, len(_PostStatusNames))
	copy(strs, _PostStatusNames)
	return strs
}

// IsAPostStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PostStatus) IsAPostStatus() bool {
	for _, v := range _PostStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PostStatus
func (i PostStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PostStatus
func (i *PostStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PostStatus should be a string, got %s", data)
	}

	var err error
	*i, err = PostStatusString(s)
	return err
}
