// Code generated by "enumer -type=ReactionTarget -json -transform=snake -trimprefix=ReactionTarget"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ReactionTargetName = "postcomment"

var _ReactionTargetIndex = [...]uint8{0, 4, 11}

const _ReactionTargetLowerName = "postcomment"

func (i ReactionTarget) String() string {
	if i < 0 || i >= ReactionTarget(len(_ReactionTargetIndex)-1) {
		return fmt.Sprintf("ReactionTarget(%d)", i)
	}
	return _ReactionTargetName[_ReactionTargetIndex[i]:_ReactionTargetIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ReactionTargetNoOp() {
	var x [1]struct{}
	_ = x[ReactionTargetPost-(0)]
	_ = x[ReactionTargetComment-(1)]
}

var _ReactionTargetValues = []ReactionTarget{ReactionTargetPost, ReactionTargetComment}

var _ReactionTargetNameToValueMap = map[string]ReactionTarget{
	_ReactionTargetName[0:4]:       ReactionTargetPost,
	_ReactionTargetLowerName[0:4]:  ReactionTargetPost,
	_ReactionTargetName[4:11]:      ReactionTargetComment,
	_ReactionTargetLowerName[4:11]: ReactionTargetComment,
}

var _ReactionTargetNames = []string{
	_ReactionTargetName[0:4],
	_ReactionTargetName[4:11],
}

// ReactionTargetString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ReactionTargetString(s string) (ReactionTarget, error) {
	if val, ok := _ReactionTargetNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ReactionTargetNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ReactionTarget values", s)
}

// ReactionTargetValues returns all values of the enum
func ReactionTargetValues() []ReactionTarget {
	return _ReactionTargetValues
}

// ReactionTargetStrings returns a slice of all String values of the enum
func ReactionTargetStrings() []string {
	strs := make([]string, len(_ReactionTargetNames))
	copy(strs, _ReactionTargetNames)
	return strs
}

// IsAReactionTarget returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ReactionTarget) IsAReactionTarget() bool {
	for _, v := range _ReactionTargetValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ReactionTarget
func (i ReactionTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ReactionTarget
func (i *ReactionTarget) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ReactionTarget should be a string, got %s", data)
	}

	var err error
	*i, err = ReactionTargetString(s)
	return err
}
