// Code generated by "enumer -type=SavedTargetType -json -transform=snake -trimprefix=SavedTarget"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SavedTargetTypeName = "postreelvideo"

var _SavedTargetTypeIndex = [...]uint8{0, 4, 8, 13}

const _SavedTargetTypeLowerName = "postreelvideo"

func (i SavedTargetType) String() string {
	if i < 0 || i >= SavedTargetType(len(_SavedTargetTypeIndex)-1) {
		return fmt.Sprintf("SavedTargetType(%d)", i)
	}
	return _SavedTargetTypeName[_SavedTargetTypeIndex[i]:_SavedTargetTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SavedTargetTypeNoOp() {
	var x [1]struct{}
	_ = x[SavedTargetPost-(0)]
	_ = x[SavedTargetReel-(1)]
	_ = x[SavedTargetVideo-(2)]
}

var _SavedTargetTypeValues = []SavedTargetType{SavedTargetPost, SavedTargetReel, SavedTargetVideo}

var _SavedTargetTypeNameToValueMap = map[string]SavedTargetType{
	_SavedTargetTypeName[0:4]:       SavedTargetPost,
	_SavedTargetTypeLowerName[0:4]:  SavedTargetPost,
	_SavedTargetTypeName[4:8]:       SavedTargetReel,
	_SavedTargetTypeLowerName[4:8]:  SavedTargetReel,
	_SavedTargetTypeName[8:13]:      SavedTargetVideo,
	_SavedTargetTypeLowerName[8:13]: SavedTargetVideo,
}

var _SavedTargetTypeNames = []string{
	_SavedTargetTypeName[0:4],
	_SavedTargetTypeName[4:8],
	_SavedTargetTypeName[8:13],
}

// SavedTargetTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SavedTargetTypeString(s string) (SavedTargetType, error) {
	if val, ok := _SavedTargetTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SavedTargetTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SavedTargetType values", s)
}

// SavedTargetTypeValues returns all values of the enum
func SavedTargetTypeValues() []SavedTargetType {
	return _SavedTargetTypeValues
}

// SavedTargetTypeStrings returns a slice of all String values of the enum
func SavedTargetTypeStrings() []string {
	strs := make([]string, len(_SavedTargetTypeNames))
	copy(strs, _SavedTargetTypeNames)
	return strs
}

// IsASavedTargetType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SavedTargetType) IsASavedTargetType() bool {
	for _, v := range _SavedTargetTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SavedTargetType
func (i SavedTargetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SavedTargetType
func (i *SavedTargetType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SavedTargetType should be a string, got %s", data)
	}

	var err error
	*i, err = SavedTargetTypeString(s)
	return err
}
