// Code generated by "enumer -type=RoleType -json -transform=snake -trimprefix=RoleType"; DO NOT EDIT.

package sharedEnums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _RoleTypeName = "useradmin"

var _RoleTypeIndex = [...]uint8{0, 4, 9}

const _RoleTypeLowerName = "useradmin"

func (i RoleType) String() string {
	if i < 0 || i >= RoleType(len(_RoleTypeIndex)-1) {
		return fmt.Sprintf("RoleType(%d)", i)
	}
	return _RoleTypeName[_RoleTypeIndex[i]:_RoleTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RoleTypeNoOp() {
	var x [1]struct{}
	_ = x[RoleTypeUser-(0)]
	_ = x[RoleTypeAdmin-(1)]
}

var _RoleTypeValues = []RoleType{RoleTypeUser, RoleTypeAdmin}

var _RoleTypeNameToValueMap = map[string]RoleType{
	_RoleTypeName[0:4]:      RoleTypeUser,
	_RoleTypeLowerName[0:4]: RoleTypeUser,
	_RoleTypeName[4:9]:      RoleTypeAdmin,
	_RoleTypeLowerName[4:9]: RoleTypeAdmin,
}

var _RoleTypeNames = []string{
	_RoleTypeName[0:4],
	_RoleTypeName[4:9],
}

// RoleTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RoleTypeString(s string) (RoleType, error) {
	if val, ok := _RoleTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RoleTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RoleType values", s)
}

// RoleTypeValues returns all values of the enum
func RoleTypeValues() []RoleType {
	return _RoleTypeValues
}

// RoleTypeStrings returns a slice of all String values of the enum
func RoleTypeStrings() []string {
	strs := make([]string, len(_RoleTypeNames))
	copy(strs, _RoleTypeNames)
	return strs
}

// IsARoleType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RoleType) IsARoleType() bool {
	for _, v := range _RoleTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for RoleType
func (i RoleType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for RoleType
func (i *RoleType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("RoleType should be a string, got %s", data)
	}

	var err error
	*i, err = RoleTypeString(s)
	return err
}
