// Code generated by "enumer -type=EventLocationType -json -transform=snake -trimprefix=EventLocation"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _EventLocationTypeName = "onlineoffline"

var _EventLocationTypeIndex = [...]uint8{0, 6, 13}

const _EventLocationTypeLowerName = "onlineoffline"

func (i EventLocationType) String() string {
	if i < 0 || i >= EventLocationType(len(_EventLocationTypeIndex)-1) {
		return fmt.Sprintf("EventLocationType(%d)", i)
	}
	return _EventLocationTypeName[_EventLocationTypeIndex[i]:_EventLocationTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EventLocationTypeNoOp() {
	var x [1]struct{}
	_ = x[EventLocationOnline-(0)]
	_ = x[EventLocationOffline-(1)]
}

var _EventLocationTypeValues = []EventLocationType{EventLocationOnline, EventLocationOffline}

var _EventLocationTypeNameToValueMap = map[string]EventLocationType{
	_EventLocationTypeName[0:6]:       EventLocationOnline,
	_EventLocationTypeLowerName[0:6]:  EventLocationOnline,
	_EventLocationTypeName[6:13]:      EventLocationOffline,
	_EventLocationTypeLowerName[6:13]: EventLocationOffline,
}

var _EventLocationTypeNames = []string{
	_EventLocationTypeName[0:6],
	_EventLocationTypeName[6:13],
}

// EventLocationTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EventLocationTypeString(s string) (EventLocationType, error) {
	if val, ok := _EventLocationTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EventLocationTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EventLocationType values", s)
}

// EventLocationTypeValues returns all values of the enum
func EventLocationTypeValues() []EventLocationType {
	return _EventLocationTypeValues
}

// EventLocationTypeStrings returns a slice of all String values of the enum
func EventLocationTypeStrings() []string {
	strs := make([]string, len(_EventLocationTypeNames))
	copy(strs, _EventLocationTypeNames)
	return strs
}

// IsAEventLocationType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EventLocationType) IsAEventLocationType() bool {
	for _, v := range _EventLocationTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EventLocationType
func (i EventLocationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EventLocationType
func (i *EventLocationType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EventLocationType should be a string, got %s", data)
	}

	var err error
	*i, err = EventLocationTypeString(s)
	return err
}
