// Code generated by "enumer -type=FileType -json -transform=lower -trimprefix=FileType"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _FileTypeName = "otherpdfdocxxlsxpptxziprartxtcsv"

var _FileTypeIndex = [...]uint8{0, 5, 8, 12, 16, 20, 23, 26, 29, 32}

const _FileTypeLowerName = "otherpdfdocxxlsxpptxziprartxtcsv"

func (i FileType) String() string {
	if i < 0 || i >= FileType(len(_FileTypeIndex)-1) {
		return fmt.Sprintf("FileType(%d)", i)
	}
	return _FileTypeName[_FileTypeIndex[i]:_FileTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FileTypeNoOp() {
	var x [1]struct{}
	_ = x[FileTypeOther-(0)]
	_ = x[FileTypePDF-(1)]
	_ = x[FileTypeDOCX-(2)]
	_ = x[FileTypeXLSX-(3)]
	_ = x[FileTypePPTX-(4)]
	_ = x[FileTypeZIP-(5)]
	_ = x[FileTypeRAR-(6)]
	_ = x[FileTypeTXT-(7)]
	_ = x[FileTypeCSV-(8)]
}

var _FileTypeValues = []FileType{FileTypeOther, FileTypePDF, FileTypeDOCX, FileTypeXLSX, FileTypePPTX, FileTypeZIP, FileTypeRAR, FileTypeTXT, FileTypeCSV}

var _FileTypeNameToValueMap = map[string]FileType{
	_FileTypeName[0:5]:        FileTypeOther,
	_FileTypeLowerName[0:5]:   FileTypeOther,
	_FileTypeName[5:8]:        FileTypePDF,
	_FileTypeLowerName[5:8]:   FileTypePDF,
	_FileTypeName[8:12]:       FileTypeDOCX,
	_FileTypeLowerName[8:12]:  FileTypeDOCX,
	_FileTypeName[12:16]:      FileTypeXLSX,
	_FileTypeLowerName[12:16]: FileTypeXLSX,
	_FileTypeName[16:20]:      FileTypePPTX,
	_FileTypeLowerName[16:20]: FileTypePPTX,
	_FileTypeName[20:23]:      FileTypeZIP,
	_FileTypeLowerName[20:23]: FileTypeZIP,
	_FileTypeName[23:26]:      FileTypeRAR,
	_FileTypeLowerName[23:26]: FileTypeRAR,
	_FileTypeName[26:29]:      FileTypeTXT,
	_FileTypeLowerName[26:29]: FileTypeTXT,
	_FileTypeName[29:32]:      FileTypeCSV,
	_FileTypeLowerName[29:32]: FileTypeCSV,
}

var _FileTypeNames = []string{
	_FileTypeName[0:5],
	_FileTypeName[5:8],
	_FileTypeName[8:12],
	_FileTypeName[12:16],
	_FileTypeName[16:20],
	_FileTypeName[20:23],
	_FileTypeName[23:26],
	_FileTypeName[26:29],
	_FileTypeName[29:32],
}

// FileTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FileTypeString(s string) (FileType, error) {
	if val, ok := _FileTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FileTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FileType values", s)
}

// FileTypeValues returns all values of the enum
func FileTypeValues() []FileType {
	return _FileTypeValues
}

// FileTypeStrings returns a slice of all String values of the enum
func FileTypeStrings() []string {
	strs := make([]string, len(_FileTypeNames))
	copy(strs, _FileTypeNames)
	return strs
}

// IsAFileType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FileType) IsAFileType() bool {
	for _, v := range _FileTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FileType
func (i FileType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FileType
func (i *FileType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FileType should be a string, got %s", data)
	}

	var err error
	*i, err = FileTypeString(s)
	return err
}
