// Code generated by "enumer -type=GroupPrivacy -json -transform=snake -trimprefix=Privacy"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _GroupPrivacyName = "publicprivatesecret"

var _GroupPrivacyIndex = [...]uint8{0, 6, 13, 19}

const _GroupPrivacyLowerName = "publicprivatesecret"

func (i GroupPrivacy) String() string {
	if i < 0 || i >= GroupPrivacy(len(_GroupPrivacyIndex)-1) {
		return fmt.Sprintf("GroupPrivacy(%d)", i)
	}
	return _GroupPrivacyName[_GroupPrivacyIndex[i]:_GroupPrivacyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GroupPrivacyNoOp() {
	var x [1]struct{}
	_ = x[PrivacyPublic-(0)]
	_ = x[PrivacyPrivate-(1)]
	_ = x[PrivacySecret-(2)]
}

var _GroupPrivacyValues = []GroupPrivacy{PrivacyPublic, PrivacyPrivate, PrivacySecret}

var _GroupPrivacyNameToValueMap = map[string]GroupPrivacy{
	_GroupPrivacyName[0:6]:        PrivacyPublic,
	_GroupPrivacyLowerName[0:6]:   PrivacyPublic,
	_GroupPrivacyName[6:13]:       PrivacyPrivate,
	_GroupPrivacyLowerName[6:13]:  PrivacyPrivate,
	_GroupPrivacyName[13:19]:      PrivacySecret,
	_GroupPrivacyLowerName[13:19]: PrivacySecret,
}

var _GroupPrivacyNames = []string{
	_GroupPrivacyName[0:6],
	_GroupPrivacyName[6:13],
	_GroupPrivacyName[13:19],
}

// GroupPrivacyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GroupPrivacyString(s string) (GroupPrivacy, error) {
	if val, ok := _GroupPrivacyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GroupPrivacyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GroupPrivacy values", s)
}

// GroupPrivacyValues returns all values of the enum
func GroupPrivacyValues() []GroupPrivacy {
	return _GroupPrivacyValues
}

// GroupPrivacyStrings returns a slice of all String values of the enum
func GroupPrivacyStrings() []string {
	strs := make([]string, len(_GroupPrivacyNames))
	copy(strs, _GroupPrivacyNames)
	return strs
}

// IsAGroupPrivacy returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GroupPrivacy) IsAGroupPrivacy() bool {
	for _, v := range _GroupPrivacyValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for GroupPrivacy
func (i GroupPrivacy) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for GroupPrivacy
func (i *GroupPrivacy) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("GroupPrivacy should be a string, got %s", data)
	}

	var err error
	*i, err = GroupPrivacyString(s)
	return err
}
