// Code generated by "enumer -type=GroupApprover -json -transform=snake -trimprefix=Approver"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _GroupApproverName = "admineveryone"

var _GroupApproverIndex = [...]uint8{0, 5, 13}

const _GroupApproverLowerName = "admineveryone"

func (i GroupApprover) String() string {
	if i < 0 || i >= GroupApprover(len(_GroupApproverIndex)-1) {
		return fmt.Sprintf("GroupApprover(%d)", i)
	}
	return _GroupApproverName[_GroupApproverIndex[i]:_GroupApproverIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GroupApproverNoOp() {
	var x [1]struct{}
	_ = x[ApproverAdmin-(0)]
	_ = x[ApproverEveryone-(1)]
}

var _GroupApproverValues = []GroupApprover{ApproverAdmin, ApproverEveryone}

var _GroupApproverNameToValueMap = map[string]GroupApprover{
	_GroupApproverName[0:5]:       ApproverAdmin,
	_GroupApproverLowerName[0:5]:  ApproverAdmin,
	_GroupApproverName[5:13]:      ApproverEveryone,
	_GroupApproverLowerName[5:13]: ApproverEveryone,
}

var _GroupApproverNames = []string{
	_GroupApproverName[0:5],
	_GroupApproverName[5:13],
}

// GroupApproverString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GroupApproverString(s string) (GroupApprover, error) {
	if val, ok := _GroupApproverNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GroupApproverNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GroupApprover values", s)
}

// GroupApproverValues returns all values of the enum
func GroupApproverValues() []GroupApprover {
	return _GroupApproverValues
}

// GroupApproverStrings returns a slice of all String values of the enum
func GroupApproverStrings() []string {
	strs := make([]string, len(_GroupApproverNames))
	copy(strs, _GroupApproverNames)
	return strs
}

// IsAGroupApprover returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GroupApprover) IsAGroupApprover() bool {
	for _, v := range _GroupApproverValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for GroupApprover
func (i GroupApprover) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for GroupApprover
func (i *GroupApprover) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("GroupApprover should be a string, got %s", data)
	}

	var err error
	*i, err = GroupApproverString(s)
	return err
}
