// Code generated by "enumer -type=MemberRole -json -transform=snake -trimprefix=Role"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MemberRoleName = "memberadminmoderator"

var _MemberRoleIndex = [...]uint8{0, 6, 11, 20}

const _MemberRoleLowerName = "memberadminmoderator"

func (i MemberRole) String() string {
	if i < 0 || i >= MemberRole(len(_MemberRoleIndex)-1) {
		return fmt.Sprintf("MemberRole(%d)", i)
	}
	return _MemberRoleName[_MemberRoleIndex[i]:_MemberRoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MemberRoleNoOp() {
	var x [1]struct{}
	_ = x[RoleMember-(0)]
	_ = x[RoleAdmin-(1)]
	_ = x[RoleModerator-(2)]
}

var _MemberRoleValues = []MemberRole{RoleMember, RoleAdmin, RoleModerator}

var _MemberRoleNameToValueMap = map[string]MemberRole{
	_MemberRoleName[0:6]:        RoleMember,
	_MemberRoleLowerName[0:6]:   RoleMember,
	_MemberRoleName[6:11]:       RoleAdmin,
	_MemberRoleLowerName[6:11]:  RoleAdmin,
	_MemberRoleName[11:20]:      RoleModerator,
	_MemberRoleLowerName[11:20]: RoleModerator,
}

var _MemberRoleNames = []string{
	_MemberRoleName[0:6],
	_MemberRoleName[6:11],
	_MemberRoleName[11:20],
}

// MemberRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MemberRoleString(s string) (MemberRole, error) {
	if val, ok := _MemberRoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MemberRoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MemberRole values", s)
}

// MemberRoleValues returns all values of the enum
func MemberRoleValues() []MemberRole {
	return _MemberRoleValues
}

// MemberRoleStrings returns a slice of all String values of the enum
func MemberRoleStrings() []string {
	strs := make([]string, len(_MemberRoleNames))
	copy(strs, _MemberRoleNames)
	return strs
}

// IsAMemberRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MemberRole) IsAMemberRole() bool {
	for _, v := range _MemberRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MemberRole
func (i MemberRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MemberRole
func (i *MemberRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MemberRole should be a string, got %s", data)
	}

	var err error
	*i, err = MemberRoleString(s)
	return err
}
