// Code generated by "enumer -type=MemberBadge -json -transform=snake -trimprefix=Badge"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MemberBadgeName = "founding_membertop_contributorconversation_startervisual_storytellernew_member"

var _MemberBadgeIndex = [...]uint8{0, 15, 30, 50, 68, 78}

const _MemberBadgeLowerName = "founding_membertop_contributorconversation_startervisual_storytellernew_member"

func (i MemberBadge) String() string {
	if i < 0 || i >= MemberBadge(len(_MemberBadgeIndex)-1) {
		return fmt.Sprintf("MemberBadge(%d)", i)
	}
	return _MemberBadgeName[_MemberBadgeIndex[i]:_MemberBadgeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MemberBadgeNoOp() {
	var x [1]struct{}
	_ = x[BadgeFoundingMember-(0)]
	_ = x[BadgeTopContributor-(1)]
	_ = x[BadgeConversationStarter-(2)]
	_ = x[BadgeVisualStoryteller-(3)]
	_ = x[BadgeNewMember-(4)]
}

var _MemberBadgeValues = []MemberBadge{BadgeFoundingMember, BadgeTopContributor, BadgeConversationStarter, BadgeVisualStoryteller, BadgeNewMember}

var _MemberBadgeNameToValueMap = map[string]MemberBadge{
	_MemberBadgeName[0:15]:       BadgeFoundingMember,
	_MemberBadgeLowerName[0:15]:  BadgeFoundingMember,
	_MemberBadgeName[15:30]:      BadgeTopContributor,
	_MemberBadgeLowerName[15:30]: BadgeTopContributor,
	_MemberBadgeName[30:50]:      BadgeConversationStarter,
	_MemberBadgeLowerName[30:50]: BadgeConversationStarter,
	_MemberBadgeName[50:68]:      BadgeVisualStoryteller,
	_MemberBadgeLowerName[50:68]: BadgeVisualStoryteller,
	_MemberBadgeName[68:78]:      BadgeNewMember,
	_MemberBadgeLowerName[68:78]: BadgeNewMember,
}

var _MemberBadgeNames = []string{
	_MemberBadgeName[0:15],
	_MemberBadgeName[15:30],
	_MemberBadgeName[30:50],
	_MemberBadgeName[50:68],
	_MemberBadgeName[68:78],
}

// MemberBadgeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MemberBadgeString(s string) (MemberBadge, error) {
	if val, ok := _MemberBadgeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MemberBadgeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MemberBadge values", s)
}

// MemberBadgeValues returns all values of the enum
func MemberBadgeValues() []MemberBadge {
	return _MemberBadgeValues
}

// MemberBadgeStrings returns a slice of all String values of the enum
func MemberBadgeStrings() []string {
	strs := make([]string, len(_MemberBadgeNames))
	copy(strs, _MemberBadgeNames)
	return strs
}

// IsAMemberBadge returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MemberBadge) IsAMemberBadge() bool {
	for _, v := range _MemberBadgeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MemberBadge
func (i MemberBadge) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MemberBadge
func (i *MemberBadge) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MemberBadge should be a string, got %s", data)
	}

	var err error
	*i, err = MemberBadgeString(s)
	return err
}
