// Code generated by "enumer -type=MemberStatus -json -transform=snake -trimprefix=Status"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MemberStatusName = "activependinginvitedbannedmuted"

var _MemberStatusIndex = [...]uint8{0, 6, 13, 20, 26, 31}

const _MemberStatusLowerName = "activependinginvitedbannedmuted"

func (i MemberStatus) String() string {
	if i < 0 || i >= MemberStatus(len(_MemberStatusIndex)-1) {
		return fmt.Sprintf("MemberStatus(%d)", i)
	}
	return _MemberStatusName[_MemberStatusIndex[i]:_MemberStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MemberStatusNoOp() {
	var x [1]struct{}
	_ = x[StatusActive-(0)]
	_ = x[StatusPending-(1)]
	_ = x[StatusInvited-(2)]
	_ = x[StatusBanned-(3)]
	_ = x[StatusMuted-(4)]
}

var _MemberStatusValues = []MemberStatus{StatusActive, StatusPending, StatusInvited, StatusBanned, StatusMuted}

var _MemberStatusNameToValueMap = map[string]MemberStatus{
	_MemberStatusName[0:6]:        StatusActive,
	_MemberStatusLowerName[0:6]:   StatusActive,
	_MemberStatusName[6:13]:       StatusPending,
	_MemberStatusLowerName[6:13]:  StatusPending,
	_MemberStatusName[13:20]:      StatusInvited,
	_MemberStatusLowerName[13:20]: StatusInvited,
	_MemberStatusName[20:26]:      StatusBanned,
	_MemberStatusLowerName[20:26]: StatusBanned,
	_MemberStatusName[26:31]:      StatusMuted,
	_MemberStatusLowerName[26:31]: StatusMuted,
}

var _MemberStatusNames = []string{
	_MemberStatusName[0:6],
	_MemberStatusName[6:13],
	_MemberStatusName[13:20],
	_MemberStatusName[20:26],
	_MemberStatusName[26:31],
}

// MemberStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MemberStatusString(s string) (MemberStatus, error) {
	if val, ok := _MemberStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MemberStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MemberStatus values", s)
}

// MemberStatusValues returns all values of the enum
func MemberStatusValues() []MemberStatus {
	return _MemberStatusValues
}

// MemberStatusStrings returns a slice of all String values of the enum
func MemberStatusStrings() []string {
	strs := make([]string, len(_MemberStatusNames))
	copy(strs, _MemberStatusNames)
	return strs
}

// IsAMemberStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MemberStatus) IsAMemberStatus() bool {
	for _, v := range _MemberStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MemberStatus
func (i MemberStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MemberStatus
func (i *MemberStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MemberStatus should be a string, got %s", data)
	}

	var err error
	*i, err = MemberStatusString(s)
	return err
}
