// Code generated by "enumer -type=PrivacySearch -json -yaml -trimprefix=Privacy_Search_ -transform=snake"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PrivacySearchName = "unknownpublicclosedsecret"

var _PrivacySearchIndex = [...]uint8{0, 7, 13, 19, 25}

const _PrivacySearchLowerName = "unknownpublicclosedsecret"

func (i PrivacySearch) String() string {
	if i < 0 || i >= PrivacySearch(len(_PrivacySearchIndex)-1) {
		return fmt.Sprintf("PrivacySearch(%d)", i)
	}
	return _PrivacySearchName[_PrivacySearchIndex[i]:_PrivacySearchIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PrivacySearchNoOp() {
	var x [1]struct{}
	_ = x[Privacy_Search_Unknown-(0)]
	_ = x[Privacy_Search_Public-(1)]
	_ = x[Privacy_Search_Closed-(2)]
	_ = x[Privacy_Search_Secret-(3)]
}

var _PrivacySearchValues = []PrivacySearch{Privacy_Search_Unknown, Privacy_Search_Public, Privacy_Search_Closed, Privacy_Search_Secret}

var _PrivacySearchNameToValueMap = map[string]PrivacySearch{
	_PrivacySearchName[0:7]:        Privacy_Search_Unknown,
	_PrivacySearchLowerName[0:7]:   Privacy_Search_Unknown,
	_PrivacySearchName[7:13]:       Privacy_Search_Public,
	_PrivacySearchLowerName[7:13]:  Privacy_Search_Public,
	_PrivacySearchName[13:19]:      Privacy_Search_Closed,
	_PrivacySearchLowerName[13:19]: Privacy_Search_Closed,
	_PrivacySearchName[19:25]:      Privacy_Search_Secret,
	_PrivacySearchLowerName[19:25]: Privacy_Search_Secret,
}

var _PrivacySearchNames = []string{
	_PrivacySearchName[0:7],
	_PrivacySearchName[7:13],
	_PrivacySearchName[13:19],
	_PrivacySearchName[19:25],
}

// PrivacySearchString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PrivacySearchString(s string) (PrivacySearch, error) {
	if val, ok := _PrivacySearchNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PrivacySearchNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PrivacySearch values", s)
}

// PrivacySearchValues returns all values of the enum
func PrivacySearchValues() []PrivacySearch {
	return _PrivacySearchValues
}

// PrivacySearchStrings returns a slice of all String values of the enum
func PrivacySearchStrings() []string {
	strs := make([]string, len(_PrivacySearchNames))
	copy(strs, _PrivacySearchNames)
	return strs
}

// IsAPrivacySearch returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PrivacySearch) IsAPrivacySearch() bool {
	for _, v := range _PrivacySearchValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PrivacySearch
func (i PrivacySearch) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PrivacySearch
func (i *PrivacySearch) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PrivacySearch should be a string, got %s", data)
	}

	var err error
	*i, err = PrivacySearchString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for PrivacySearch
func (i PrivacySearch) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for PrivacySearch
func (i *PrivacySearch) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = PrivacySearchString(s)
	return err
}
