// Code generated by "enumer -type=QuestionType -json -transform=snake -trimprefix=QuestionType"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _QuestionTypeName = "textmultiple_choicecheckbox"

var _QuestionTypeIndex = [...]uint8{0, 4, 19, 27}

const _QuestionTypeLowerName = "textmultiple_choicecheckbox"

func (i QuestionType) String() string {
	if i < 0 || i >= QuestionType(len(_QuestionTypeIndex)-1) {
		return fmt.Sprintf("QuestionType(%d)", i)
	}
	return _QuestionTypeName[_QuestionTypeIndex[i]:_QuestionTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _QuestionTypeNoOp() {
	var x [1]struct{}
	_ = x[QuestionTypeText-(0)]
	_ = x[QuestionTypeMultipleChoice-(1)]
	_ = x[QuestionTypeCheckbox-(2)]
}

var _QuestionTypeValues = []QuestionType{QuestionTypeText, QuestionTypeMultipleChoice, QuestionTypeCheckbox}

var _QuestionTypeNameToValueMap = map[string]QuestionType{
	_QuestionTypeName[0:4]:        QuestionTypeText,
	_QuestionTypeLowerName[0:4]:   QuestionTypeText,
	_QuestionTypeName[4:19]:       QuestionTypeMultipleChoice,
	_QuestionTypeLowerName[4:19]:  QuestionTypeMultipleChoice,
	_QuestionTypeName[19:27]:      QuestionTypeCheckbox,
	_QuestionTypeLowerName[19:27]: QuestionTypeCheckbox,
}

var _QuestionTypeNames = []string{
	_QuestionTypeName[0:4],
	_QuestionTypeName[4:19],
	_QuestionTypeName[19:27],
}

// QuestionTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func QuestionTypeString(s string) (QuestionType, error) {
	if val, ok := _QuestionTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _QuestionTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to QuestionType values", s)
}

// QuestionTypeValues returns all values of the enum
func QuestionTypeValues() []QuestionType {
	return _QuestionTypeValues
}

// QuestionTypeStrings returns a slice of all String values of the enum
func QuestionTypeStrings() []string {
	strs := make([]string, len(_QuestionTypeNames))
	copy(strs, _QuestionTypeNames)
	return strs
}

// IsAQuestionType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i QuestionType) IsAQuestionType() bool {
	for _, v := range _QuestionTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for QuestionType
func (i QuestionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for QuestionType
func (i *QuestionType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("QuestionType should be a string, got %s", data)
	}

	var err error
	*i, err = QuestionTypeString(s)
	return err
}
