name: "BE-modular-golang"

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main
jobs:
    quality-check:
     name: Code Quality Check
     runs-on: ubuntu-latest
     steps: 
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: 'stable'
            check-latest: true
        - name: Run golangci-lint
          id : lint
          uses: golangci/golangci-lint-action@v6
          continue-on-error: true
          with:
            version: latest
            args: --timeout=5m ./... # Nên set timeout vì mặc định 1m đôi khi không đủ cho project lớn

        # - name: unit test 
        #   id : unit
        #   run: go test -v  -race -cover ./...

        - name : Security Scan
          id : sercurity
          uses: golang/govulncheck-action@v1
          continue-on-error: true
          with:
            go-version-file: go.mod
            repo-checkout: false
        - name : final  quality-check
          id : final-quality-check
          if : steps.lint.outcome == 'failure' ||  steps.sercurity.outcome == 'failure'
          run : |
              echo "❌ Có lỗi xảy ra trong quá trình kiểm tra!"
              echo "Lint status: ${{ steps.lint.outcome }}"
              echo "Security status: ${{ steps.sercurity.outcome }}"
              exit 1  # <--- Bắt buộc có lệnh này để đánh dấu Job là Failed
        

        
        

         